### ISSUE TITLE
rJava.rdb is corrupt? (jre1.8.0_131, R 3.3.3, rJava 0.9-8, Windows 10)

### ISSUE THREAD

**Issue by joseRey** [s-u/rJava#101]
I am getting the following when trying to load the rJava library (`library(rJava)`):

`Error in get(Info[i, 1], envir = env) : 
  lazy-load database 'C:/Users/MyUser/Documents/R/win-library/3.3/rJava/R/rJava.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
Error: package or namespace load failed for ‘rJava’`

These are the details of my setup:
Windows version: 10.0.14393
Java version: jre1.8.0_131
R version: R 3.3.3
rJava Version 0.9-8

Thanks

**Comment by s-u** [comment]
This has nothing to do with rJava, you have a R version mismatch with your packages - re-install packages (including rJava) to fix. Note that often users overlook old folders so check `.libPaths()` if in doubt.
