### ISSUE TITLE
checking JNI data types... configure: error: One or more JNI types differ from the corresponding native type....

### ISSUE THREAD

**Issue by yolanda0001** [s-u/rJava#103]
### Error occurs  when I run _install.packages("rJava")_

**The error is :**
Selection: 14
trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/src/contrib/rJava_0.9-8.tar.gz'
Content type 'application/octet-stream' length 656615 bytes (641 KB)
downloaded 641 KB

* installing *source* package ‘rJava’ ...
** package ‘rJava’ successfully unpacked and MD5 sums checked
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether time.h and sys/time.h may both be included... yes
configure: checking whether gcc -std=gnu99 supports static inline...
yes
checking whether setjmp.h is POSIX.1 compatible... yes
checking whether sigsetjmp is declared... yes
checking whether siglongjmp is declared... yes
checking Java support in R... present:
interpreter : '/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/jre/bin/java'
archiver    : '/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/bin/jar'
compiler    : '/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/bin/javac'
header prep.: '/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/bin/javah'
cpp flags   : '-I/usr/lib/jvm/java/include -I/usr/lib/jvm/java/include/linux'
java libs   : '-L/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/jre/lib/amd64/server -ljvm'
checking whether Java run-time works... yes
checking whether -Xrs is supported... yes
checking whether JNI programs can be compiled... yes
**checking JNI data types... configure: error: One or more JNI types differ from the corresponding native type. You may need to use non-standard compiler flags or a different compiler in order to fix this.
ERROR: configuration failed for package ‘rJava’**
* removing ‘/opt/anaconda2/lib/R/library/rJava’

The downloaded source packages are in
	‘/tmp/RtmpJe06OZ/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("rJava") :
  installation of package ‘rJava’ had non-zero exit status

**sys:**
CentOS6.7-x86_64
**R version:**
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
**java version:**
java version "1.6.0_41"
OpenJDK Runtime Environment (IcedTea6 1.13.13) (rhel-1.13.13.1.el6_8-x86_64)
OpenJDK 64-Bit Server VM (build 23.41-b41, mixed mode)
javac **version:**
javac 1.6.0_41

**_R CMD javareconf_ is normal**
[root@master anaconda2]# R CMD javareconf
Java interpreter : /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/jre/bin/java
Java version     : 1.6.0_41
Java home path   : /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64
Java compiler    : /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/bin/javac
Java headers gen.: /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/bin/javah
Java archive tool: /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/bin/jar

trying to compile and link a JNI program
detected JNI cpp flags    : -I/usr/lib/jvm/java/include -I/usr/lib/jvm/java/include/linux
detected JNI linker flags : -L$(JAVA_HOME)/jre/lib/amd64/server -ljvm
gcc -std=gnu99 -I/opt/anaconda2/lib/R/include -DNDEBUG -I/usr/lib/jvm/java/include -I/usr/lib/jvm/java/include/linux -I/opt/anaconda2/include    -fpic  -I/opt/anaconda2/include  -c conftest.c -o conftest.o
gcc -std=gnu99 -shared -L/opt/anaconda2/lib/R/lib -L/opt/anaconda2/lib -lgfortran -o conftest.so conftest.o -L/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/jre/lib/amd64/server -ljvm -L/opt/anaconda2/lib/R/lib -lR

JAVA_HOME        : /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64
Java library path: /usr/lib/jvm/java/jre/lib/amd64/server
JNI cpp flags    : -I/usr/lib/jvm/java/include -I/usr/lib/jvm/java/include/linux
JNI linker flags : -L$(JAVA_HOME)/jre/lib/amd64/server -ljvm
Updating Java configuration in /opt/anaconda2/lib/R
Done.

I have change the version of java with java-1.7.0-openjdk,jdk-7u80-linux-x64,jdk-8u131-linux-x64.But it doesn't work.

**Comment by s-u** [comment]
Check `config.log` to see what's failing.
