### ISSUE TITLE
Making rJava compatible with JDK 9?

### ISSUE THREAD

**Issue by wudustan** [s-u/rJava#104]
With the 1 + 3 back shift from JDK 8 onwards, use of a source older than 1.6 is no longer supported by JDK 9. Do you have any plans to make 1.5 / 1.6 supported?

**Comment by s-u** [comment]
It is still supported, the source only require 1.4 if I recall, so any version of Java 1.4 or higher is ok.

**Comment by wudustan** [comment]
This is coming on the back of an error I experienced a number of times yesterday trying to install rJava:

warning: [options] bootstrap class path not set in conjunction with -source 1.4
error: Source option 1.4 is no longer supported. Use 1.6 or later.
error: Target option 1.4 is no longer supported. Use 1.6 or later.
Makefile.all:44: recipe for target 'org/rosuda/JRI/Rengine.class' failed
make[2]: Leaving directory '/tmp/Rtmpbc3Prv/R.INSTALL5da357e036f3/rJava/jri/src'
make[2]: *** [org/rosuda/JRI/Rengine.class] Error 2
Makefile.all:21: recipe for target 'src/JRI.jar' failed
make[1]: Leaving directory '/tmp/Rtmpbc3Prv/R.INSTALL5da357e036f3/rJava/jri'
make[1]: *** [src/JRI.jar] Error 2
Makevars:14: recipe for target 'jri' failed
make: *** [jri] Error 2
ERROR: compilation failed for package ‘rJava’
* removing ‘/home/yuri/R/x86_64-pc-linux-gnu-library/3.4/rJava

**Comment by s-u** [comment]
You can set it to any higher versions as needed if you supported by your JDK - it merely ensures that the result is usable by older JRE.

**Comment by academikuser** [comment]
> require(xlsx)
Loading required package: xlsx
Loading required package: rJava
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Volumes/Bmac/Rlibs/rJava/libs/rJava.so':
  dlopen(/Volumes/Bmac/Rlibs/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Volumes/Bmac/Rlibs/rJava/libs/rJava.so
  Reason: image not found
Failed with error:  ‘package ‘rJava’ could not be loaded’

**Comment by s-u** [comment]
How is this related to this issue? Your R is not configured with Java support (see the error: JVM not found).

**Comment by wudustan** [comment]
Yep, apologies about this. Java is a black box of magic to me. OK to close issue.

**Comment by hugeme** [comment]
Hello, I have the same issue using JDK 9:

warning: [options] bootstrap class path not set in conjunction with -source 1.4
error: Source option 1.4 is no longer supported. Use 1.6 or later.
error: Target option 1.4 is no longer supported. Use 1.6 or later.
make[2]: *** [org/rosuda/JRI/Rengine.class] Error 2
make[1]: *** [src/JRI.jar] Error 2
make: *** [jri] Error 2
ERROR: compilation failed for package ‘rJava’
* removing ‘/usr/local/lib/R/3.4/site-library/rJava’
* restoring previous ‘/usr/local/lib/R/3.4/site-library/rJava’

Is there a workaround somehow? Thx

**Comment by luisspuerto** [comment]
The same here!

**Comment by luisspuerto** [comment]
@hugeme the only workaround I've found right now is uninstall Java9 and reinstall Java8. 
You can see a little bit more in this thread: https://github.com/s-u/rJava/issues/119

Since I've have installed Java with brew cask just did the same as in the thread. 

```
brew cask uninstall java
brew cask install java8
R CMD javareconf
```

I don't know if you need to have installed cask versions. 

`brew tap caskroom/versions`

More info here: http://davidcai.github.io/blog/posts/install-multiple-jdk-on-mac/ 

I tried to have more than one version of Java as explained there and it didn't workout.

**Comment by luisspuerto** [comment]
With the rJava update this issue at least for me is fixed

**Comment by s-u** [comment]
Thanks!
