### ISSUE TITLE
strange error while i used library method

### ISSUE THREAD

**Issue by dreamlate00** [s-u/rJava#105]
the error is : 
`
Error in library("bnlearn") : ²»´æÔڽÐ'bnlearn'Õâ¸öÃû×ֵError: object 'learning.test' not found
`
my code is following :
`
Rengine engine = new Rengine(null, false,new TextConsole());
        System.out.println("Rengine created, waiting for R");
        if (!engine.waitForR()) {
            System.out.println("Cannot load R");
        }
        engine.eval("library(\"bnlearn\")");
        engine.eval("learning.test");
`
I can't understandwhat kind of error happened and how to deal with it.
I use jdk1.8, R 3.4.0 , and eclipse

**Comment by s-u** [comment]
My guess would be that you don't have the `bnlearn` package installed at system level. Either do that, or use `.libPaths()` to add any custom libraries.
