### ISSUE TITLE
signature for java Set not accepted

### ISSUE THREAD

**Issue by Mdhaker** [s-u/rJava#107]
Hello,
I have a method that returns a Set of string Set<String> what is the JNI signature of my method, I tried everything by didn't work, I change it to String[] with the signature "[Ljava/lang/String;" and still not working..

how should deal with lists in rJava ?

**Comment by s-u** [comment]
`Ljava/util/Set;` is the signature of `java.util.Set`. If in doubt, post the declaration of the method.
