### ISSUE TITLE
Rjava Installation Issue

### ISSUE THREAD

**Issue by lamtibboualaa** [s-u/rJava#109]
Hi,

I tried o install Rjava using this command : 
`install.packages('rJava')`

I get the following error : 
`package ‘rJava’ is not available (for R version 3.3.2)`

Which are the supported R versions for Rjava ?

Thanks.

**Comment by s-u** [comment]
R 2.5.0 or higher.

Please read all the messages you get - likely your CRAN mirror isn't working - make sure you have connectivity and that you can access CRAN.
