### ISSUE TITLE
R function not running in its entirety 

### ISSUE THREAD

**Issue by markFriel** [s-u/rJava#118]
We are currently using the rJava interface to use R code in Java. We have a function in R whose parameter is a pdf file. Example: Function(C:/pathToFile.pdf) When run in R it is executed in its entirety successfully.

The function converts the pdf file to a jpeg file and this is done successfully in JRI, however the next step in the function is to use the load.image() function in the imager package and this doesn't execute successfully. We believe the problem comes from Java trying to call the load.image() function.

What might be the reason for this and is there any solutions/workarounds?

**Comment by s-u** [comment]
The issue will be with your code which you don't show so we can't comment.
