### ISSUE TITLE
Windows: rJava installation based on registry entries fails when using Oracle Java 9 

### ISSUE THREAD

**Issue by eibe** [s-u/rJava#120]
Without setting JAVA_HOME, rJava installation on Windows currently fails when using Java 9. The problem is that the names of the registry keys have changed in Java 9, see

  https://bugs.openjdk.java.net/browse/JDK-8187906

The source coded of rJava's findjava.c checks for

   javakey="Software\\JavaSoft\\Java Development Kit"; 

which no longer works.

We have a GUI application that uses rJava. Java 9 is becoming important for GUI applications because more and more users have HDPI displays. Java 8 on Windows does not support those and renders microscopic user interfaces that are essentially unusable.

**Comment by s-u** [comment]
I have updated rJava to first look in JRE/JDK keys. Can you, please, confirm that it addresses the issue?

**Comment by eibe** [comment]
Yes, it looks like it's working now. However, I had to set JAVA_HOME to compile the package because the findjava.c code is still looking for the old registry keys. Perhaps that code should be updated as well?

**Comment by eibe** [comment]
Also, the same bits of code occur in your JavaGD package:

http://svn.rforge.net/JavaGD/trunk/R/windows/FirstLib.R
http://svn.rforge.net/JavaGD/trunk/src/jvm-w32/findjava.c

We use that package as well and it currently falls over as well if JAVA_HOME is not set.

Sorry, couldn't find a better forum to post this.

**Comment by s-u** [comment]
Ok, got it - so the run-time works, but compilation doesn't. I'll address that for the next release.

As for JavaGD, fair point, I'll move it to GitHub as well

**Comment by eibe** [comment]
Sorry to bother you again with this, but the Windows registry issue still exists in JavaGD. I have just tried Java 11 and had to set JAVA_HOME to make JavaGD work. It doesn't look there has been a new release of JavaGD where this has been fixed?

rJava works well without setting JAVA_HOME. Thanks for fixing this issue in rJava.

**Comment by s-u** [comment]
Thanks, should now fixed by 4200e0
