### ISSUE TITLE
rJava does not load on OSX El Captain and R.3.4.2

### ISSUE THREAD

**Issue by hmpioner** [s-u/rJava#122]
To all,

I'm not being able to run rJava in MAC. I looked over the net all solutions that people implemented to reconcile the different versions of Java and make rJava work on MAC, but I'm getting a different error message:
> library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: no suitable image found.  Did find:
	/Users/heleno/lib/libjvm.dylib: stat() failed with errno=20

Can someone help with this?

**Comment by s-u** [comment]
Please make sure you have configured R with Java support via `R CMD javareconf` - please consult the R documentation.
