### ISSUE TITLE
rJava odd compile warnings

### ISSUE THREAD

**Issue by pgensler** [s-u/rJava#123]
Recently I was installing some packages into an R container, and rJava was a depedency, but some of these warnings seem a bit puzzling (using the gcc compiler):

```
gcc -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o rJava.so Rglue.o arrayc.o callJNI.o callback.o fields.o init.o jri_glue.o loader.o otables.o rJava.o tools.o -L/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server -ljvm -L/usr/local/lib/R/lib -lR
(cd ../jri && make)
make[1]: Entering directory '/tmp/RtmpN39w9P/R.INSTALL3db86c303c75/rJava/jri'
make -C src JRI.jar
make[2]: Entering directory '/tmp/RtmpN39w9P/R.INSTALL3db86c303c75/rJava/jri/src'
/usr/bin/javac -target 1.6 -source 1.6 -d . ../RConsoleOutputStream.java ../RFactor.java ../REXP.java ../Rengine.java ../RList.java ../Mutex.java ../package-info.java ../RMainLoopCallbacks.java ../RVector.java ../RBool.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
```

and

```
gcc -c -o rjava.o rjava.c -g -Iinclude  -DRIF_HAS_CSTACK -DRIF_HAS_RSIGHAND -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/lib/jvm/java-8-openjdk-amd64/jre/../include -I/usr/lib/jvm/java-8-openjdk-amd64/jre/../include/linux  -fpic -I/usr/lib/jvm/java-8-openjdk-amd64/jre/../include -I/usr/lib/jvm/java-8-openjdk-amd64/jre/../include/linux
rjava.c: In function ‘RJava_request_lock’:
rjava.c:22:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write(ipcout, buf, sizeof(ptrlong));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rjava.c: In function ‘RJava_clear_lock’:
rjava.c:30:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write(ipcout, buf, sizeof(ptrlong));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rjava.c: In function ‘RJava_request_callback’:
rjava.c:39:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write(ipcout, buf, sizeof(ptrlong) * 3);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rjava.c: In function ‘RJava_init_ctrl’:
rjava.c:51:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write(ipcout, buf, sizeof(ptrlong));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rjava.c:52:3: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
   read(resin, buf, sizeof(ptrlong) * 2);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -o libjri.so Rengine.o jri.o Rcallbacks.o Rinit.o globals.o rjava.o  -shared -L/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server -ljvm -Wl,--export-dynamic -fopenmp -L/usr/local/lib -L/usr/local/lib/R/lib -lR -lpcre -llzma -lbz2 -lz -lrt -ldl -lm -licuuc -licui18n
/usr/bin/javac -target 1.6 -source 1.6 -d . ../package-info.java ../RFactor.java ../REXP.java ../RList.java ../Mutex.java ../RVector.java ../RBool.java ../RConsoleOutputStream.java ../RMainLoopCallbacks.java ../Rengine.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
/usr/bin/jar fc JRI.jar org libjri.so
make[2]: Leaving directory '/tmp/RtmpN39w9P/R.INSTALL3db86c303c75/rJava/jri/src'
rm -f libjri.so
cp src/libjri.so libjri.so
/usr/bin/javac -target 1.6 -source 1.6 -classpath src/JRI.jar -d examples examples/rtest.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: examples/rtest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
/usr/bin/javac -target 1.6 -source 1.6 -classpath src/JRI.jar -d examples examples/rtest2.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: examples/rtest2.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
make[1]: Leaving directory '/tmp/RtmpN39w9P/R.INSTALL3db86c303c75/rJava/jri'
```

I think rJava may not like the settings in my Makevars file:
```
CXX = /usr/bin/ccache clang++ -Qunused-arguments -fcolor-diagnostics 
CXXFLAGS = -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION
```
Please let me know if you would like a copy of my dockerfile, as I'm not entirely sure these warnings should be going off when compiling the package. 

One other thing to note is that I also received some odd errors prior stating:
```/usr/bin/ld: cannot find -llzma  ```
 which forced me to install liblzma-dev package to work properly and

```/usr/bin/ld: cannot find -lbz2 ``` 
  which forced me to install libbz2-dev that made it work.

Is there any way to get better errors about what libraries to install as the first one,  was extremely hard to figure out? Thanks.

**Comment by ProfFancyPants** [comment]
I am having simular issues. After the release version failed to install, this is the error I got after trying to install the dev version. I had just updated my Java this morning. I am wondering how easy it will be to downgrade.

`
> devtools::install_github("s-u/rJava")
Downloading GitHub repo s-u/rJava@master
from URL https://api.github.com/repos/s-u/rJava/zipball/master
Installing rJava
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/Valued  \
  Customer/AppData/Local/Temp/RtmpgnOGhe/devtools38bc7b4a549f/s-u-rJava-e14a6aa" --library="C:/Users/Valued  \
  Customer/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'rJava' ...
Generate Windows-specific files (src/jvm-w32) ...
make: Entering directory `/cygdrive/c/Users/Valued Customer/AppData/Local/Temp/RtmpgnOGhe/devtools38bc7b4a549f/s-u-rJava-e14a6aa/src/jvm-w32'
c:/Rtools/mingw_64/bin/dlltool --as c:/Rtools/mingw_64/bin/as  --input-def jvm64.def --kill-at --dllname jvm.dll --output-lib libjvm.dll.a
c:/Rtools/mingw_64/bin/gcc  -O2 -c -o findjava.o findjava.c
c:/Rtools/mingw_64/bin/gcc  -s -o findjava.exe findjava.o
make: Leaving directory `/cygdrive/c/Users/Valued Customer/AppData/Local/Temp/RtmpgnOGhe/devtools38bc7b4a549f/s-u-rJava-e14a6aa/src/jvm-w32'
Find Java...
[: files/java/jre1.8.0_144: unknown operand
  JAVA_HOME=c:/program files/java/jre1.8.0_144
=== Building JRI ===
[: files/java/jre1.8.0_144: unknown operand
  JAVA_HOME=c:/program files/java/jre1.8.0_144
  R_HOME=C:/PROGRA~1/R/R-34~1.2
Creating Makefiles ...
Configuration done.
make -C src JRI.jar
make[1]: Entering directory `/cygdrive/c/Users/Valued Customer/AppData/Local/Temp/RtmpgnOGhe/devtools38bc7b4a549f/s-u-rJava-e14a6aa/jri/src'
c:/program files/java/jre1.8.0_144/bin/javac -target 1.6 -source 1.6 -d . ../Mutex.java ../RBool.java ../RConsoleOutputStream.java ../REXP.java ../RFactor.java ../RList.java ../RMainLoopCallbacks.java ../RVector.java ../Rengine.java ../package-info.java
make[1]: c:/program: Command not found
make[1]: *** [org/rosuda/JRI/Rengine.class] Error 127
make[1]: Leaving directory `/cygdrive/c/Users/Valued Customer/AppData/Local/Temp/RtmpgnOGhe/devtools38bc7b4a549f/s-u-rJava-e14a6aa/jri/src'
make: *** [src/JRI.jar] Error 2
**** WARNING: JRI could NOT be built
Set IGNORE=1 if you want to build rJava anyway.
Warning: running command 'sh ./configure.win' had status 1
ERROR: configuration failed for package 'rJava'
* removing 'C:/Users/Valued Customer/Documents/R/win-library/3.4/rJava'
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected! 
`

**Comment by s-u** [comment]
Peter (@pgensler), the libraries are not required by rJava, they are required by your R, rJava is just passing down the flags from R, so it really depends on your R installation.

@ProfFancyPants - please don't pollute other's issues - you are simply missing dev tools as the error tells you and it is entirely unrelated to this issue.

**Comment by pgensler** [comment]
@s-u Ok, to be honest I'm a little lost on this, so apologies if these questions are poor.

So what about these compiler warnings? I would imagine that you would want to suppress them so  if you are compiling the package like I am, you could compile without some messy warnings (like this)
```
rjava.c: In function ‘RJava_request_callback’:
rjava.c:39:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   write(ipcout, buf, sizeof(ptrlong) * 3);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Do you have any experience using Docker at all to create containers? I think rJava gets imported in on accident, and I'm not sure that the build scripts tells the correct packages that get imported or installed because of a rJava dependency. Thanks.

**Comment by s-u** [comment]
The warning is just saying that the result of `write()` is not used - which is intentional since the subsequent read will fail and carry the result for the lock. Warnings are just that - something pointing out potential unintended consequences, but if they are intended they are simply spurious. You can spend all life just finding ways to appease compiler warnings - without any actual purpose.

As for Docker, yes, but the question is what the R code needs that you're running. In can be even indirect through another R package.

**Comment by pgensler** [comment]
No I understand, it's just troublesome to view a bunch of warnings when I'm building my image, that's all.

Currently I am trying to simply set up an testing environment in a docker container.
What's odd is that my container will build, but I get some odd errors like this:
```
also installing the dependencies ‘fracdiff’, ‘lmtest’, ‘RcppArmadillo’, ‘forecast’, ‘padr’, ‘timeDate’, ‘quadprog’, ‘XLConnectJars’, ‘rJava’, ‘PerformanceAnalytics’, ‘quantmod’, ‘Quandl’, ‘timetk’, ‘timeSeries’, ‘tseries’, ‘TTR’, ‘XLConnect’
```
I am using the install2.r to install the packages, but I really hope this is not installing dependencies, which it seems like it may be. If you are willing to try a dockerfile, that would be helpful.

Is there a way to search for a package that would contain all these packages as dependencies or packages that are imported?
