### ISSUE TITLE
Installation of rJava from Github Repo fails on Windows 10 - Is the problem PATH related and is there an easy fix?

### ISSUE THREAD

**Issue by ScientificProgrammer** [s-u/rJava#125]
I tried installing rJava from both the [Github repo](https://github.com/s-u/rJava) and from [RForge](http://rforge.net/rJava/) using the following commands, respectively.

1. `devtools::install_github("s-u/rJava")`
1. `install.packages("rJava",,"http://rforge.net")`

Initially, both methods failed. Looking at the R output, I could see that the problem was because my JDK was located at *C:\\Program Files\\Java\\jdk1.8.0_131*. I have had many R packages fail to install when a key component was located in a directory where at least one of the directories in the PATH contained a space.

I fixed the PATH name problem by creating a *symlink* named *C:\\java\\*, which pointed to the JDK. As an aside, please note that in Windows 10 jargon, this construct is technically called a [directory junction](https://technet.microsoft.com/en-us/library/cc753194\(v=ws.10\).aspx).

With that problem fixed, when I tried to install rJava again from the Github repo, and the install failed again. However, this time, I started seeing the following warning frequently:

    warning: [options] bootstrap class path not set in conjunction with -source 1.6

Fortunately, this time, the RForge install method worked fine. **Is there an easy fix to the Github installer so that I don't have to use RForge?**

My system information is listed below, along with the full output the failed Github attempt and the successful RForge attempt.

| **VAR**		| **VALUE** 					|
| -------------:|:------------------------------|
|* OS* | Microsoft Windows NT 10.0.16299.0|
|*RStudio Mode*	|desktop						|
|*RStudio Version*|1.1.383						|  
|*RTools Version*| 34|
|R platform		|x86_64-w64-mingw32				|
|R arch			|x86_64                      	|
|R os				|mingw32                     	|
|R system			|x86_64, mingw32             	|
|R svn rev		|73368                       	|
|R version.string	|R version 3.4.2 (2017-09-28)	|
|R nickname		|Short Summer					|

[Output from RJava Installation-Github.txt](https://github.com/s-u/rJava/files/1485914/Output.from.RJava.Installation-Github.txt)

[Output from RJava Installation-RForge.txt](https://github.com/s-u/rJava/files/1485915/Output.from.RJava.Installation-RForge.txt)

**Comment by s-u** [comment]
Please report any issues you have with `devtools` to the developers. It is a contributed package and not part of R.

**Comment by s-u** [comment]
`rJava` is installed by creating a package tar ball via the `mkdist.sh` script. If you wanted to install from GitHub it would require`devtools` to support that convention.
