### ISSUE TITLE
rJava Error

### ISSUE THREAD

**Issue by awfrankwils** [s-u/rJava#127]
"Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64" 
"R version 3.4.3 (2017-11-30)"

I keep getting this error, tried reinstalling the package but it has not resolved the issue. Never had this issue before, not sure how to resolve.

> library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found

**Comment by cmbarton** [comment]
Same thing on the Mac version of 3.4.3 (x86_64-apple-darwin15.6.0 (64-bit))

**Comment by s-u** [comment]
You need to configure R with Java support:

```
R CMD javereconf
```

because Oracle Java location is changing frequently with updates.

Also note that RStudio is reported to not use Java settings correctly so you you may need to run it through `R CMD` to set them -- or pre-load `libjni.dylib` -- or explicitly set the path in the library.

**Comment by cmbarton** [comment]
This requires me to be on the sudo list

Michael Barton

...Sent from my iPad

**Comment by s-u** [comment]
Well, whoever installs the software has to do it. You don't need to (and should not) run it as `sudo`, but whoever installed Java and R has to do it. So ask your admin if they didn't configure R and Java correctly.

**Comment by cmbarton** [comment]
I'm doing this on the agave cluster, not my personal computer.

Michael
____________________
C. Michael Barton
Director, Center for Social Dynamics & Complexity
Professor of Anthropology, School of Human Evolution & Social Change
Head, Graduate Faculty in Complex Adaptive Systems Science
Arizona State University

voice:  480-965-6262 (SHESC), 480-965-8130/727-9746 (CSDC)
fax: 480-965-7671 (SHESC),  480-727-0709 (CSDC)
www: http://www.public.asu.edu/~cmbarton, http://csdc.asu.edu















On Mar 14, 2018, at 10:00 AM, Simon Urbanek <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, whoever installs the software has to do it. You don't need to (and should not) run it as sudo, but whoever installed Java and R has to do it. So ask your admin if they didn't configure R and Java correctly.
