### ISSUE TITLE
rJava with java 1.8.0_161 fail to load java.io.*

### ISSUE THREAD

**Issue by Camilochiang** [s-u/rJava#128]
Hei. This may be the wrong place to ask, but due that is a very specific topic I would like to ask you something.

Im running rjava linked to java 1.8.0_161 with R 3.4.3 in OS 10.13.2 (High Sierra) and I have some issues with some functions that I would like to understand

`> library(rJava)
> .jinit()
[1] 0
> .jclassPath()
[1] "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/java"
> 
> ## First we try:
> .jnew('java.lang.Object') # Works
[1] "Java-Object{java.lang.Object@61bbe9ba}"
> 
> ## Lets check the package IO
 
> .jnew('java.io.IOException') # ok...
[1] "Java-Object{java.io.IOException}"
> .jnew('java.io.PrintStream') ## Drama!
Error in .jnew("java.io.PrintStream") : 
  java.lang.NoSuchMethodError: <init>

> ## What is there...
> .jnew('java.io.Console') ## ok!
[1] "Java-Object{java.io.Console@610455d6}"
> .jnew('java.io.CharConversionException') ## ok!
[1] "Java-Object{java.io.CharConversionException}"
> .jnew('java.io.InvalidObjectException') ## drama
Error in .jnew("java.io.InvalidObjectException") : 
  java.lang.NoSuchMethodError: <init>
> .jnew('java.io.ObjectlnputValidation')
Error in .jnew("java.io.ObjectlnputValidation") : 
  java.lang.ClassNotFoundException
> .jnull('java.io.InvalidObjectException') ## Ok. 
[1] "Java-Object<null>"
`

May i know why this functions doesnt work properly ? Do i need to have a environmental variable for theses ones?  When I check JAVA_HOME in R is empy....

I Have check it before with NetBeans and there is not problem at Java level, so i guess that is a problem with my R.. 

Additionaly to this, this version of Java come with a new lib file ( libjava.jnilib) and not sure how to connect it to R. Do i need to?

Thanks in advance!

**Comment by s-u** [comment]
I would recommend reading Java documentation for the classes you're using - what's happening here is that you are trying to call non-existed constructors. For example, `java.io.PrintStream` requires you to pass the target object (file or output stream) which you didn't provide.
