### ISSUE TITLE
Autoconf subst variable `JAVA_LD` referenced in `R/zzz.R.in` does not exist in `configure.ac`

### ISSUE THREAD

**Issue by mingwandroid** [s-u/rJava#129]
Presumably this should be `JAVA_LD_PATH` instead?

```
grep -R JAVA_LD . | grep SUBST
./jri/configure.ac:AC_SUBST(JAVA_LD_PATH)
```

**Comment by s-u** [comment]
Thanks, this was a somewhat misguided attempt to provide a last-resort solution in case `jvm` cannot be found using R settings. However, as you point out, `JAVA_LD` (nor `JAVA_LD_PATH`) is detected in the top-level configure so it won't work either way. It is likely wrong to pick build-time Java anyway, so probably best solution is to remove it from `R/zzz.R.in` entirely.
