### ISSUE TITLE
Java stack work-around should be disabled when JRI is called from already initialized JVM

### ISSUE THREAD

**Issue by msannell** [s-u/rJava#130]
Consider the following Java code which starts an R engine via jri, and
then loads rJava and calls .jinit.

    import org.rosuda.JRI.RMainLoopCallbacks;
    import org.rosuda.JRI.Rengine;

    public class CallIntoR {

        public static class TextConsole implements RMainLoopCallbacks
        {
            public void rWriteConsole(Rengine re, String text, int oType) {
              System.out.print(text);
            }
            public String rChooseFile(Rengine re, int newFile) { return null; }
            public String rReadConsole(Rengine re, String prompt, int addToHistory) { return null; }
            public void rBusy(Rengine re, int which) { }
            public void rShowMessage(Rengine re, String message) { }
            public void rFlushConsole (Rengine re) { }
            public void rLoadHistory  (Rengine re, String filename) { }
            public void rSaveHistory  (Rengine re, String filename) { }
        }

        public static void main(String[] args) throws Exception {
            System.out.println("before new Rengine");
            Rengine rengine = new Rengine(
                    new String[] { "--no-save", "--no-restore", "-q"},
                    false, new TextConsole());
            if (!rengine.waitForR()) {
                throw new IllegalStateException("Unable to load R engine");
            }
            System.out.println("before print(1:10)");
            rengine.eval("print(1:10)", false);
            System.out.println("before library(rJava)");
            rengine.eval("library(rJava)", false);
            System.out.println("before .jinit()");
            rengine.eval(".jinit()", false);
            System.out.println("before print(.jcall('java/lang/Math','D','pow',2,3))");
            rengine.eval("print(.jcall('java/lang/Math','D','pow',2,3))", false);
            System.out.println("before rengine.end");
            rengine.end();
            System.out.println("done");
        }

    }

Suppose I set R_HOME and LD_LIBRARY_PATH appropriately to point to R
3.4.3 with rJava 0.9.9 installed, and run CallIntoR (with java jre
1.8.0_65).  The call to .jinit produces a segfault:

    erratic sannella% java -cp .:/home/sannella/R-3.4.3/site-library/rJava/jri/JRI.jar CallIntoR
    before new Rengine
    before print(1:10)
     [1]  1  2  3  4  5  6  7  8  9 10
    before library(rJava)
    before .jinit()
    Segmentation fault (core dumped)
    erratic sannella%

If I disable the RJAVA_JVM_STACK_WORKAROUND fix, then it works:

    erratic sannella% setenv RJAVA_JVM_STACK_WORKAROUND 0
    erratic sannella% java -cp .:/home/sannella/R-3.4.3/site-library/rJava/jri/JRI.jar CallIntoR
    before new Rengine
    before print(1:10)
     [1]  1  2  3  4  5  6  7  8  9 10
    before library(rJava)
    before .jinit()
    before print(.jcall('java/lang/Math','D','pow',2,3))
    [1] 8
    before rengine.end
    done
    erratic sannella%

If R 3.4.3 has rJava 0.9.8 installed, CallIntoR works with
RJAVA_JVM_STACK_WORKAROUND set or unset.

Is this use case (start R inside Java, and then load and use rJava)
expected?

**Comment by s-u** [comment]
Thanks, this is a very good point. The Java work-around is only needed when R is the process that embeds Java. It is not need when the process itself is already the JVM process and so this work-around shouldn't even be attempted in the case. I have to check how to detect that case automatically and disable the work-around
