### ISSUE TITLE
.jinit() crashes with Java 9 when trying to add classpath

### ISSUE THREAD

**Issue by r-suzuki** [s-u/rJava#132]
# Summary
If `.jinit()` is called when `rJava/java/boot` is not in the classpath, it leads to a crash with Java 9. A reproducible example is shown below, which gave the same result on Windows and Linux.

# Example
This problem always happens when R is called from JRI (without explicitly setting classpath). Here is a short Java example of "Java -> JRI -> rJava" chain:

```java
import org.rosuda.JRI.REXP;
import org.rosuda.JRI.Rengine;

public class JRIrJavaTest {
	public static void main(String[] args)
	{
		Rengine engine = new Rengine(new String[]{"--no-save"}, false, null);
		REXP result = engine.eval("try({rJava::.jinit(); a <- 1.234})");
		System.out.println(result);
		engine.end();
	}

}
```

When it is compiled and run using Java 8, I could successfully get the result `[REAL* (1.234)]`. Using Java 9 however, it crashes with a message like below:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.rosuda.JRI.Rengine (file:/C:/Users/<USER_NAME>/Documents/R/win-library/3.4/rJava/jri/JRI.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.rosuda.JRI.Rengine
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000000800d411, pid=5720, tid=7008
#
# JRE version: Java(TM) SE Runtime Environment (9.0+11) (build 9.0.4+11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (9.0.4+11, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x37d411]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\<USER_NAME>\workspace\JRIrJavaTest\hs_err_pid5720.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

I tried this example on Windows 7 Ultimate and CentOS 7 with R 3.4.3 and Oracle JDK 9, both leading to the same result.

On CentOS setting `RJAVA_JVM_STACK_WORKAROUND=0` was also needed (as shown in #130), and rJava was re-installed after `R CMD javareconf` following switching Java versions (using `alternatives` for configuring `java` and `javac`).

# Details
`.jinit()` tries to add `rJava/java/boot` to the classpath if it is not included yet:

```r
        if (is.jnull(rjcl)) {
            cpr <- try(.jmergeClassPath(boot.classpath), silent = TRUE)
```
It seems that `.jmergeClassPath()` crashes when calling `java.lang.System#setProperty`:

```r
        .jcall("java/lang/System", "S", "setProperty", "java.class.path", as.character(acp))
```

It may be solved if a custom class loader with `addURL` is available and `.jmergeClassPath()` uses it to add classpath, but I haven't successfully done it yet.

There is also a warning message regarding JRI (`WARNING: An illegal reflective access operation has occurred...`) which also may violate the encapsulation of Java 9.

I'm still trying to find a workaround, but anyway please let me report the problem first. I hope there will be a good solution.

**Comment by perpdgo** [comment]
Hi r-suzuki, 

It was possible to solve this problem?. I am having exactly the same problem and I am unable to find a solution.

**Comment by r-suzuki** [comment]
@perpdgo Unfortunately I coudn't. Currently I avoid this problem by adding `rJava/java/boot` to the classpath in advance.

It works, but this is just a workaround. I still hope some better solution.

**Comment by s-u** [comment]
Please make sure the segfault is not related to the stack test (which intentionally generates a segfault to find the stack boundary). I don't have JDK 9 at hand anyone (since Oracle is aggressively removing them), but both with JDK 10 and 11 the above example works just fine:

```
$ JRI=`Rscript -e 'cat(system.file("jri",package="rJava"))'`
$ echo $JRI
/usr/local/R/site-lib/rJava/jri
$ javac -cp $JRI/JRI.jar:$JRI/JRIEngine.jar JRIrJavaTest.java 
$ RJAVA_JVM_STACK_WORKAROUND=0 R CMD java -Djava.library.path=$JRI \
  -cp $JRI/JRI.jar:$JRI/JRIEngine.jar:. JRIrJavaTest
[REAL* (1.234)]
$ Rscript -e 'rJava::.jinit(); cat(rJava::.jcall("java/lang/System","S","getProperty","java.version"))'
11.0.1
```
(Tested with Ubuntu 18.04.1 LTS, Java 10.0.2 and Java 11.0.1, rJava 0.9-10)

If you still have issues, please post the exact commands you used to compile and run.

**Comment by s-u** [comment]
I just verified that the above also works in Java 9.0.4 so I suspect the issue is may be elsewhere.

**Comment by perpdgo** [comment]
Thank you r-suzuki and Simon. In my case the problem that I was loading the rJava library 
using 

private Rengine engine; 
//...
//Initialization and more code
//...
engine.eval("library(rJava)");

This code was working with Java8. 

Simon, just another question, perhaps I need to open another report. With the new version of JDK for windows (version 11) the java installer has stopped adding information to the registry. With openJDK we need to configure manually the PATH and JAVA_HOME in order to be able to load rJava and JavaGD. Is there another approach?, as I understand we are not going to be able to use Oracle JDK freely, so it is better to use openJDK.

Regards.

**Comment by s-u** [comment]
Please open another issue or add to an existing issue. I don't use Windows so I'd appreciate any feedback if people know what changes are necessary.

Do you still see a problem with the current issue here? If so, can you ad more detail about how you compile and start it? Since you're using Windows it may be more tricky as there is no `R CMD` to setup the environment correctly.

**Comment by r-suzuki** [comment]
@s-u, thank you for your feedback. I still have this problem. Here is the result with Ubuntu 18.04LTS, OpenJDK 10.0.2, R-3.4.4 and rJava 0.9-10. R was installed by apt and `sudo R CMD javareconf` was done in advance.

First, `rJava` works as always:

```
$ Rscript -e 'rJava::.jinit(); cat(rJava::.jcall("java/lang/System","S","getProperty","java.version"))'
10.0.2
```

But it does not from `JRI`:

```
$ JRI=`Rscript -e 'cat(system.file("jri",package="rJava"))'`

$ echo $JRI
/home/user/R/x86_64-pc-linux-gnu-library/3.4/rJava/jri

$ javac -cp $JRI/JRI.jar:$JRI/JRIEngine.jar JRIrJavaTest.java 

$ RJAVA_JVM_STACK_WORKAROUND=0 R CMD java -Djava.library.path=$JRI \
   -cp $JRI/JRI.jar:$JRI/JRIEngine.jar:. JRIrJavaTest
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.rosuda.JRI.Rengine (file:/home/user/R/x86_64-pc-linux-gnu-library/3.4/rJava/jri/JRI.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.rosuda.JRI.Rengine
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff4ad743ddd, pid=27743, tid=27746
#
# JRE version: OpenJDK Runtime Environment (10.0.2+13) (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
# Java VM: OpenJDK 64-Bit Server VM (10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x85cddd]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/user/Desktop/rJavaJRITest/core.27743)
#
# An error report file with more information is saved as:
# /home/user/Desktop/rJavaJRITest/hs_err_pid27743.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

**Comment by r-suzuki** [comment]
Here is some information that could be helpful, including R session info, etc. Thank you for your time.
[info.txt](https://github.com/s-u/rJava/files/2494998/info.txt)

**Comment by perpdgo** [comment]
Thanks for the help Simon, I opened the issue about jdk and windows.

Regards.
