### ISSUE TITLE
ENMeval rjava java.lang.NullPointerException

### ISSUE THREAD

**Issue by oftr** [s-u/rJava#133]
Hi, 

I would like to ask about an issue recurrently found during my analyses with rJava. When I want to run the package "ENMeval" (which interacts with "dismo" package and MaxEnt), I got stuck during long and intensive analyses.  Specifically, when jackknifing procedure is run, all analyses stopped after several minutes, with the following warning:

java.io.FileNotFoundException: C:\Users\BOTANI~1\AppData\Local\Temp\RtmpOWRZRY\file11cc2f1a4b7c\plots\species_roc.png (Denied Access)
    at java.io.RandomAccessFile.open0(Native Method)
    at java.io.RandomAccessFile.open(Unknown Source)
    at java.io.RandomAccessFile.<init>(Unknown Source)
    at javax.imageio.stream.FileImageOutputStream.<init>(Unknown Source)
    at com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(Unknown Source)
    at javax.imageio.ImageIO.createImageOutputStream(Unknown Source)
    at javax.imageio.ImageIO.write(Unknown Source)
    at density.Runner.writePlots(Runner.java:2449)
    at density.Runner.writeCumulativeIndex(Runner.java:1947)
    at density.Runner.start(Runner.java:493)
    at mebridge.fit(mebridge.java:27)

Error in rJava::.jcall(mxe, "S", "fit", c("autorun", "-e", afn, "-o",  :  java.lang.NullPointerException

The command line for this rutine was the following:

c = ENMevaluate(bis, cli, method="jackknife", bg, RMvalues = c(1,2,3), fc = c("L", "LQ"), bin.output=TRUE,clamp=TRUE, parallel=FALSE)

After testing several suggestions made by the creators of "ENMeval", with no apparent solution, it was pointed rJava as the most likely responsible for this failure (https://groups.google.com/forum/#!topic/Maxent/KiCXQi0YW0Q). To me, it looks like an error when my computer tries to save a lot of files in the temporary folder (it runs properly after a few cycles until it crashes). Yet, even allowing special permissions, maxing the memory for analyses, and checking additional issues in "dismo" and "MaxEnt", the issues persist. I use rJava in R 3.4.4 installed in a Windows 7 computer. 

Thank you in advance for any comments and solutions!!

**Comment by s-u** [comment]
It says that this is a permission problem with your file - can you elaborate why this has anything to do with rJava? This is a Java-side error so clearly in the Java code - it has nothing to do with the rJava interface... I woudl suspect that you can't load the file so the package fails to guard against that and bails out with a `null` exception in Java (NOT in rJava!).
