### ISSUE TITLE
GPL (>= 2) licensing

### ISSUE THREAD

**Issue by lukasstadler** [s-u/rJava#136]
it's great that there's an LGPL-licensed branch of rJava.
AFAICS, the master branch is GPL2 because it copies some code from R itself (Defn.h).
since this code is GPL2-or-later, rJava could also use a GPL2-or-later or GPL 2-or-3 license.
I'm not a lawyer, but IMO that would make it more compatible with GPL3-licensed packages.

**Comment by s-u** [comment]
@lukasstadler The hack is no longer needed for R 3.6.0 and higher, so I have removed the hack and the master branch is now LGPL (to be released as 1.0-1). AFAIK that makes it GPL2+ compatible among other things so should fulfill the request.

**Comment by lukasstadler** [comment]
great, that'll simplify things for us.
