### ISSUE TITLE
The contact mailing list had been decommissioned or broken.

### ISSUE THREAD

**Issue by JuhaszIstvan** [s-u/rJava#139]
README.md recommends reading the "stats-rosuda-devel" mailing list. 

The name of the mailing list, however, is not recognised by the linked server, https://mailman.rz.uni-augsburg.de/mailman/listinfo/stats-rosuda-devel throws a "No such list stats-rosuda-devel" error.

The individual words words "rosuda" stats aren't found  on the page, either. 

Please update the README.md file

**Comment by s-u** [comment]
Thanks, the Augsburg staff didn't even inform us that they decommissioned the mailing list. Sorry about that, I'll change the instructions to use GitHub or e-mail me directly.
