### ISSUE TITLE
JAVAH is incorrectly required for JDK 10+

### ISSUE THREAD

**Issue by JuhaszIstvan** [s-u/rJava#141]
Hello,

the installation of the current version of rJava  dies because the lack of JAVAH definition in the envornment variables when the java vendor is openJDK (1.8 and 11) 

Background:
Curiously, you have implemented workarounds that handle this issue:
https://github.com/s-u/rJava/commit/7558bfd61aacd03329991ced356fc452258f5807

But it still failes on opensuse/openjdk-18 and 11 :

```
interpreter : '/usr/bin/java'
archiver    : '/usr/bin/jar'
compiler    : '/usr/bin/javac'
header prep.: ''
cpp flags   : '-I/usr/lib64/jvm/java-11-openjdk-11/include'
java libs   : '-L/usr/lib64/jvm/java-11-openjdk-11/lib/server -ljvm'
configure: error: One or more Java configuration variables are not set.
Make sure R is configured with full Java support (including JDK). Run
R CMD javareconf
as root to add Java support to R.
```

I apologise for opening a separate ticket for every facet of this issue, I believe in being specific.

**Comment by mwhudson** [comment]
I think the issue is that the linked commit fails to patch the top-level configure & configure.ac

**Comment by s-u** [comment]
Thanks, 7558bfd was aimed at the most common case where system alts for `javah` are still in place but non-functional. In your case you don't even have an alt symlink at the OS level, so it's not found at all.

**Comment by JuhaszIstvan** [comment]
thank you, that awas fast  Early morning start?:)  I have reproduced this issue last night on a fresh CentOS VM with Oracle JDK. Can't wait to try the patched version, thank you!
