### ISSUE TITLE
rJava install in win7 fail

### ISSUE THREAD

**Issue by macsharma** [s-u/rJava#143]
I am using R 3.5 and Java 10.0.1
Command Used:
------------------
Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre-10.0.1;C:\\Program Files\\Java\\jre-10.0.1\\bin;C:\\Program Files\\Java\\jre-10.0.1\\bin\\server")
install.packages(pkgs = "rJava", repos="http://rforge.net", type = 'source')

Error:
------
* installing *source* package 'rJava' ...
Generate Windows-specific files (src/jvm-w32) ...
make: Entering directory '/Users/mayank/AppData/Local/Temp/RtmpQv9p7e/R.INSTALL1a2c666463bb/rJava/src/jvm-w32'
c:/Rtools/mingw_64/bin/dlltool --as c:/Rtools/mingw_64/bin/as  --input-def jvm64.def --kill-at --dllname jvm.dll --output-lib libjvm.dll.a
c:/Rtools/mingw_64/bin/gcc  -O2 -c -o findjava.o findjava.c
c:/Rtools/mingw_64/bin/gcc  -s -o findjava.exe findjava.o
make: Leaving directory '/Users/mayank/AppData/Local/Temp/RtmpQv9p7e/R.INSTALL1a2c666463bb/rJava/src/jvm-w32'
Find Java...
./configure.win: line 15: [: too many arguments
  JAVA_HOME=C:/Program Files/Java/jre-10.0.1;C:/Program Files/Java/jre-10.0.1/bin;C:/Program Files/Java/jre-10.0.1/bin/server
=== Building JRI ===
configure.win: line 21: [: too many arguments
  JAVA_HOME=C:/Program Files/Java/jre-10.0.1;C:/Program Files/Java/jre-10.0.1/bin;C:/Program Files/Java/jre-10.0.1/bin/server
  R_HOME=C:/PROGRA~1/R/R-35~1.0
Creating Makefiles ...
Configuration done.
make -C src JRI.jar
make[1]: Entering directory '/Users/mayank/AppData/Local/Temp/RtmpQv9p7e/R.INSTALL1a2c666463bb/rJava/jri/src'
C:/Program Files/Java/jre-10.0.1;C:/Program Files/Java/jre-10.0.1/bin;C:/Program Files/Java/jre-10.0.1/bin/server/bin/javac  -d . ../RList.java ../RBool.java ../RVector.java ../RMainLoopCallbacks.java ../RConsoleOutputStream.java ../Mutex.java ../Rengine.java ../REXP.java ../RFactor.java ../package-info.java
sh: C:/Program: No such file or directory
sh: C:/Program: No such file or directory
sh: C:/Program: No such file or directory
make[1]: *** [Makefile.all:41: org/rosuda/JRI/Rengine.class] Error 127
make[1]: Leaving directory '/Users/mayank/AppData/Local/Temp/RtmpQv9p7e/R.INSTALL1a2c666463bb/rJava/jri/src'
make: *** [Makefile.all:19: src/JRI.jar] Error 2
**** WARNING: JRI could NOT be built
Set IGNORE=1 if you want to build rJava anyway.
ERROR: configuration failed for package 'rJava'
* removing 'C:/Users/mayank/Documents/R/win-library/3.5/rJava'
* restoring previous 'C:/Users/mayank/Documents/R/win-library/3.5/rJava'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘rJava’ had non-zero exit status

**Comment by s-u** [comment]
User error - invalid `JAVA_HOME` setting. If in doubt, do NOT set `JAVA_HOME` and `rJava` will pick up the right setting from the registry.
