### ISSUE TITLE
Installation still fails:datatype doesn't match

### ISSUE THREAD

**Issue by JuhaszIstvan** [s-u/rJava#147]
Install still fails even with the updated package. I have looked into code, it seems that autoconfig file's  following line stops the installation: 
 
`return (sizeof(int)==sizeof(jint) && sizeof(long)==sizeof(long) && sizeof(jbyte)==sizeof(char) && sizeof(jshort)==sizeof(short) && sizeof(jfloat)==sizeof(float) && sizeof(jdouble)==sizeof(double))?0:1;`

I have never even heard of the autoconf tool before and I can only guess that the ?0:1 coerces the return value into something  but I think the main function returns nothing  which might be causing the subsequent test to fail. 

There is a typo on the second check which should be sizeof(jlong)==sizeof(long) but that wouldn't cause the issue. 

Nevertheless, I have tested the variable types with the following program(my first C program, yay! ) and they seem to check out:
```
#include <stdio.h>
#include <jni.h>
int main()
{
    // Sizeof operator is used to evaluate the size of a variable
    printf("int: %ld bytes jint: %ld bytes - %d \n",sizeof(int),sizeof(jint),sizeof(int)==sizeof(jint));
    printf("long: %ld bytes jlong: %ld bytes - %d \n",sizeof(long),sizeof(long),sizeof(jlong)==sizeof(jlong));
    printf("char: %ld bytes jbytes: %ld bytes - %d \n",sizeof(char),sizeof(jbyte),sizeof(char)==sizeof(jbyte));    
    printf("short: %ld bytes jshort: %ld bytes - %d \n",sizeof(short),sizeof(jshort),sizeof(short)==sizeof(jshort));    
    printf("float: %ld bytes jfloat: %ld bytes - %d \n",sizeof(float),sizeof(jfloat),sizeof(float)==sizeof(jfloat)); 
	printf("double: %ld bytes jdouble: %ld bytes - %d \n",sizeof(double),sizeof(jdouble),sizeof(double)==sizeof(jdouble)); 
    return 0;
 }
```
tjos itselfs correctly prints 1: 
`int main(void) {
  printf("%d\n",sizeof(int)==sizeof(jint) && sizeof(long)==sizeof(long) && sizeof(jbyte)==sizeof(char) && sizeof(jshort)==sizeof(short) && sizeof(jfloat)==sizeof(float) && sizeof(jdouble)==sizeof(double));
  return 0;
}`

The last thing I have found that could be important is that jni.h #includes jni_md.h which is in the include/linux/ folder and had to be specified to  separately, otherwise the program didnt compile. I dont understand the AC well enough to tell whether that could be an issue there or not.  

thank you!
system specs
OS:openSUSE Tumbleweed; 
jdk: java-1.8.0-openjdk-1.8.0/

log: 
> install.packages("rJava",,"http://rforge.net")
Installing package into ‘/home/$USER/R/x86_64-suse-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'http://rforge.net/src/contrib/rJava_0.9-10.tar.gz'
Content type 'application/x-gzip' length 654583 bytes (639 KB)
==================================================
downloaded 639 KB

* installing *source* package ‘rJava’ ...
[...]
checking whether JNI programs can be compiled... yes
checking JNI data types... configure: error: One or more JNI types differ from the corresponding native type. You may need to use non-standard compiler flags or a different compiler in order to fix this.
Warning in system(cmd) : error in running command
ERROR: configuration failed for package ‘rJava’
* removing ‘/home/$USER/R/x86_64-suse-linux-gnu-library/3.5/rJava’
Warning in install.packages :
  installation of package ‘rJava’ had non-zero exit status

**Comment by s-u** [comment]
Please check `config.log` - the error is actually misleading because in most cases the reason is not the run-time but rather compile-time error - very often incorrectly configure R Java support and/or missing tools.

**Comment by JuhaszIstvan** [comment]
I am sorry I know it must be a general thing but I canot find the file you are referring to. Search for "config.log" returns nothing neither for "/" nor for Home  

The command install.packages("rJava",,"http://rforge.net",keep_outputs=TRUE,clean = FALSE)  only leaves the console output and the downloaded pacakge 'configure' references the 'config.log' a lot but i can't find it.   Do you happen to know what should I search for, how could I get this path?

**Comment by JuhaszIstvan** [comment]
Thank you, it worked!  I admit, I am struggling to understand the installation sequence. I couldn't figure out why confdefs.h causes the termination if conftest fails. Maybe conftest calls confdefs.h but I can't be certain.

Nevertheless, from the log here below, it seems that "conftest" is missing  libjvm.so even though ls says the library is available at the directory path listed in the gcc command's parameters. You have patched missing libjvm in oracle JDK packages but this is an openjdk installation. 

With autoconf, install-sh  ... .way too many completely unknown layers for me to understand the execution execution sequence . I dont think I am going to be able to understand this alone in a reasonable timeframe. 

```
configure:3805: checking JNI data types
configure:3820: gcc -o conftest -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -I/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/include   conftest.c  -L/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/amd64/server -ljvm >&5
configure:3820: $? = 0
configure:3820: ./conftest
./conftest: error while loading shared libraries: libjvm.so: cannot open shared object file: No such file or directory
configure:3820: $? = 127
configure: program exited with status 127
configure: failed program was:
| /* confdefs.h */
```

```
ls /usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/amd64/server 
classes.jsa  libjsig.so  libjvm.so  Xusage.txt
```

**Comment by s-u** [comment]
Ok, two things - can you do

``ls -l /usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/amd64/server``

just to see that it's not a broken symlink and

``ldd /usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/lib/amd64/server/libjvm.so``

to see if there are any missing libraries it may rely on.
In general, it should be ok - we have tested with OpenJDK as long as your configuration is correct.

**Comment by JuhaszIstvan** [comment]
Hello,
the symlinks were ok,there were no broken dependencies. Reinstalled openjdk 1.8 - no change. installed openJDK10: execution passed that ligne. With a 2 additional packages from the SUSE repositories(libicu-devel and libbz2-devel), the package was able to install. 

We have a viable configuration, I am going to test this out in a VM for the next stable release and write up a manual installation guide  for our SDK then try to have the [SUSE hosted package's](https://build.opensuse.org/package/show/devel%3Alanguages%3AR%3Areleased/R-rJava)  dependencies updated so it starts building again.

Thank you for your support. Do you want me to keep testing this possible issue on openJDK 1.8?  
Thank you

**Comment by JuhaszIstvan** [comment]
All is good,  Changes were passed over the rep.  thank you!
