### ISSUE TITLE
Installation of rJava 0.9-10 required symlink for libomp

### ISSUE THREAD

**Issue by dwinsemius** [s-u/rJava#149]
Was unable to find any copy of the Java 9 SDK so installed the version 10. 

MacBook-Air:~ dwinsemius$ /usr/libexec/java_home -V
Matching Java Virtual Machines (5):
    10.0.1, x86_64:	"Java SE 10.0.1"	/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
    1.8.0_171, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home
    1.8.0_25, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
    1.6.0_65-b14-468, x86_64:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    1.6.0_65-b14-468, i386:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home

Was getting an error message about missing lomp during compiling from source in the R.app console. Had clang6 and Makevars file in my working directory with:
CC=/usr/local/clang6/bin/clang
CXX=/usr/local/clang6/bin/clang++
LDFLAGS =-L/usr/local/clang6/li

Found an SO question/answer regarding clang4 and Sierra and modified it to:

sudo ln -s /usr/local/clang6/lib/libomp.dylib /usr/local/lib/libomp.dylib

Although the rforge website reports a server problem (500:Internal Server Error)  at http://www.rforge.net/rJava/files/ was still able to run this successfully from R console:

install.packages("rJava",,'http://rforge.net/',type='source')

**Comment by s-u** [comment]
Sorry, this has nothing to do with rJava - iomp is needed for R (i.e., any R package)
