### ISSUE TITLE
Cannot Debug This Error: jfindClass(as.character(driverClass)[1])

### ISSUE THREAD

**Issue by zachasman** [s-u/rJava#155]
I'm trying to run this script on my R Shiny Server, but I've been tripped up on this one error for hours now. 

My script, at least the part causing the error, is as such:

    library(rJava)
    library(RJDBC)
    library(RPostgreSQL)
    
    URL <- 'https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.2/AthenaJDBC42_2.0.2.jar'
    fil <- basename(URL)
    if (!file.exists(fil)) download.file(URL, fil)
    
    drv <- JDBC(driverClass="com.amazonaws.athena.jdbc.AthenaDriver", fil, identifier.quote="'")

When I run it, the error it returns is as follows:

    Loading required package: methods
    Loading required package: DBI
    Error in .jfindClass(as.character(driverClass)[1]) : class not found
    Calls: JDBC -> is.jnull -> .jfindClass
    Execution halted

I've tried a lot of different things today, too many to count, and I always get that same error. 

The weirdest thing is, when I run it on my local RStudio, it works totally fine. It's just when I get it on the server it starts bugging out.

Can someone please help? I've been stuck on this for awhile now and any help would be greatly appreciated!

**Comment by dernst** [comment]
don't you still have to add the jar file to the classpath before calling `JDBC`?
`.jaddClassPath("AthenaJDBC42_2.0.2.jar")`

**Comment by s-u** [comment]
My wild guess would be incompatible JDK versions (using drivers for more recent JDK) - try enabling debug mode in the class loader:
```
library(rJava)
.jinit()
.jclassLoader()$setDebug(1L)
```
before using JDBC to get more verbose output.
