### ISSUE TITLE
rJava 9-10 appears to be looking for jdk-9 library

### ISSUE THREAD

**Issue by dpbrown50** [s-u/rJava#156]
Not sure if I'm interpreting the following error correctly , but it appears that rJava is looking for a jdk-9 library. Installed the binary for rJava since still unable to compile from source (due to javah problem reported in issue #153).

Any suggestions?

****************************************************
Error: package or namespace load failed for ‘RDAVIDWebService’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found
Error in eval(parse(text = "DAVIDWebService")) : 
  object 'DAVIDWebService' not found
In addition: Warning messages:
1: package ‘RDAVIDWebService’ was built under R version 3.5.0 
2: package ‘Matrix’ was built under R version 3.4.4 
3: package ‘ggplot2’ was built under R version 3.4.4 
************************************************
macOS 10.13.3
R 3.4.3
java 1.8.0_171
RDAVIDWebService 1.18.0
rJava 0.9.10

**Comment by s-u** [comment]
You have to configure your R using `javareconf` to use whichever Java you have installed. The default is Java 9, but if you have anything else you have to run
```
R CMD javareconf
```
Please also note that the R settings onyl apply to R, it doesn't apply to GUIs like RStudio.

**Comment by dpbrown50** [comment]
Thanks for your quick response.

Your suggestion apparently resolved this java issue, but now the user I'm supporting reports the following error:

Error in .Object$initialize(...) : object 'david.user' not found
Calls: enrichDAVID ... <Anonymous> -> initialize -> initialize -> <Anonymous>
In addition: Warning messages:
1: package ‘RDAVIDWebService’ was built under R version 3.5.0 
2: package ‘Matrix’ was built under R version 3.4.4 
3: package ‘ggplot2’ was built under R version 3.4.4 
Execution halted

This appears to be due to something more fundamental in his script design and configuration of the 'registration' to the DAVIDWebService.

He's since found online tools that apparently provide what he needs, so the issue is moot for him.

Thanks again for your support.
