### ISSUE TITLE
Working on android

### ISSUE THREAD

**Issue by headzik** [s-u/rJava#158]
Hi there. Is it possible to work with rJava on Android? I managed to work my code on Windows 10 eclipse project, but when I tried to run it on my Android phone I am lacking libraries. I managed to get three of the needed libraries: libjri.so, libR.so and libR.so but it keeps asking for more and I am not sure how many more it might need (100? :O). And it cannot find the libpthread.so.0 file I also provided. There has to be an easier way to do this. Any thoughts?

**Comment by s-u** [comment]
Well, you'll need a full installation of R first - that's where all the dependencies come from. I have no idea how to do that for Android - cross-compilation of R is somewhat difficult since you need to run R in order to install packages (I have done something similar many years ago for iOS).
