### ISSUE TITLE
rJava not loading java11 windows

### ISSUE THREAD

**Issue by perpdgo** [s-u/rJava#163]
Hi Simon, 

Perhaps this problem has been reported before, rJava is not loading correctly in windows 
with the latest java version (11), 

> library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dirname(this$RuntimeLib)
  error: a character vector argument expected

The java installer from Oracle do not add the directory of java binaries to the path and it does not create the environmental variable JAVA_HOME. These two things were done automatically before with Java 8. 

I have found several entries in the internet to solve the problem that applies to Oracle JDK and OpenJDK in Windows, only two steps are required to solve the issue:

1) Set the PATH
2) Create the environmental variable JAVA_HOME

the details are given in the following URL, 

https://stackoverflow.com/questions/52511778/how-to-install-openjdk-11-on-windows

Regards.

**Comment by s-u** [comment]
Thanks, I looked at JDK-11 and it still populates `HKLM\SOFTWARE\JavaSoft\JDK\{CurrentVersion}\JavaHome` so it's fine, but no other keys. We are already using a heuristic to find the right binary, but the check for `RuntimeLib` was not guarding against missing entry even though it's not necessarily needed. Please check the new version.
