### ISSUE TITLE
build of rJava fails on linux if libjvm not on LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by shadogray** [s-u/rJava#164]
conftest is compiled with -L<PATH_TO_LIBJVM>, but the execution lacks export of LD_LIBRARY_PATH
so the ac_fn_c_try_run will fail:

checking Java support in R... present:
interpreter : '/usr/java/latest/jre/bin/java'
archiver    : '/usr/java/latest/bin/jar'
compiler    : '/usr/java/latest/bin/javac'
header prep.: '/usr/java/latest/bin/javah'
cpp flags   : '-I/usr/java/latest/include -I/usr/java/latest/include/linux'
java libs   : '-L/usr/java/latest/jre/lib/amd64/server -ljvm'
checking whether Java run-time works... Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/thomas/tmp
yes
checking whether -Xrs is supported... Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/thomas/tmp
yes
checking whether -Xrs will be used... yes
checking whether JNI programs can be compiled... yes
**checking JNI data types... configure: error: One or more JNI types differ from the corresponding native type. You may need to use non-standard compiler flags or a different compiler in order to fix this.**

configure:3820: gcc -o conftest -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -I/usr/java/latest/include -I/usr/java/latest/include/linux   conftest.c
  -L/usr/java/latest/jre/lib/amd64/server -ljvm >&5
configure:3820: $? = 0
**configure:3820: ./conftest
./conftest: error while loading shared libraries: libjvm.so: cannot open shared object file: No such file or directory**

LD_LIBRARY_PATH=/usr/java/latest/jre/lib/amd64/server/ would solve the problem

Sorry, but dont know, how this should be done correctly.

**Comment by s-u** [comment]
It means you're either not calling R correctly or you don't have R configured correctly for your Java, because that's exactly what R does (see `etc/ldpaths`).
