### ISSUE TITLE
Rengine doesn't end properly if running in Tomcat

### ISSUE THREAD

**Issue by devilgate** [s-u/rJava#166]
We have a Java web application ([this one over here](https://github.com/smallAreaHealthStatisticsUnit/rapidInquiryFacility)) which embeds some R scripts by calling them via JRI.

The problem we are seeing is that, when we hot deploy the war file -- that is, copy it into Tomcat's `webapps` directory without stopping and restarting Tomcat -- the application fails when we try to use the `Rengine` class again. This is despite the fact that we call the `end` method of `Rengine` after we've finished using it the first time.

Our start looks like this:

```java
Rengine rengine = null;

try {	
	//Create an R engine with JRI
	rengine = Rengine.getMainEngine();
	if (rengine == null) {
		String[] rArgs={"--vanilla"};
		rengine = new Rengine(
			rArgs,								// Args
			false, 							// runMainLoop
			new LoggingConsole(log)); 			// RMainLoopCallbacks implementation
												// Logger log not used - uses RIFLogger
	}

	if (!rengine.waitForR()) {
		rifLogger.warning(getClass(),
						  "Cannot load the R engine (probably already loaded)");
	}
	// ... and so on
	
```

Then at the end (after an admittedly convoluted path):

```java
rifLogger.info(getClass(), "Stopping R Engine" );
rengine.end();
```

You can see [the whole thing](https://github.com/smallAreaHealthStatisticsUnit/rapidInquiryFacility/blob/master/rifServices/src/main/java/org/sahsu/rif/services/datastorage/common/StatisticsProcessing.java#L133) if you want. We know the `end` call gets executed because we see the logging output.

My thinking is that the `Rengine` thread is not being stopped completely, or that somehow there is a problem creating a new one (see below for the errors from Tomcat). I've tried various things to try and ensure the thread gets stopped, but I'm stuck. My suspicion is that the problem is at least partly in the JRI code, not least because of [`Rengine`'s weird constructor](https://github.com/s-u/rJava/blob/master/jri/Rengine.java). I mean, calling the `start` method _in_ the constructor? That seems strange and potentially problematic. Then from what I can tell, the `run` method doesn't actually do anything. It just loops around doing:

```Java
sleep(idleDelay);
if (runLoop) rniIdle();
```

It's like the thread only exists so the caller can have a reference to the engine to call the other methods on it. But if that's so, why make it a thread at all?

I'm quite prepared to be told the problem is in our code, but if so, I'm hoping for tips to fix it or work around it.

The errors we get in Tomcat look like below. Any help greatly appreciated.

```
08-Nov-2018 17:33:43.946 WARNING [Thread-7] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [rifServices] is still processing a request that has yet to finish. This is very likely to create a memory leak. You can control the time allowed for requests to finish by using the unloadDelay attribute of the standard Context implementation. Stack trace of request processing thread:[
 java.lang.Object.wait(Native Method)
 java.lang.Thread.join(Thread.java:1245)
 java.lang.Thread.join(Thread.java:1319)
 java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:106)
 java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
 java.lang.Shutdown.runHooks(Shutdown.java:123)
 java.lang.Shutdown.sequence(Shutdown.java:167)
 java.lang.Shutdown.exit(Shutdown.java:212)
 java.lang.Runtime.exit(Runtime.java:109)
 java.lang.System.exit(System.java:968)
 org.rosuda.JRI.Rengine.<clinit>(Rengine.java:27)
 org.sahsu.rif.services.datastorage.common.StatisticsProcessing.performStep(StatisticsProcessing.java:136)
 org.sahsu.rif.services.datastorage.common.RunStudyThread.smoothResults(RunStudyThread.java:248)
 org.sahsu.rif.services.datastorage.common.RunStudyThread.run(RunStudyThread.java:108)
 java.lang.Thread.run(Thread.java:745)
 org.sahsu.rif.services.datastorage.common.StudySubmissionService.submitStudy(StudySubmissionService.java:690)
 org.sahsu.rif.services.rest.WebService.submitStudy(WebService.java:1373)
 org.sahsu.rif.services.rest.StudySubmissionServiceResource.submitStudy(StudySubmissionServiceResource.java:834)
 sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.lang.reflect.Method.invoke(Method.java:483)
 com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
 com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
 com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
 com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
 com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
 com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
 com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
 com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
 com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
 com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
 com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
 com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
 com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
 com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
 com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
 javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
 org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
 org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
 org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
 org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
 org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
 org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
 org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
 org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:407)
 org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
 org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
 org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
 org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 java.lang.Thread.run(Thread.java:745)]
08-Nov-2018 17:33:43.947 SEVERE [Thread-7] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [rifServices] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@14802ebe]) and a value of type [com.sun.jersey.server.impl.application.WebApplicationContext] (value [com.sun.jersey.server.impl.application.WebApplicationContext@3d2d5081]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

**Comment by devilgate** [comment]
Thanks for that, Alberto. Good to get some kind of response here, at least. It's been very quiet.

I hadn't come across flowscope variables before. Seems to be specific to Spring, which we're not using.

I worked around our problem for now by moving all the R calls to a new service and WAR file. That way we can redeploy the main service without bringing Tomcat down. We still have to take it down if we need to redeploy the service with the R calls, but that should be very infrequent. And we've got better separation of concerns now.

Still, I'd quite like to fork this repo and make the whole thing work better. Maybe one day, when I've got some spare time.

**Comment by abh95** [comment]
Yes, I forgot to mention I was working with Spring. Glad to see you managed to solve it too anyway :)

For what I've seen there's a lack of sources from which to get information about this package's functionalities, so hopefully anyone having problems related to this event will come across this post.

**Comment by devilgate** [comment]
Hi Simon, thanks for getting back to me. 

As you'll have seen from my code above, we do create `Rengine` exactly once, and we do use `getMainEngine` to obtain the handle. The problem appears to be that the process doesn't terminate when we call `Rengine`'s `end` method.

My guess is that to fix it we'd have to make a suitable call into the native code. Or get hold of the PID and kill the process, but that wouldn't be very platform-independent.

At the very least it would be worth documenting that the `end` method doesn't do what people would expect it to do, at least in contexts like running in Tomcat.

**Comment by s-u** [comment]
Martin, `end()` is a no-op in your case since you can never re-initialize. If you want to actually quite the process simply use `System.exit(0)` or if you really want to be nice `eval("base::q('no')");`.
