### ISSUE TITLE
plotting graphs using qcc in RJava

### ISSUE THREAD

**Issue by sv-prasad** [s-u/rJava#167]
Hello,

I am trying to plot a "xbar.one" using qcc in Rjava. The following is the part of the code that I am using for this:

_re.eval("library(qcc)"); 
_re.eval("val <- (5045,4350,4350,3975,4290,4430,4485,4285,3980,3925,3645,3760,3300,3685,3463,5200)");
_re.eval("x <- qcc(val, type='xbar.one',plot=FALSE)");
_re.eval("par(col.axis='blue', font.axis=4, cex.axis=1)");
_re.eval("plot(x)");

The R plot window opens but no graph is getting plotted. 

Any help would bemuch appreciated.

**Comment by dernst** [comment]
The second line has a syntax error in R code. Should be `val <- c(5045, ...`. The plot window opens because you call `par` which creates an empty window if none exists yet. Not an rJava problem.

**Comment by sv-prasad** [comment]
Thanks for the response Dominik.
I corrected the error and then commented out the par call. I am still getting an empty window.
However the code works perfectly in the R Gui.

**Comment by dernst** [comment]
ok not sure then. maybe you need to call the R event loop so the window content gets drawn. just guessing here atm. maybe you can plot into a file?
{code}
png("file/name.png")
plot(x)
dev.off()
{code}

**Comment by sv-prasad** [comment]
Hi,
Ok. I will try that.

**Comment by sv-prasad** [comment]
> ok not sure then. maybe you need to call the R event loop so the window content gets drawn. just guessing here atm. maybe you can plot into a file?
> 
> ```
> png("file/name.png")
> plot(x)
> dev.off()
> ```

I tried outputting to a jpeg file. That is also coming out blank. No graph.

**Comment by sv-prasad** [comment]
Outputting to a file is working on changing the dimensions of picture in JavaGD function.
