### ISSUE TITLE
rJava does not work with IBM JRE

### ISSUE THREAD

**Issue by kevin-sorat** [s-u/rJava#169]
It appears that rJava looks for some dll files in the specific location in Oracle JRE, e.g. jvm.dll under jdk1.8.0_201\jre\bin\server folder.
In IBM JRE, the corresponding dll files are in a different location (e.g. under sdk\jre\bin\j9vm folder), so initialization of JVM, by rJava, fails when IBM JRE is being used. The specific error message in R console is:
```
.onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Program Files/IBM Watson Studio/resources/
application/addons/shaper/shaper-service/R_libs_windows/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  The specified module could not be found.
```

Could rJava initialization be modified to detect the version of JRE is IBM JRE and to look for the dll files in 
sdk\jre\bin\j9vm folder in this case?

**Comment by keithc-ca** [comment]
The latest release of openj9 (available at [1]) should not have this problem.

[1] https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9

**Comment by jerry1100** [comment]
I opened https://github.com/s-u/rJava/pull/170, which should resolve this issue. Unfortunately, I'm not familiar with R so I don't know how to go about testing it. @kevin-sorat do you mind testing it?

**Comment by s-u** [comment]
If you have custom, non-standard Java you can always make it work by adding the location of `libjvm.dll` to your `PATH`.

**Comment by jerry1100** [comment]
Yup, after looking through the [source code](https://github.com/s-u/rJava/blob/e7f5c41fbd0b94981845430050a75d4b747f33e0/R/windows/FirstLib.R#L33-L39), I realized it was just adding the java stuff to `PATH`, so I just added IBM's java stuff to `PATH` to begin with, and it worked.

Thanks for the confirmation.
