### ISSUE TITLE
Mac OSX Mojave install.packages("rJava",type='source',"http://rforge.net") fails

### ISSUE THREAD

**Issue by davidproksch** [s-u/rJava#172]
When running: install.packages("rJava",type='source',"http://rforge.net") on 
MacOS Mojave Version 10.14.2 with openJDK 

java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-b12)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.192-b12, mixed mode)

I get the following error:

trying URL 'https://mirrors.nics.utk.edu/cran/src/contrib/rJava_0.9-10.tar.gz'
Content type 'application/x-gzip' length 672577 bytes (656 KB)
==================================================
downloaded 656 KB

* installing *source* package ‘rJava’ ...
** package ‘rJava’ successfully unpacked and MD5 sums checked
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether time.h and sys/time.h may both be included... yes
configure: checking whether clang supports static inline...
yes
checking whether setjmp.h is POSIX.1 compatible... yes
checking whether sigsetjmp is declared... yes
checking whether siglongjmp is declared... yes
checking Java support in R... present:
interpreter : '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java'
archiver    : '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/jar'
compiler    : '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac'
header prep.: '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javah'
cpp flags   : '-I/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/../include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/../include/darwin'
java libs   : '-L/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/server -ljvm'
checking whether Java run-time works... yes
checking whether -Xrs is supported... yes
checking whether -Xrs will be used... yes
checking whether JNI programs can be compiled... yes
checking JNI data types... configure: error: One or more JNI types differ from the corresponding native type. You may need to use non-standard compiler flags or a different compiler in order to fix this.
ERROR: configuration failed for package ‘rJava’
* removing ‘/Users/me/Library/R/3.5/library/rJava’
* restoring previous ‘/Users/me/Library/R/3.5/library/rJava’

The downloaded source packages are in
	‘/private/var/folders/36/hcx3csl94mldwx5bc4b1zqp00000gp/T/RtmpkjxvX1/downloaded_packages’
Warning message:
In install.packages("rJava", type = "source", "http://rforge.net") :
  installation of package ‘rJava’ had non-zero exit status

**Comment by dernst** [comment]
Reminds me of #153, where R attempted to compile with `-fopenmp` while openmp support for clang was not installed. Can you look at the actual error message in config.log and/or check in `$R_HOME/lib/R/etc/Makeconf` if `DYLIB_LDFLAGS` contains `-fopenmp` ? If so, either install a compiler which supports openmp or remove said flag from `Makeconf`.
https://github.com/s-u/rJava/issues/153#issuecomment-453202661

**Comment by davidproksch** [comment]
I checked where R is installed, and Library/Frameworks/R.framework/Versions/3.5/Resources/etc/Makeconf has this:

DYLIB_LDFLAGS = -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -fopenmp# $(CFLAGS) $(CPICFLAGS)

there are also several other references to -fopenmp in the Makeconf file:
MAIN_LDFLAGS = -fopenmp
SHLIB_OPENMP_CFLAGS = -fopenmp
SHLIB_OPENMP_CXXFLAGS = -fopenmp
SHLIB_OPENMP_FCFLAGS = -fopenmp
SHLIB_OPENMP_FFLAGS = -fopenmp

When I remove those flags, it compiles.  

I run this little test:
> library("rJava")
> .jinit()
> .jcall("java/lang/System", "S", "getProperty", "java.runtime.version")
[1] "1.8.0_192-b12"

And it appears to work.

**Comment by s-u** [comment]
It means you have the wrong compilers - R uses OpenMP but your compiler doesn't support it. This has nothing to do with rJava.
