### ISSUE TITLE
rJava (v.0.9-10) appears to have an issue with Azul OpenJDK

### ISSUE THREAD

**Issue by tdEmpl64** [s-u/rJava#173]
I was using rJava (v.0.9-10) just fine on a machine with Oracle JRE, but I'm getting an error when attempting to install rJava on a different machine fitted, instead, with the Azul OpenJDK:
error: Failed dependencies: libjvm.so(SUNWprivate_1.1)
Is rJava incompatible with the Azul OpenJDK?
Thank you,
Alexander.

**Comment by s-u** [comment]
No idea, you may want to ask their support. You will need JNI and the above error suggests it may not be provided by that Java.

**Comment by tdEmpl64** [comment]
Apologies for reopening--I have narrowed down on the issue as follows:

I'm building rJava on a system [A] that is equipped with OpenJDK 8. The single occurrence of the JVM library across the entire system is the file libjvm.so(). Then, I download the rJava source into a local repository on system [A], and build it via

R --vanilla --slave -e '{install.packages("rJava", repos = "file://///users/home/alexander/myrepo")}'

After I build rJava on system [A], I attempt installing it on a different identical system [B]. The issue is that system [B] keeps complaining that rJava has a dependency on libjvm.so(SUNWprivate_1.1). I find this dependency irrational, because system [A] only carries libjvm.so() and has no trace of libjvm.so(SUNWprivate_1.1).

During build time, the rJava configurator acknowledges correctly my system's OpenJDK:
...
checking Java support in R... present:
interpreter : '/opt/teradata/jvm64/jdk8/jre/bin/java'
archiver    : '/opt/teradata/jvm64/jdk8/bin/jar'
compiler    : '/opt/teradata/jvm64/jdk8/bin/javac'
header prep.: '/opt/teradata/jvm64/jdk8/bin/javah'
cpp flags   : '-I/opt/teradata/jvm64/jdk8/include -I/opt/teradata/jvm64/jdk8/include/linux'
java libs   : '-L/opt/teradata/jvm64/jdk8/jre/lib/amd64/server -ljvm'
...
checking Java version... 1.8.0_192
checking Java compatibility version (integer)... 8
checking whether /opt/teradata/jvm64/jdk8/bin/javah actually works... yes
...

Alas, given that the build system [A] only carries libjvm.so(), how on earth does rJava get its dependency on libjvm.so(SUNWprivate_1.1) ?!!
The only rational explanation is that the rJava (or the R) source contains itself elements that introduce this dependency during build time. If so, then would you happen to know how could I deactivate/circumvent them and make the rJava build independent from libjvm.so(SUNWprivate_1.1), please?

On that note, I have noticed other issues that appear to be of similar nature, such as #78 ("rJava uses 1.6 instead of the current Java version") but they haven't been of help for the present problem.

Thank you,
Alexander.

**Comment by dernst** [comment]
Are you trying to build rJava with OpenJDK8 and expect those binaries to work with Azul OpenJDK8? Those two JDKs might not be ABI-compatible. Try building rJava with Azul OpenJDK8 and, if anything, post the output from that.

**Comment by tdEmpl64** [comment]
Good point, and sorry if I led to wrong assumptions. Both systems [A] and [B] are equipped with the same Azul OpenJDK8. Building, testing, and the above output therefore takes place across the same OpenJDK distribution.

Here is also a new interesting piece of information I just found about the Azul OenJDK8 through the "find-provides" utility:
   # /usr/lib/rpm/find-provides
libjvm.so
   libjvm.so()(64bit)
   libjvm.so(libjvm.so)(64bit)
   libjvm.so(SUNWprivate_1.1)(64bit)
The above illustrates that the "libjvm.so" library on the [A] and [B] systems provides not only libjvm.so(), but also libjvm.so(SUNWprivate_1.1), too!

In light of the previous discussion and findings, let me make now address the issue I'm facing with even more specific questions:
1. Is rJava knowingly linking in any way to the libjvm.so(SUNWprivate_1.1) component of "libjvm.so"?
2. If yes, is there a way I could prevent this linking during build time (thus only enabling linking to libjvm.so())?
If I can prevent rJava from linking to the libjvm.so(SUNWprivate_1.1) component while building rJava on system [A], then there will be no internal rpm dependency on it when attempting to install the pre-built rJava on system [B].

Thank you,
Alexander.
