### ISSUE TITLE
.jinit() fails in Java 12 with java.lang.NullPointerException

### ISSUE THREAD

**Issue by luispuerto** [s-u/rJava#175]
```R
library("rJava")
.jinit()
```

This is related to https://github.com/colearendt/xlsx/issues/126 
This behavior was observed also with the previous version (0.9-10) and java 12.

**Comment by s-u** [comment]
I can confirm. It took me a while to chase down, mainly because this is a chain reaction - there is an exception in the bootstrap which means the printing of the exception crashes as the `rJava` tools are not loaded yet.

But the underlying problem is puzzling to me - it looks like a bug in the JDK to me so far, so I'd stay away from JDK 12 for now.

The actual exception happens when simply trying to get the value of `java.lang.Integer.TYPE` via the reflection API which fails with:

```
Exception in thread "main" java.lang.NullPointerException
	at java.base/jdk.internal.reflect.Reflection.verifyMemberAccess(Reflection.java:130)
	at java.base/java.lang.reflect.AccessibleObject.slowVerifyAccess(AccessibleObject.java:673)
	at java.base/java.lang.reflect.AccessibleObject.verifyAccess(AccessibleObject.java:666)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:638)
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1075)
	at java.base/java.lang.reflect.Field.get(Field.java:416)
```
AFAICT this is an internal error in the JDK as none of the objects involved are `null`.

To be precise:
```
> ic <- .jcall("java/lang/Class","Ljava/lang/Class;","forName","java.lang.Integer")
> ic
[1] "Java-Object{class java.lang.Integer}"
> f<-.jcall(ic,"Ljava/lang/reflect/Field;","getField", "TYPE")
> f
[1] "Java-Object{public static final java.lang.Class java.lang.Integer.TYPE}"
> .jcall(f, "Ljava/lang/Object;", "get", .jcast(ic, "java/lang/Object"))
[java.lang.NullPointerException]
```

**Comment by s-u** [comment]
Fortunately, the JDK-12 sources are available, so with some digging we see this happens in 
```
    public Object get(Object obj)
        throws IllegalArgumentException, IllegalAccessException
    {
        if (!override) {
            Class<?> caller = Reflection.getCallerClass();
            checkAccess(caller, obj);
```
and since we know `obj` is not `null` (and `checkAccess ` is really just pass-through) it looks like `Reflection.getCallerClass()` returning `null` -- and that is an internal native JDK function.

**Comment by s-u** [comment]
For Oracle: minimal JNI example to reproduce:

```
#include <jni.h>

int main()
{
       JavaVM *jvm;
       JNIEnv *env;
       JavaVMInitArgs vm_args;
       JavaVMOption options[1];
       jint rc;

       options[0].optionString = "-Djava.class.path=.";
       vm_args.version = JNI_VERSION_1_2;
       vm_args.nOptions = 1;
       vm_args.options = options;
       if ((rc = JNI_CreateJavaVM(&jvm, (void**)&env, &vm_args)) != JNI_OK)
           return 1;

       jclass javaClassClass = (*env)->FindClass(env, "java/lang/Class");
       jmethodID mid_forName = (*env)->GetStaticMethodID(env, javaClassClass, "forName", "(Ljava/lang/String;)Ljava/lang/Class;");
       jobject ic = (*env)->CallStaticObjectMethod(env, javaClassClass, mid_forName, (*env)->NewStringUTF(env, "java.lang.Integer"));
       /* > f<-.jcall(ic,"Ljava/lang/reflect/Field;","getField", "TYPE") */
       jmethodID mid_getField = (*env)->GetMethodID(env, javaClassClass, "getField", "(Ljava/lang/String;)Ljava/lang/reflect/Field;");
       jobject f = (*env)->CallObjectMethod(env, ic, mid_getField, (*env)->NewStringUTF(env, "TYPE"));
       /* .jcall(f, "Ljava/lang/Object;", "get", .jcast(ic, "java/lang/Object")) */
       jmethodID mid_get = (*env)->GetMethodID(env, (*env)->GetObjectClass(env, f), "get", "(Ljava/lang/Object;)Ljava/lang/Object;");
       jobject v = (*env)->CallObjectMethod(env, f, mid_get, ic);
       (*env)->ExceptionDescribe(env);
       (*jvm)->DestroyJavaVM(jvm);
       return 0;
}
```

**Comment by luispuerto** [comment]
Thanks a lot @s-u !! We'll stick to Java 11 for a while then. 

Do you know if this has been reported to java??

**Comment by s-u** [comment]
I'm in contact with Oracle, but I have not filed an official bug report.

**Comment by s-u** [comment]
According to Oracle this is a regression form https://bugs.openjdk.java.net/browse/JDK-8206240 and their team is working on it (thanks, Mark for prompt help!).

**Comment by mlchung** [comment]
Please see https://bugs.openjdk.java.net/browse/JDK-8221530 and the proposed fix.

**Comment by MichaelChirico** [comment]
Is there a Java 12 release that fixes this yet?

**Comment by s-u** [comment]
I don't think Oracle plans to address this in Java 12, the aim was to fix it in Java 13. Also I have put a work-around in the latest rJava so it doesn't crash in the bootstrap, but it can still crash in user code if it happens to use the buggy Java code path.

**Comment by strategist922** [comment]
Will JDK 13 solve this issue?

**Comment by luispuerto** [comment]
@strategist922 I guess it solves it, but it creates others 😛

**Comment by luispuerto** [comment]
this issue is not worth taking care of since we just got a new version of java. goto: #206
