### ISSUE TITLE
'rJava.rdb' is corrupt (R version 3.5.2, rJava_0.9-11, MacOS 10.14.4)

### ISSUE THREAD

**Issue by rosalieb** [s-u/rJava#179]
When trying to load xlsx package, I get the error message:
lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/R/rJava.rdb' is corrupt

I've tried downloading rJava from different sources (.tar, CRAN), but it won't work.
Any idea of where it could come from? Thanks a lot!

**Comment by s-u** [comment]
It typically means you have a version mismatch between R and the package.
