### ISSUE TITLE
While doing library("xlsx") I am getting an error

### ISSUE THREAD

**Issue by vyerramsetti** [s-u/rJava#186]
While doing library("xlsx") *& require(xlsx) I am getting  below the error.could you please help me out 

 library("xlsx")
Error: package or namespace load failed for ‘xlsx’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/syerramsetti/Documents/R/win-library/3.6/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  The specified module could not be found.

**Comment by s-u** [comment]
You have to install Java.
