### ISSUE TITLE
Error in shiny-server but not when running shiny app directly

### ISSUE THREAD

**Issue by reisner** [s-u/rJava#187]
Hi there, my shiny app works fine when I login as the `shiny` user and run the app directly, but when I used `shiny-server`, the app starts to load and then fails. Checking the logs reveals:

```
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/usr/local/lib/R/site-library/rJava/libs/rJava.so':
  libjvm.so: cannot open shared object file: No such file or directory
Warning: Error in : package ‘rJava’ could not be loaded
  56: stop
  55: .getRequiredPackages2
  54: library
Error : package ‘rJava’ could not be loaded
```

**Comment by s-u** [comment]
Likely `shiny-server` doesn't correctly setup the R environment. If is doubt, use `R CMD ` to start it.

**Comment by reisner** [comment]
I tried `sudo R CMD systemctl restart shiny-server`


I still get:
```

Warning: Error in : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/usr/local/lib/R/site-library/rJava/libs/rJava.so':
  libjvm.so: cannot open shared object file: No such file or directory
  68: <Anonymous>
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/usr/local/lib/R/site-library/rJava/libs/rJava.so':
  libjvm.so: cannot open shared object file: No such file or directory
```

**Comment by reisner** [comment]
In the error it is looking for `/usr/local/lib/R/site-library/rJava/libs/rJava.so`, but the file is actually located at `/usr/local/lib/R/site-library/rJava/libs/rJava.so` ... any ideas what could be causing this?

**Comment by s-u** [comment]
Please ask RStudio for support of their product - you are missing the R Java configuration in your setup (`R` makes sure that `libjvm.so` is on `LD_LIBRARY_PATH` but in your setup it's not)

**Comment by reisner** [comment]
@s-u OK I'll follow up with them again (they are ignoring my issue). In the meantime you've pointed me to a solution -- shinyserver was looking at `/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server` but my installation was in `/usr/lib/jvm/default-java/jre/lib/amd64/server/` 

I just created a softlink for now, and things work. Thanks for your help! :)
