### ISSUE TITLE
Error when install rJava in centos

### ISSUE THREAD

**Issue by dawncx** [s-u/rJava#19]
When I install rJava using install.packages("rJava") in R, there is always an Error:
One or more JNI types differ from the corresponding native type. You may need to use non-standard compiler flags or a different compiler in order to fix this.
I tried lots of ways I can find, but all didn't work, I feel appreciated if you could help me or give me some advice!

My R version is: R version 3.0.3 (2014-03-06) -- "Warm Puppy"
My jdk version is: java version "1.6.0_37" Java(TM) SE Runtime Environment (build 1.6.0_37-b06)

rJava to be installed version is: rJava_0.9-6

R CMD javareconf:

Java interpreter : /opt/jdk1.6.0_37/jre/bin/java
Java version     : 1.6.0_37
Java home path   : /opt/jdk1.6.0_37/jre
Java compiler    : /opt/jdk1.6.0_37/jre/../bin/javac
Java headers gen.: /opt/jdk1.6.0_37/jre/../bin/javah
Java archive tool: /opt/jdk1.6.0_37/jre/../bin/jar

trying to compile and link a JNI progam 
detected JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/linux
detected JNI linker flags : -L$(JAVA_HOME)/lib/i386/server -ljvm
gcc -std=gnu99 -I/opt/R/lib/R/include -DNDEBUG -I/opt/jdk1.6.0_37/jre/../include -I/opt/jdk1.6.0_37/jre/../include/linux -I/usr/local/include    -fpic  -g -O2  -c conftest.c -o conftest.o
gcc -std=gnu99 -shared -L/usr/local/lib -o conftest.so conftest.o -L/opt/jdk1.6.0_37/jre/lib/i386/server -ljvm -L/opt/R/lib/R/lib -lR

JAVA_HOME        : /opt/jdk1.6.0_37/jre
Java library path: $(JAVA_HOME)/lib/i386/server
JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/linux
JNI linker flags : -L$(JAVA_HOME)/lib/i386/server -ljvm
Updating Java configuration in /opt/R/lib/R
Done.

**Comment by pkumarSinghal** [comment]
What is the location of the config.log file?
Thanks,
Piyush

**Comment by s-u** [comment]
It is it the `rJava` directory - the easiest is to use `R CMD INSTALL rJava` after unpacking the tar ball, alternatively you can also use `--no-clean-on-error` option.
