### ISSUE TITLE
r0.9-11 mac10.13.6  jdk 1.8.0 failed to use rJava

### ISSUE THREAD

**Issue by topxxuki** [s-u/rJava#194]
错误: package or namespace load failed for ‘rJava’:
 loadNamespace()里算'rJava'时.onLoad失败了，详细内容：
  调用: dyn.load(file, DLLpath = DLLpath, ...)
  错误: 无法载入共享目标对象‘@path/Library/R/3.5/library/rJava/libs/rJava.so’：:
  dlopen(/@path/Library/R/3.5/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: @path/Library/R/3.5/library/rJava/libs/rJava.so
  Reason: image not found

already set java_home
> Sys.getenv("DYLD_FALLBACK_LIBRARY_PATH")
[1] "/Library/Frameworks/R.framework/Resources/lib:/Users/xiongxue/lib:/usr/local/lib:/usr/lib:::/lib:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/"
> Sys.getenv("DYLD_LIBRARY_PATH")
[1] "/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk.bak/Contents/Home/jre/lib/server"

Java interpreter : /usr/bin/java
Java version     : 1.8.0_181
Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar

why it still links to jdk1.11???

**Comment by mrchypark** [comment]
same here

**Comment by s-u** [comment]
Unless you recompile rJava will be linked to whatever Java was used at compile time. But that is only a fallback - the R settings are what matters first. The main issue is that your settings are incorrect - please follow the documentation and let R determine the settings as you're likely to get it wrong. Do NOT set `JAVA_HOME` nor any other environment variables by hand - the ones you are showing above are plain wrong as you can see (compare the paths from` javareconf`).
