### ISSUE TITLE
Error installing rJava package

### ISSUE THREAD

**Issue by berniescholz** [s-u/rJava#195]
When I try to install the rJava package within R:

> install.packages("rJava")

it downloads and starts building the package. But when it gets to the following step:

gcc -std=gnu99 -shared -L/u1/R-3.6.1/lib64/R/lib -L/u1/zlib/zlib-1.2.8/lib -L/u1/bzip/bzip2-1.0.6/lib -L/u1/xz/xz-5.2.2/lib -L/u1/pcre/pcre-8.35/lib -L/u1/libcurl/curl-7.47.1/lib -L/u1/readline/readline-master/lib -lcurl -fPIC -o rJava.so Rglue.o arrayc.o callJNI.o callback.o fields.o init.o jri_glue.o loader.o otables.o rJava.o tools.o -L/usr/lib/jvm/jdk1.6.0_131/jre/lib/amd64/server -ljvm -L/u1/R-3.6.1/lib64/R/lib -lR

I get the following error:

/usr/bin/ld: /u1/R-3.6.1/lib64/R/lib/libR.a(attrib.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/u1/R-3.6.1/lib64/R/lib/libR.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make: *** [rJava.so] Error 1
ERROR: compilation failed for package ârJavaâ
* removing â/u1/R-3.6.1/lib64/R/library/rJavaâ

I am using R version 3.61 on Oracle Linux Server version 6.9. The "uname -r" command returns:

2.6.32-696.10.3.el6.x86_64

I had downloaded and built the R executable from the source code.

**Comment by dernst** [comment]
Make sure your R supports shared libraries (`--enable-shared` afair) and if necessary rebuild R with `-fPIC` then try building rJava again.

**Comment by berniescholz** [comment]
Thanks Dominik.
Is the option "--enabled-shared"? I thought it was "--enable-R-shlib". Or do these both do the same?

**Comment by dernst** [comment]
You're right, `--enable-R-shlib` is probably what you want (the other just be enabled by default).

**Comment by berniescholz** [comment]
Thanks Dominik, that worked. I rebuilt R with that "--enable-R-shlib" option (after also rebuilding all the library dependencies like zlib, bzip, xz, pcre, curl . Now I am able to install rJava from within R without error.
