### ISSUE TITLE
Error: package or namespace load failed for ‘rJava’:

### ISSUE THREAD

**Issue by elcega** [s-u/rJava#197]
> library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/ecg1g15/Library/R/3.5/library/rJava/libs/rJava.so':
  dlopen(/Users/ecg1g15/Library/R/3.5/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Users/ecg1g15/Library/R/3.5/library/rJava/libs/rJava.so
  Reason: image not found

Seems like someone already have the same issue: https://github.com/s-u/rJava/issues/49

Is there anyway o check or move java between folders to make sure R recognises the installed java?

Thanks

**Comment by s-u** [comment]
Yes, you have to configure R with Java support - see R docuemntation, most commonly you need to run

    R CMD javareconf
