### ISSUE TITLE
Cannot install rJava on Ubuntu 16.04

### ISSUE THREAD

**Issue by GanjinZero** [s-u/rJava#200]
When install rJava by
```
install.packages('rJava')
```
It shows:
...
checking whether Java run-time works... yes
checking whether -Xrs is supported... yes
checking whether -Xrs will be used... yes
checking whether JNI programs can be compiled... configure: error: Cannot compile a simple JNI program. See config.log for details.

I have tried 
```
R CMD javareconf
```
It shows:
*** JAVA_HOME is not a valid path, ignoring
Java interpreter : /usr/bin/java
Java version     : 1.8.0_03-Ubuntu
Java home path   : /usr/lib/jvm/java-8-openjdk-amd64/jre
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar

trying to compile and link a JNI program 
detected JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/linux
detected JNI linker flags : -L$(JAVA_HOME)/lib/amd64/server -ljvm
x86_64-conda_cos6-linux-gnu-cc -I"/home/veritas/anaconda3/envs/r/lib/R/include" -DNDEBUG -I/usr/lib/jvm/java-8-openjdk-amd64/jre/../include -I/usr/lib/jvm/java-8-openjdk-amd64/jre/../include/linux  -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I/home/veritas/anaconda3/envs/r/include -Wl,-rpath-link,/home/veritas/anaconda3/envs/r/lib   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/veritas/anaconda3/envs/r/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix  -c conftest.c -o conftest.o
x86_64-conda_cos6-linux-gnu-cc -shared -L/home/veritas/anaconda3/envs/r/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,-rpath,/home/veritas/anaconda3/envs/r/lib -L/home/veritas/anaconda3/envs/r/lib -Wl,-rpath-link,/home/veritas/anaconda3/envs/r/lib -o conftest.so conftest.o -L/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server -ljvm -L/home/veritas/anaconda3/envs/r/lib/R/lib -lR

JAVA_HOME        : /usr/lib/jvm/java-8-openjdk-amd64/jre
Java library path: $(JAVA_HOME)/lib/amd64/server
JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/linux
JNI linker flags : -L$(JAVA_HOME)/lib/amd64/server -ljvm
Updating Java configuration in /home/veritas/anaconda3/envs/r/lib/R
Done.

So how can I fix my problem? This R is installed by Anaconda3.

**Comment by s-u** [comment]
See the warning above `JAVA_HOME is not a valid path, ignoring` - make sure you unset `JAVA_HOME` as it's wrong. Run `R CMD javareconf` and the install `rJava`. If you still see issues, check `config.log` in the `rJava` directory for details.
