### ISSUE TITLE
.jcall error

### ISSUE THREAD

**Issue by moonmoench** [s-u/rJava#202]
I would like to know if the integration of rJava did work for me? 
 when I type into RStudio Console: ".jinit()" it returns a "0" to me.
I am trying to run the package "iplots" which requires "rJava". Currently, I am getting the error message: 
ihist(PC[,2])
Error in .jcall(.iplots.fw, "I", "getCurVarSetLength") : 
  RcallMethod: invalid object parameter

where PC[,2] is the principal component of a matrix consisting of several numeric variables. In this case, it is a vector with a length of 159. "ihist()" is a method of the package "iplots" which produces interactive histograms.

Up until now, I had difficulties in getting "rJava" to install. Apparently, the location RStudio is looking for Java is a hard-wired path and I had to detect where RStudio is expecting Java to be and then create this path in my directory. I don't get any error message if I type "library(rJava)". Now I need to run something trivial to check if "rJava" is working. 

Because if it is working I know the problem is with another package and I can move on.

I am running the newest RStudio(Version 1.2.5001), the newest R(Version: 3.6.1), the newest macOS Catalina(Version: 10.15) and Java (Version: 1.8.0_222).

How I gracefully tried to solve the installation of the package "rJava" :) :
https://www.reddit.com/r/Rlanguage/comments/dgen10/r_version_36_and_rjava_packgage/

**Comment by dernst** [comment]
You can try something like this
```
library("rJava")
.jinit()                               
                                       
obj = .jnew("java/lang/String", "asdf")
.jcall(obj, "I", "length")             
.jcall(obj, "Z", "matches", "foo")     
.jcall(obj, "S", "toUpperCase")        
```

If that works then the error is with the package or how you use it. Using `.jcall` directly is a bit unusual imo.

**Comment by moonmoench** [comment]
.jinit() returns a "0"
.jcall length returns a 4
.jcall matches returns a FALSE
the last .jcall returns the string in all upper case letters.

So I guess it works and I have managed to at least get rJava to work. Thank you
