### ISSUE TITLE
Updates to packages depending on rJava are rejected by CRAN

### ISSUE THREAD

**Issue by kliegr** [s-u/rJava#203]
I maintain a package in CRAN depending on rJava, for which I am struggling to push the latest updates.

The problem is as follows:
My package passes tests without error or notice on all flavors but one, where the install fails due to an installation error of a dependency package (package rJava on r-devel-windows-ix86+x86_64). This installation error was already there in the past submissions of my package to CRAN, and
was not previously considered as a blocker to the package (or its updates) being accepted.

Now, the package updates are automatically rejected:

> > package qCBA_0.4.tar.gz does not pass the incoming checks automatically,
> please see the following pre-tests:
> > Windows: <
> https://win-builder.r-project.org/incoming_pretest/qCBA_0.4_20191120_105327/Windows/00check.log
>
> > Status: 1 ERROR
> > Debian: <
> https://win-builder.r-project.org/incoming_pretest/qCBA_0.4_20191120_105327/Debian/00check.log
> >
> > Status: OK

More details:
Installation of  rJava package fails on 32-bit Windows, as can be seen
here: > https://win-builder.r-project.org/incoming_pretest/qCBA_0.4_20191106_094406/Windows/00install.out
("keine zul�ssige Win32-Anwendung" error)

This problem seems to apply generally to the rJava package, not just to its use in my package:
https://cran.r-project.org/web/checks/check_results_rJava.html.
Other packages seem to have the same problem: https://stat.ethz.ch/pipermail/r-package-devel/2019q4/004539.html

The problem seems to be related to CRAN policy change.
As follows from "Reverse depends" of rJava, packages depending on rJava were successfully updated in mid-2019. The most recently updated package was apparently Crossover in May 2019.

**Comment by zachcp** [comment]
same.

**Comment by richardli** [comment]
same, I emailed CRAN and Uwe said he would look into it last week, no updates yet.

**Comment by kevinykuo** [comment]
Any of y'all gotten further with this? I haven't heard back from Uwe, and AFAICT the issue has been blocking every package that imports rJava from being updated on CRAN. Understanding this is really outside the scope of rJava but would be interested to see if there's a workaround we're missing @s-u ?

**Comment by kliegr** [comment]
No progress here.

**Comment by AQLT** [comment]
It seems solved. Yesterday I've been able to update one of my packages that depends on rJava.

**Comment by kliegr** [comment]
Also worked for me.

**Comment by s-u** [comment]
Yes, it looks like the CRAN builder machine was missing the corresponding Java.
