### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by ASK-Ngute** [s-u/rJava#204]
Error: package or namespace load failed for ‘tabulizer’:
 .onLoad failed in loadNamespace() for 'tabulizerjars', details:
  call: NULL
  error: .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'D:/R-3.6.1/library/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

**Comment by s-u** [comment]
Trying to load 64-bit rJava in 32-bit R? Please make sure you Java architecture matches your R architecture.
