### ISSUE TITLE
rJava w/ Java 13 loading error

### ISSUE THREAD

**Issue by luispuerto** [s-u/rJava#206]
Hey! 

I just update to Java 13.0.2 from Java 11 and tested if rJava is working but although is building fine, it doesn't load. 

You can see all the outputs here. 

https://gist.github.com/luispuerto/5c27a387085a0f07523a37ee5a99180a

Any idea of what is going on? 

Thanks in advance.

**Comment by s-u** [comment]
The error has nothing to do with rJava, your R library is broken, you have likely mixed R versions without changing your library. I'd suggest removing your user R library first and the re-install.
In addition you have invalid `JAVA_HOME` setting, remove it first. Fionally, you probably want to add `/Library/Java/JavaVirtualMachines/openjdk-13.0.2.jdk/Contents/Home/bin` to `PATH` first to make sure you're not using Apple Java stubs.

**Comment by luispuerto** [comment]
…. OK… 

Anyhow, thanks for your message. I just realize that there is a java 14 version now, and it seems that there is no problem with that.
