### ISSUE TITLE
Feature Request: Detect incorrect JAVA_HOME on Windows

### ISSUE THREAD

**Issue by billdenney** [s-u/rJava#209]
This is the same issue as #201 and https://stackoverflow.com/questions/27661325/unable-to-load-rjava-on-r .

I had an issue where I needed to update my JAVA_HOME environmental variable after a Java update.  The directory specified by JAVA_HOME no longer existed.  It would be helpful to let the user know if JAVA_HOME no longer exists and therefore they should set it to something else.

I don't know if this is cross-platform, but there are many issues found when searching for JAVA_HOME, so there may be a more general, cross-platform solution.

If this is of interest, I'd be happy to write a PR with a check for the directory existing in https://github.com/s-u/rJava/blob/master/R/windows/FirstLib.R.  (If a cross-platform solution is warranted, then I'm not sure how it should be implemented.)

**Comment by s-u** [comment]
@billdenney rJava *does* detect `JAVA_HOME` automatically. Users should never set it in the first place unless they are experts and want to force a special case (e.g., if you have multiple Java versions installed and you want to pick the one that is not selected in the registry).

That said, we could try to detect invalid `JAVA_HOME` and tell the user to remove it since it's broken.

**Comment by billdenney** [comment]
I definitely get it that it's more of an expert feature.  As a non-expert Java user, I have to use it because I need to have two versions of Java on my system and use one of them with R and another for other purposes.  Hopefully my PR does the trick.

**Comment by s-u** [comment]
Thanks, I have re-worked the loading yesterday (7e91fdb8f). On unix it now checks if `JAVA_HOME` is set incorrectly, issues a warning in that case and removes it to fall back to the system default. I plan to do the same for Windows - I need to check if the dynamic loading can also be applied there as that would make it easier to issue correct errors.

**Comment by billdenney** [comment]
Thanks!
