### ISSUE TITLE
Create plots in R using JRI

### ISSUE THREAD

**Issue by chrisAbyi** [s-u/rJava#21]
Please see this duplicate on Stackoverflow: http://stackoverflow.com/questions/24891319/how-to-create-plots-in-r-using-jri.

I want to create a plot in R from a Java program and store it on the harddrive. This is not about displaying an R plot in a java window. I'm using JRE as part of the rJava package. Performing calculations in R from java works just fine.

Executing this in R produces a nice plot: 
pdf(file="qqplot.pdf")
x <- rnorm(100)
qqnorm(x); qqline(x)
dev.off()

Nevertheless, executing the same from Java produces the same file, but it is empty.

Any ideas on this are highly appreciated!

**Comment by mitakas** [comment]
If you are on some version of Linux (Ubuntu for example), you could use `cairo_pdf` instead of `pdf`:
```R
cairo_pdf(file="qqplot.pdf")
x <- rnorm(100)
qqnorm(x); qqline(x)
dev.off()
```

You can check what graphics devices are supported using the `capabilities()` function in R:
```R
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE        TRUE        TRUE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE        TRUE       FALSE        TRUE        TRUE 
```

**Comment by s-u** [comment]
When using `ggplot`  you have to use `print()` since the plotting functions only create an object, they don't actually plot anything.
