### ISSUE TITLE
Error in installing rjava

### ISSUE THREAD

**Issue by msgoussi** [s-u/rJava#214]
installing *source* package 'rJava' ...
** package 'rJava' successfully unpacked and MD5 sums checked
** using staged installation
Generate Windows-specific files (src/jvm-w32) ...
make: Entering directory '/Users/310677/AppData/Local/Temp/RtmpqSRAtK/R.INSTALL2ec469257168/rJava/src/jvm-w32'
C:/Rtools/mingw_64/bin/dlltool --as C:/Rtools/mingw_64/bin/as  --input-def jvm64.def --kill-at --dllname jvm.dll --output-lib libjvm.dll.a
C:/Rtools/mingw_64/bin/gcc  -O2 -c -o findjava.o findjava.c
C:/Rtools/mingw_64/bin/gcc  -s -o findjava.exe findjava.o
make: Leaving directory '/Users/310677/AppData/Local/Temp/RtmpqSRAtK/R.INSTALL2ec469257168/rJava/src/jvm-w32'
Find Java...
  JAVA_HOME=C:/PROGRA~1/Java/JRE18~1.0_2
=== Building JRI ===
  JAVA_HOME=C:/PROGRA~1/Java/JRE18~1.0_2
  R_HOME=D:/R/R-3.6.3
JDK has no javah.exe - using javac -h . instead
Creating Makefiles ...
Configuration done.
make -C src JRI.jar
make[1]: Entering directory '/Users/310677/AppData/Local/Temp/RtmpqSRAtK/R.INSTALL2ec469257168/rJava/jri/src'
C:/PROGRA~1/Java/JRE18~1.0_2/bin/javac -h . -d . ../RList.java ../RBool.java ../RVector.java ../RMainLoopCallbacks.java ../RConsoleOutputStream.java ../Mutex.java ../Rengine.java ../REXP.java ../RFactor.java ../package-info.java
sh: C:/PROGRA~1/Java/JRE18~1.0_2/bin/javac: No such file or directory
make[1]: *** [Makefile.all:41: org/rosuda/JRI/Rengine.class] Error 127
make[1]: Leaving directory '/Users/310677/AppData/Local/Temp/RtmpqSRAtK/R.INSTALL2ec469257168/rJava/jri/src'
make: *** [Makefile.all:19: src/JRI.jar] Error 2
**** WARNING: JRI could NOT be built
Set IGNORE=1 if you want to build rJava anyway.
ERROR: configuration failed for package 'rJava'
* removing 'D:/R/R-3.6.3/library/rJava'
Warning in install.packages :
  installation of package ‘rJava’ had non-zero exit statu

**Comment by s-u** [comment]
@msgoussi you need JDK to install rJava, but you only have JRE. Note that rJava is available from CRAN, so you should simply use the CRAN version - you only need JRE at run-time. If you really want to compile it yourself, make sure you install full JDK.

**Comment by msgoussi** [comment]
I installed JDK as you mentioned


* installing *source* package 'rJava' ...
** package 'rJava' successfully unpacked and MD5 sums checked
** using staged installation
Generate Windows-specific files (src/jvm-w32) ...
make: Entering directory '/Users/310677/AppData/Local/Temp/Rtmpukr0J0/R.INSTALL165440693648/rJava/src/jvm-w32'
C:/Rtools/mingw_64/bin/dlltool --as C:/Rtools/mingw_64/bin/as  --input-def jvm64.def --kill-at --dllname jvm.dll --output-lib libjvm.dll.a
C:/Rtools/mingw_64/bin/gcc  -O2 -c -o findjava.o findjava.c
C:/Rtools/mingw_64/bin/gcc  -s -o findjava.exe findjava.o
make: Leaving directory '/Users/310677/AppData/Local/Temp/Rtmpukr0J0/R.INSTALL165440693648/rJava/src/jvm-w32'
Find Java...
  JAVA_HOME=C:/PROGRA~1/Java/jdk-14
=== Building JRI ===
  JAVA_HOME=C:/PROGRA~1/Java/jdk-14
  R_HOME=D:/R/R-3.6.3
JDK has no javah.exe - using javac -h . instead
Creating Makefiles ...
Configuration done.
make -C src JRI.jar
make[1]: Entering directory '/Users/310677/AppData/Local/Temp/Rtmpukr0J0/R.INSTALL165440693648/rJava/jri/src'
C:/PROGRA~1/Java/jdk-14/bin/javac -h . -d . ../RList.java ../RBool.java ../RVector.java ../RMainLoopCallbacks.java ../RConsoleOutputStream.java ../Mutex.java ../Rengine.java ../REXP.java ../RFactor.java ../package-info.java
..\Rengine.java:120: error: invalid use of a restricted identifier 'yield'
        while (!alive && !died) yield();
                                ^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
1 error
make[1]: *** [Makefile.all:41: org/rosuda/JRI/Rengine.class] Error 1
make[1]: Leaving directory '/Users/310677/AppData/Local/Temp/Rtmpukr0J0/R.INSTALL165440693648/rJava/jri/src'
make: *** [Makefile.all:19: src/JRI.jar] Error 2
**** WARNING: JRI could NOT be built
Set IGNORE=1 if you want to build rJava anyway.
ERROR: configuration failed for package 'rJava'
* removing 'D:/R/R-3.6.3/library/rJava'
Warning in install.packages :
  installation of package ‘rJava’ had non-zero exit status

**Comment by s-u** [comment]
Please install rJava from CRAN. You're using JDK 14 which is not stable and not compatible. It may work for run-time, but not building.

**Comment by msgoussi** [comment]
Dear Mr. 
I installed JDK from java website then I installed rjava uning install.packages in R. This is what I understood from your previous reply.

**Comment by THERMOSTATS** [comment]
I have the same issue here, also directly install from CRAN, both JDK and JRE already installed. 
Seems something related to the build of JRI?

`=== Building JRI ===
  JAVA_HOME=C:/PROGRA~1/Java/JDK-14~1.1
  R_HOME=C:/PROGRA~1/R/R-36~1.0
JDK has no javah.exe - using javac -h . instead
Creating Makefiles ...
Configuration done.
make -C src JRI.jar
make[1]: Entering directory '/cygdrive/c/Users/lix/AppData/Local/Temp/1/RtmpyaSxBf/R.INSTALL3a6062e163e4/rJava/jri/src'
C:/PROGRA~1/Java/JDK-14~1.1/bin/javac -h . -d . ../RList.java ../RBool.java ../RVector.java ../RMainLoopCallbacks.java ../RConsoleOutputStream.java ../Mutex.java ../Rengine.java ../REXP.java ../RFactor.java ../package-info.java
..\Rengine.java:120: error: invalid use of a restricted identifier 'yield'
        while (!alive && !died) yield();
                                ^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
1 error
make[1]: *** [Makefile.all:41: org/rosuda/JRI/Rengine.class] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/lix/AppData/Local/Temp/1/RtmpyaSxBf/R.INSTALL3a6062e163e4/rJava/jri/src'
make: *** [Makefile.all:19: src/JRI.jar] Error 2
**** WARNING: JRI could NOT be built
Set IGNORE=1 if you want to build rJava anyway.
ERROR: configuration failed for package 'rJava'
* removing 'C:/Users/lix/Documents/R/win-library/3.6/rJava'
* restoring previous 'C:/Users/lix/Documents/R/win-library/3.6/rJava'
Warning in install.packages :
  installation of package ‘rJava’ had non-zero exit status
`
