### ISSUE TITLE
v0.9-12: Failing to install on Bioconductor Devel

### ISSUE THREAD

**Issue by mjsteinbaugh** [s-u/rJava#217]
Hi @s-u ,

I'm seeing some new rJava errors pop up in my Bioconductor Devel environment, running R unstable 2020-04-02 r78137. Note that I also tried with the latest version of OpenJDK 14 and I'm seeing the same error below.

Here's how to reproduce using Docker:

```sh
docker run -it \
    bioconductor/bioconductor_docker:devel \
    /bin/bash
```

```R
install.packages("rJava")
```

Here's the relevant error log:

```
gcc -c -o rjava.o rjava.c -g -Iinclude  -DRIF_HAS_CSTACK -DRIF_HAS_RSIGHAND -g -O2 -fstack-protector-strong -Wfo
rmat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/lib/jvm/java-11-openjdk-amd64/include -I
/usr/lib/jvm/java-11-openjdk-amd64/include/linux  -fpic -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/
jvm/java-11-openjdk-amd64/include/linux
rjava.c: In function ‘RJava_request_lock’:
rjava.c:22:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-re
sult]
   write(ipcout, buf, sizeof(ptrlong));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rjava.c: In function ‘RJava_clear_lock’:
rjava.c:30:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-re
sult]
   write(ipcout, buf, sizeof(ptrlong));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rjava.c: In function ‘RJava_request_callback’:
rjava.c:39:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-re
sult]
   write(ipcout, buf, sizeof(ptrlong) * 3);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rjava.c: In function ‘RJava_init_ctrl’:
rjava.c:51:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-re
sult]
   write(ipcout, buf, sizeof(ptrlong));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rjava.c:52:3: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-res
ult]
   read(resin, buf, sizeof(ptrlong) * 2);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -o libjri.so Rengine.o jri.o Rcallbacks.o Rinit.o globals.o rjava.o  -shared -L/usr/lib/jvm/java-11-openjdk-
amd64/lib/server -ljvm -Wl,--export-dynamic -fopenmp -L/usr/local/lib -L/usr/local/lib/R/lib -lR -lpcre2-8 -llzm
a -lbz2 -lz -lrt -ldl -lm -licuuc -licui18n
/usr/bin/ld: cannot find -lpcre2-8
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile.all:35: libjri.so] Error 1
make[2]: Leaving directory '/tmp/Rtmpn5gR08/R.INSTALL1c6976ddd4/rJava/jri/src'
make[1]: *** [Makefile.all:19: src/JRI.jar] Error 2
make[1]: Leaving directory '/tmp/Rtmpn5gR08/R.INSTALL1c6976ddd4/rJava/jri'
make: *** [Makevars:14: jri] Error 2
ERROR: compilation failed for package ‘rJava’
* removing ‘/usr/local/lib/R/site-library/rJava’
```
@nturaga Have you seen this issue in the Bioconductor Docker image builds?

**Comment by mjsteinbaugh** [comment]
Figured it out, installing `libpcre2-dev` fixes this issue on Debian/Ubuntu.

**Comment by s-u** [comment]
Correct, you need all the dependencies that were used to build your R.

**Comment by s-u** [comment]
BTW: in theory `r-base-dev` should do the trick, if it doesn't then you may want to file an issue with the Debian maintainers.

**Comment by nturaga** [comment]
> Hi @s-u ,
> 
> I'm seeing some new rJava errors pop up in my Bioconductor Devel environment, running R unstable 2020-04-02 r78137. Note that I also tried with the latest version of OpenJDK 14 and I'm seeing the same error below.
> 
> Here's how to reproduce using Docker:
> 
> ```shell
> docker run -it \
>     bioconductor/bioconductor_docker:devel \
>     /bin/bash
> ```
> 
> ```r
> install.packages("rJava")
> ```
> 
> Here's the relevant error log:
> 
> ```
> gcc -c -o rjava.o rjava.c -g -Iinclude  -DRIF_HAS_CSTACK -DRIF_HAS_RSIGHAND -g -O2 -fstack-protector-strong -Wfo
> rmat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/lib/jvm/java-11-openjdk-amd64/include -I
> /usr/lib/jvm/java-11-openjdk-amd64/include/linux  -fpic -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/
> jvm/java-11-openjdk-amd64/include/linux
> rjava.c: In function ‘RJava_request_lock’:
> rjava.c:22:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-re
> sult]
>    write(ipcout, buf, sizeof(ptrlong));
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> rjava.c: In function ‘RJava_clear_lock’:
> rjava.c:30:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-re
> sult]
>    write(ipcout, buf, sizeof(ptrlong));
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> rjava.c: In function ‘RJava_request_callback’:
> rjava.c:39:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-re
> sult]
>    write(ipcout, buf, sizeof(ptrlong) * 3);
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> rjava.c: In function ‘RJava_init_ctrl’:
> rjava.c:51:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-re
> sult]
>    write(ipcout, buf, sizeof(ptrlong));
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> rjava.c:52:3: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-res
> ult]
>    read(resin, buf, sizeof(ptrlong) * 2);
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> gcc -o libjri.so Rengine.o jri.o Rcallbacks.o Rinit.o globals.o rjava.o  -shared -L/usr/lib/jvm/java-11-openjdk-
> amd64/lib/server -ljvm -Wl,--export-dynamic -fopenmp -L/usr/local/lib -L/usr/local/lib/R/lib -lR -lpcre2-8 -llzm
> a -lbz2 -lz -lrt -ldl -lm -licuuc -licui18n
> /usr/bin/ld: cannot find -lpcre2-8
> collect2: error: ld returned 1 exit status
> make[2]: *** [Makefile.all:35: libjri.so] Error 1
> make[2]: Leaving directory '/tmp/Rtmpn5gR08/R.INSTALL1c6976ddd4/rJava/jri/src'
> make[1]: *** [Makefile.all:19: src/JRI.jar] Error 2
> make[1]: Leaving directory '/tmp/Rtmpn5gR08/R.INSTALL1c6976ddd4/rJava/jri'
> make: *** [Makevars:14: jri] Error 2
> ERROR: compilation failed for package ‘rJava’
> * removing ‘/usr/local/lib/R/site-library/rJava’
> ```
> 
> @nturaga Have you seen this issue in the Bioconductor Docker image builds?

Hi @mjsteinbaugh ,

I think there is an issue in the rocker/r-ver:devel image which we inherit from. I'm going to issue a pull request to fix it to rocker. Hopefully in a few days it should be seen downstream.
