### ISSUE TITLE
R中运行Repast模型，涉及到rJava错误

### ISSUE THREAD

**Issue by 15751593981** [s-u/rJava#220]
我利用如下代码，从R中运行Repast的模型
> library(rrepast)
> install.dir<-"E:/installationModel/sy09"
> obj<-Model(modeldir = install.dir,dataset = "NewInfectedNumber",TRUE)
但是却出现如下错误
Error in rJava::.jcall(e, "V", "endAt", v) : 
  method endAt with signature (Z)V not found
请问，该错误是为什么会出现，该如何解决

**Comment by s-u** [comment]
Sorry, nothing to do with rJava.
