### ISSUE TITLE
Cache getNativeSymbolInfo('RcallMethod')?

### ISSUE THREAD

**Issue by jefferis** [s-u/rJava#221]
Dear Simon,

Many thanks for the invaluable work on this package including your recent release!

The code snippet below from `.jcall` suggests that @s-u intended to cache the information about the interface (`RcallMethod` or `RcallSyncMethod`) in the package's private `.env` environment.

https://github.com/s-u/rJava/blob/32e2fd7fa956fb317eb985443c69744b39782116/R/call.R#L92-L97

The only place that I can see `.env` getting filled in this way is here: 

https://github.com/s-u/rJava/blob/32e2fd7fa956fb317eb985443c69744b39782116/R/jfirst.R#L31-L35

and that doesn't include the interface calls. As far as I can see it's been like this since the first cache commit in 2011:

https://github.com/s-u/rJava/commit/8a56f5855c8f4b447355d1205f8b44eb5315c030#r39284843

I am using rJava for some intensive calls. The java library I am calling takes about 45 µs on my machine to process each `.jcall` but on top of that there is an overhead of about 20 µs per call associated with `getNativeSymbolInfo`. So actually cacheing the the call results would be very useful here.

**Comment by s-u** [comment]
Thanks, great catch! Indeed, everything is supposed to be cached. First, I'll fix the above and then I'll disable dynamic lookup so even if someone adds an entry point later it gets caught.

**Comment by jefferis** [comment]
Dear Simon @s-u, many thanks for addressing this (in a much more comprehensive fashion than my PR). I was just wondering if you intend to submit 0.9-13 to CRAN soon or if it will stay in development for the time being. I might try to work around this issue in my own code if it will be a while, but clearly this is one of those occasions where the best fix is to get the update from upstream. Thanks again, Greg.
