### ISSUE TITLE
StackOverflow errors on Debian and Java 11+ [Packages dependent on rJava fails CRAN check on Debian]

### ISSUE THREAD

**Issue by richardli** [s-u/rJava#224]
It seems another CRAN check issue arise with their build on Debian. I was trying to submit a package update and failed the checks with the error message below, only on the Debian (it seems this affects other packages using rJava with unit tests on CRAN too):

> package InSilicoVA_1.3.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/InSilicoVA_1.3.0_20200623_165417/Windows/00check.log>
Status: 1 NOTE
Debian: <https://win-builder.r-project.org/incoming_pretest/InSilicoVA_1.3.0_20200623_165417/Debian/00check.log>
Status: 1 ERROR, 1 NOTE

The relevant part of the error message is: 

 > test_check("InSilicoVA")
  InSilicoVA Sampler Initiated, 400 Iterations to Sample
  Error in .jcall(obj, "[D", "Fit", dimensions.j, probbase.j, probbase_order.j,  : 
    java.lang.StackOverflowError

I wonder if anyone has successfully work around the stackoverflow error?

**Comment by s-u** [comment]
Java 11 and higher seem to have very small stack sizes on Debian for some reason. This can be fixed by adding `-Xss2m` or similar to `java.parameters` option to increase the stack size.

**Comment by s-u** [comment]
For now I have changed `rJava` to automatically add `-Xss2m` to JVM parameters unless `-Xss` is already specified by the user.

**Comment by richardli** [comment]
Thank you!!
