### ISSUE TITLE
Strings are not re-encoded to UTF-16 correctly when run in locales other than UTF-8 and Latin1

### ISSUE THREAD

**Issue by victorsilvares** [s-u/rJava#228]
**I'm on Windows10 running R 4.0.2 and using Java jdk11.0.8, the same problem occurred while using jdk14.0.2. After installing rJava and trying to read maxent.jar, it returns this problem:**

_WARNING: Initial Java 12 release has broken JNI support and does NOT work. Use stable Java 11 (or watch for 12u if avaiable).
ERROR: Java exception occurred during rJava bootstrap - see stderr for Java stack trace.
Exception in thread "main" java.lang.NoClassDefFoundError: meversion
Caused by: java.lang.ClassNotFoundException: meversion
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
Error in rJava::.jnew("meversion") : 
  java.lang.NoClassDefFoundError: meversionrJava::.jnew("meversion")new("jobjRef", jobj = <pointer: 0x000002c7f2bd3a28>, jclass = "java/lang/NoClassDefFoundError")_

**While using jdk-1.8.0_261 the problem is a little bit differente, but still don't work**

_Error in .jinit() : Unable to create a Java class loader.
WARNING: Initial Java 12 release has broken JNI support and does NOT work. Use stable Java 11 (or watch for 12u if avaiable).
ERROR: Java exception occurred during rJava bootstrap - see stderr for Java stack trace.
Exception in thread "main" java.lang.NoClassDefFoundError: RJavaClassLoader
Caused by: java.lang.ClassNotFoundException: RJavaClassLoader
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)_

**I've tried a lot of java versions and couldnt make it work proprerly. Any help will be appreciated! Thanks in advance**

**Comment by hrbrmstr** [comment]
It would be helpful to provide a reproducible example. First, the output of:

```r
library(rJava)

.jinit()
.jcall("java/lang/System", "S", "getProperty", "java.runtime.version")
```

after each Java switch would be helpful to ensure you actually are using the version(s) you believe you are (and in the sessions you think you are). 

I would appear you're attempting to use the {[dismo](https://cran.r-project.org/web/packages/dismo/index.html)] package (that would have been helpful to include if so). If this is correct, what function are you running that causes this error?

I do not have an issue with `maxent.jar` on macOS and Java 11.0.2+9:

```r
dismo:::.getMeVersion()
## [1] "3.4.1"
```

Your error suggests you're actually using Java 12 despite believing you've switched versions (ref: https://github.com/s-u/rJava/blob/447d28e890c05975a8a32163b59adc203ed20880/src/rJava.c#L121-L125)

**Comment by victorsilvares** [comment]
Sorry about the low details of my current problem. And yes, i was trying to run maxent thru dismo package. I completely removed Java from my windows before i tried another version.
Every funcition that i call maxent, it return this error. Like


```
library(dismo)
dismo:::.getMeVersion()
#226 Error in .jinit() : Unable to create a Java class loader.
#WARNING: Initial Java 12 release has broken JNI support and does NOT work. Use stable Java 11 (or watch for 12u if avaiable).
#ERROR: Java exception occurred during rJava bootstrap - see stderr for Java stack trace.
#Exception in thread "main" [1] "3.4.1"
```


When i ask the java version:
```
> system("java -version")
#java version "1.8.0_261"
#Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
#Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
#[1] 0
```

When i try to use the maxent() funcion
```
> maxent()
#Error in .jinit() : Unable to create a Java class loader
```

And if i run it a second time, it shows more details of the problem (as i show in the first post)
```
> maxent()
#WARNING: Initial Java 12 release has broken JNI support and does NOT work. Use stable Java 11 (or watch for 12u if avaiable).
#ERROR: Java exception occurred during rJava bootstrap - see stderr for Java stack trace.
#Exception in thread "main" java.lang.NoClassDefFoundError: RJavaClassLoader
#Caused by: java.lang.ClassNotFoundException: RJavaClassLoader
#	at java.net.URLClassLoader.findClass(Unknown Source)
#	at java.lang.ClassLoader.loadClass(Unknown Source)
#	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
#	at java.lang.ClassLoader.loadClass(Unknown Source)
#This is MaxEnt version 3.4.1 
```

**Comment by hrbrmstr** [comment]
Can you run the

```r
library(rJava)

.jinit()
.jcall("java/lang/System", "S", "getProperty", "java.runtime.version")
```

Showing the system version does not necessarily == what R sees as Java.

Also, the output of `R CMD javareconf` would help.

**Comment by victorsilvares** [comment]
I found the problem actually was the path that Java used to get rJava working, some UTF-8 problem witch characters and spaces, i supose. I changed the directory where R is installing all packages and now it is working perfectly. 

I think the warning about using Java12 instead of other version is a regular warning because it's pretty much the source of all major problems.


Problem solved, Thank you very much @hrbrmstr !

**Comment by s-u** [comment]
@victorsilvares have you found out the cause? Apparently the class path did not include the `rJava/java` directory which is necessary to load the class loader, so I'm just curious what in the path made it to fail to access it. It may also have been permission issues.. I suppose the error handling could be better to detect that explicitly.

**Comment by victorsilvares** [comment]
@s-u  I think the cause of the problem was in my microsoft username, since my surname is Guimar**ã**es. I think those versions of java was struggling to find the rjava inside the Guimar**ã**es directory. After i put the library on the root (C:/), it starts to work completely well.  Talking with some university colleague i found one of them that had same issue in the past, and his username was Mourão. Looks like its a **~**  issue.

Right now i can run java perfectly. Thank you very much for the package and support, @s-u

**Comment by s-u** [comment]
Ah, I got it, thanks - rJava uses UTF-8 encoding by default and it knows how to deal with UTF-8 strings, so it works as long as the native encoding is UTF-8. However, Windows doesn't support UTF-8 as its native encoding, so the paths were passed to Java in whatever native encoding your Windows is using and thus likely garbled at the conversion. Hence the Java code couldn't find the path. That makes sense - I'll see if we have a way to make sure the strings get re-coded from the native encoding to UTF-8 as they get passed from R to Java.

**Comment by iamjingxian** [comment]
Hi, 

I am wondering if the error i'm receiving might be similar to yours, even though it seems like it's presenting as a JVM error as well? This baffles me as there shouldn't have been another JVM running in the background - this script was ran the 1st thing after I power up my system.  

"

R[write to console]: ERROR: Java exception occurred during rJava bootstrap - see stderr for Java stack trace.

Exception in thread "main" java.lang.NullPointerException
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:290)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
R[write to console]: Error: .onLoad failed in loadNamespace() for 'rcdklibs', details:
  call: .jinit(classpath = c(jars))
  error: Unable to create a Java class loader.

R[write to console]: In addition:
R[write to console]: Warning messages:

R[write to console]: 1:
R[write to console]: In .jinit(classpath = c(jars)) :
R[write to console]:

**R[write to console]:  Another VM is running already and the VM did not allow me to append paths to the class path.**

R[write to console]: 2:
R[write to console]: In .jinit(classpath = c(jars)) :
R[write to console]:

R[write to console]:  Cannot set VM parameters, because VM is running already.

**Comment by s-u** [comment]
@iamjingxian Possibly, but it's hard to tell without more details. As mentioned above, make sure you don't use non-ASCII characters in the path to your library if you are using Windows.

**Comment by s-u** [comment]
@iamjingxian I have found an issue in the UTF-16 string conversion which I have fixed so hopefully paths with non-ASCII characters should be supported. Please try latest rJava (version 1.0-7) to see if that fixes your problem.

**Comment by iamjingxian** [comment]
Hi, i think mine is a different problem. VM is *indeed* running in the background due to an improper shutdown of another script. 

I will look elsewhere to find a solution to my problem. 

thanks!
