### ISSUE TITLE
library(rJava) error

### ISSUE THREAD

**Issue by Rui-Jing** [s-u/rJava#231]
Hi,
Thanks for developing this powerful tool. But  i have a problem when i run library(rJava). 
The error is:
**Error: package or namespace load failed for ‘esATAC’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/vip1/R/x86_64-pc-linux-gnu-library/3.6/rJava/libs/rJava.so':
  libjvm.so: cannot open shared object file: No such file or directory**
I sincerely hope to get your reply.

**Comment by DVicendese** [comment]
HI,

I have a similar problem and get the following message 

Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.

When I try and open a package  in R that depends on rJava I get the following error message
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.

I am using a 64bit PC with  R 4.0.2, R Studio 1.3.1073 
and  have new versions of rJava, xlsxjars and reinstalled Java  8.0.2610.12  itself from
https://www.java.com/en/download/manual.jsp

What do I need to do?

Thanks in advance for your assistance

Don

**Comment by SimpleDSGit** [comment]
Hi @Rui-Jing and @DVicendese , 
Are you sure you have the same architecture type of R and Java installed on your machine? To check, go to your drives and check your Program Files folder(s). You might have two folders; one which is just "Program Files" and the other which is "Program Files (x86)". If you have two folders, R and Java should be in the same folder. If they are not in the same folder, then you likely have different architectures of R and Java. 

One thing to note, when you go to the [Java website](https://www.java.com/en/) and click the button, the Java website attempts to assess which type of operating system you have based on your browser. However, if you are using Google Chrome, this does not seem to work appropriately. I have a 64-bit system with 64-bit Chrome, but Java attempted to install the 32-bit version of Java. This would cause the issue you describe. If you go to the Java website using Firefox, the site works correctly.

**Comment by EEmanetci** [comment]
Hello,
I also have library error:
> library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
My java and R studio are in same folder. How can I fix it?
Thank you.

**Comment by s-u** [comment]
Note that you have to match both R and Java architecture. The computer architecture doesn't matter, because 64-bit PCs can run both 32-bit and 64-bit programs, what matters is which of them you are running. If you know what you're doing and have Java in a non-stadard location you can set `JAVA_HOME` to the home of the Java installation (make sure you use 8.3 path).
