### ISSUE TITLE
Undefined symbol EXTPTR_PTR in rJava.so

### ISSUE THREAD

**Issue by dhlewis61** [s-u/rJava#233]
Hi

I've been trying to install rJava and use it with the XLSX CRAN package but I encounter the undefined symbol EXTPTR_PTR. The error I'm getting is below:

R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/opt/conda/lib/R/library/rJava/libs/rJava.so':
  /opt/conda/lib/R/library/rJava/libs/rJava.so: undefined symbol: EXTPTR_PTR

I've looked at the source code and noticed that EXTPTR_PTR occurs in src/Rglue.c, src/otables.c, src/loader.c, src/arrayc.c src/fields.c, src/jri_glue.c, src/tools.c and jri/src/Rengine.c but it's only defined as a macro in src/Rglue.c.

If EXTPTR_PTR could be placed as a macro in src/rJava.h and jri/src/jri.h, that would ensure it doesn't end up as an undefined symbol in rjvm.so.

I hope I'm helping.

Cheers
David Lewis

**Comment by s-u** [comment]
Please note that this is an issue due to ABI change between R 4.0.0 and 4.0.2 - please use the package version that corresponds to the R version as those are not binary compatible.
