### ISSUE TITLE
Java version check for `early releases`

### ISSUE THREAD

**Issue by haobibo** [s-u/rJava#236]
For some early release version of Java, the $JVER variable can be like `16-ea`, which leads to version detection failure in this line: 
https://github.com/s-u/rJava/blob/ec6e26832e142ddb6149d414f6b4e0bcffecdec9/jri/configure#L3477

@s-u  Would you please consider support such kind of java version numbers?

**Comment by s-u** [comment]
Thanks, please see if this has been fixed by 651e712 in rJava 0.9-14

**Comment by haobibo** [comment]
Thx, it works.
