### ISSUE TITLE
JRI: chars in REPL callback functions needs reencoding

### ISSUE THREAD

**Issue by tatsunagai** [s-u/rJava#24]
REPL callback functions in Rcallbacks.c treat chars as UTF8 when bringing chars to (or from) Java. Original chars may not UTF8 depending on user's environment. It often becomes problem in Windows non english region.

**Comment by s-u** [comment]
Based on the experience with #51 a proper way to handle this would be to use iconv to convert to/from UTF-16 and use the `GetStringChars`/`NewString` UTF-16 versions of the JNI.
