### ISSUE TITLE
problem installing jdk 15

### ISSUE THREAD

**Issue by dollysrivastava** [s-u/rJava#240]

**Comment by dollysrivastava** [comment]
Error: failed /Library/Java/JavaVirtualMachines/jdk-15.jdk/Contents/Home/lib/server/libjvm.dylib, because dlopen(/Library/Java/JavaVirtualMachines/jdk-15.jdk/Contents/Home/lib/server/libjvm.dylib, 10): no suitable image found.  Did find:
	/Library/Java/JavaVirtualMachines/jdk-15.jdk/Contents/Home/lib/server/libjvm.dylib: code signature invalid for '/Library/Java/JavaVirtualMachines/jdk-15.jdk/Contents/Home/lib/server/libjvm.dylib'

**Comment by kamal218** [comment]
Jumping between Mac OS versions, Java versions and rJava releases might be a struggle.

Take a look here for quite comprehensive list of steps you might need to take:

http://www.owsiak.org/r-3-4-rjava-macos-and-even-more-mess/

It might be you need to recompile rJava from sources to get it working in your environment

**Comment by dollysrivastava** [comment]
Thank  you.
Dolly Srivastava (650) 722-2042 (Cell) 

    On Wednesday, October 7, 2020, 8:40:42 PM PDT, kamal218 <notifications@github.com> wrote:  
 
 


Jumping between Mac OS versions, Java versions and rJava releases might be a struggle.

Take a look here for quite comprehensive list of steps you might need to take:

http://www.owsiak.org/r-3-4-rjava-macos-and-even-more-mess/

It might be you need to recompile rJava from sources to get it working in your environment

**Comment by dollysrivastava** [comment]
Sorry to bother you again, however I'm only trying to install JDK 15, not R, nor rJava.
Dolly Srivastava (650) 722-2042 (Cell) 

    On Wednesday, October 7, 2020, 8:56:12 PM PDT, Dolly Srivastava <dollysrivastava@yahoo.com> wrote:  
 
 Thank  you.
Dolly Srivastava (650) 722-2042 (Cell) 

    On Wednesday, October 7, 2020, 8:40:42 PM PDT, kamal218 <notifications@github.com> wrote:  
 
 


Jumping between Mac OS versions, Java versions and rJava releases might be a struggle.

Take a look here for quite comprehensive list of steps you might need to take:

http://www.owsiak.org/r-3-4-rjava-macos-and-even-more-mess/

It might be you need to recompile rJava from sources to get it working in your environment
