### ISSUE TITLE
rJava not building on openSUSE Tumbleweed due to version coding

### ISSUE THREAD

**Issue by robby81** [s-u/rJava#242]
checking whether javah was replaced by javac -h... ./configure: line 3477: test: 15-internal: integer expression expected
no
configure: error: one or more Java tools are missing.

*** JDK is incomplete! Please make sure you have a complete JDK. JRE is *not* sufficient.
configure: error: ./configure failed for jri
ERROR: configuration failed for package ‘rJava’

**Comment by s-u** [comment]
Please make sure you use the latest version as this exact issue was addressed in 651e712. Also please follow basic rules about reporting issues such as providing an exact example including all software involved, how you installed dependencies and full output (not just the bit you think is important).
