### ISSUE TITLE
Error in .jfindClass(as.character(driverClass)[1])

### ISSUE THREAD

**Issue by Jaschenn** [s-u/rJava#245]
I want to use java to connect to Kylin, an OLAP database. But whatever I try, I always get this error: (see it between)
environment: R 4.0 | Java 1.8 
```
library("rJava")
> library("DBI")
> library("RJDBC")
> cp <- list.files(path = "~/Rscripts/newlib", full.names = T)
> cp
[1] "/Users/jas/Rscripts/newlib/guava-19.0.jar"      
[2] "/Users/jas/Rscripts/newlib/kylin-jdbc-2.6.6.jar"
[3] "/Users/jas/Rscripts/newlib/kylin-tool-2.6.6.jar"
> .jinit(classpath = cp)
> kylin_drive <- JDBC("org.apache.kylin.jdbc.Driver")
Error in .jfindClass(as.character(driverClass)[1]) : 
  java.lang.NoClassDefFoundError: org/apache/kylin/jdbc/shaded/com/google/common/collect/Sets
> setwd("/Users/jas/Rscripts/newlib/")
> system("ls")
guava-19.0.jar
kylin-jdbc-2.6.6.jar
kylin-tool-2.6.6.jar
> kylin_drive <- JDBC("org.apache.kylin.jdbc.Driver")
Error in .jfindClass(as.character(driverClass)[1]) : 
  java.lang.NoClassDefFoundError: Could not initialize class org.apache.kylin.jdbc.Driver
```
I have tried all the ways that I can image(use google, stackoverflow, GitHub issue)
but till now I have found no answer, 
so if there is anyone knows how to fix it, I really appreciate !

UPDATE:

`.jaddClassPath()` always return a `NULL` when I use it to add class path

```
> print(.jaddClassPath("guava-19.0.jar"))
NULL
```
I don't know why.
but it really works (really add the jar file to ClassPath)

**Comment by s-u** [comment]
`.jaddClassPath()` always returns `NULL`, it has nothing to do with success/failure. You can use `.jclassPath()` to check which directories/files are on the class path. If is doubt, enable debugging in the class loader to see why a certain class cannot be loaded:

    .jclassLoader()$setDebug(1L)

The you should see every step of the loading process. I assume this was a question and not an issue so I'm closing it.
