### ISSUE TITLE
Initial Java 12 release has broken JNI support and does NOT work

### ISSUE THREAD

**Issue by Wei494** [s-u/rJava#251]
**I'm on Windows10 running R 4.0.3 and using Java jdk11.0.1. After installing rJava and emailR and trying to use send.email, it returns this problem:**
_WARNING: Initial Java 12 release has broken JNI support and does NOT work. Use stable Java 11 (or watch for 12u if avaiable).
ERROR: Java exception occurred during rJava bootstrap - see stderr for Java stack trace.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/mail/HtmlEmail
Caused by: java.lang.ClassNotFoundException: org.apache.commons.mail.HtmlEmail
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
Error in .jnew("org.apache.commons.mail.HtmlEmail") : 
  java.lang.NoClassDefFoundError: org/apache/commons/mail/HtmlEmail.jnew("org.apache.commons.mail.HtmlEmail")new("jobjRef", jobj = <pointer: 0x00000235b46798d8>, jclass = "java/lang/NoClassDefFoundError")_

**However, the jave version I run in R is 11.0.1**
```
system("java -version")
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

I also set the path at the first, but it doesn't work:
`Sys.setenv(JAVA_HOME='C:/Program Files/Java/jdk-11.0.1')`

**Is there anything else I can try? Any help will be appreciated! Thanks in advance!**

**Comment by Wei494** [comment]
Finally, I couldn't find a method to slove this problem so I turn to Python :(

**Comment by s-u** [comment]
This was a user error - the quoted warning is unrelated to your problem.
