### ISSUE TITLE
How to let users decide the memory for JVM when they use my package based on rJava.

### ISSUE THREAD

**Issue by qiangxyz** [s-u/rJava#252]
I am creating a package using rJava, which may need a very large memory for running java sometimes. I can use options(java.parameters = "-Xmx10g) in onload.R to fixed the setting, but it is not a good way. Is there any way to let users to decide the memory for JVM after they loaded my package?

**Comment by s-u** [comment]
You can't change the setting _after_ the JVM is started, because Java only allows it to be set at initialisation time. That is a limitation of Java, unfortunately.
