### ISSUE TITLE
loading failed for 'i386'  when running devtools::check()

### ISSUE THREAD

**Issue by qiangxyz** [s-u/rJava#253]
I compiled a jar file with a 64bit JDK8 in the Windows10 X64 environment, and put it in folder "java" of my package. When I included it in my package and run devtools::check(), it returns an error: 
`ERROR: loading failed for 'i386'.`
The same error happened when I compile the jar file with a 32bit JDK8.
I also tried a very simple test package with only onLoad.R file and let the folder "java" empty, again the same error returned.

Thanks a lot.

**Comment by s-u** [comment]
If you use bi-arch R, you have to compile package for _all_ the architectures, so in your case for 32-bit and 64-bit which means you need both 32-bit and 64-bit Java. If you don't want to do that, you can use `--no-multiarch`. Please see R documentation for details (or documentation for `devtools` if you are not using non-standard tools).

**Comment by qiangxyz** [comment]
Thanks. It worked!
