### ISSUE TITLE
installation of package ‘rJava’ had non-zero exit status

### ISSUE THREAD

**Issue by Dracaris** [s-u/rJava#257]
Hello, I tried to install the package "rJava" and everything was fine until in the end it is removed from the disk where it was installed and show this message:

make: *** [Makefile.all:19: src/JRI.jar] Error 2
**** WARNING: JRI could NOT be built
Set IGNORE=1 if you want to build rJava anyway.
ERROR: configuration failed for package 'rJava'
* removing 'C:/Users/name/Documents/R/win-library/4.0/rJava'
Warning in install.packages :
  installation of package ‘rJava’ had non-zero exit status

I'm just learning about R and its multiple functions and packages, and I don't know much about commands or scripts ... If someone can guide me, I would appreciate it.

**Comment by s-u** [comment]
Compiling R packages from source on Windows it is non-trivial, I would _strongly_ recommend installing rJava from CRAN using `install.packages("rJava")` unless you are an expert.
