### ISSUE TITLE
java.awt.HeadlessException

### ISSUE THREAD

**Issue by rsakai** [s-u/rJava#26]
When I run the followiing commands using rJava, I get java.awt.HeadlessException.

f <- .jnew("java/awt/Frame","Hello")
.jcall(f,,"setVisible",TRUE)

This works fine if I call it from JGR. How can I  handle the exception? I am using OS X 10.9.4 and using RStudio.

Is it possible to call .jinit() and set java.awt.headless to false?

**Comment by Tungurahua** [comment]
@rsakai Did you get this to work? I am faced with a similar issue and would be grateful if you could explain the steps you took to 'start Java first and run R on a separat thread' as @s-u suggested.

**Comment by rsakai** [comment]
@Tungurahua Nope. I didn't find a work around....
