### ISSUE TITLE
General question - will users of rJava or packages that invoke rJava need to have a Java license under oracles new guidelines?

### ISSUE THREAD

**Issue by jzadra** [s-u/rJava#261]
Does anyone know whether users of rJava or packages that invoke rJava need to have a Java license under oracles new guidelines?

**Comment by s-u** [comment]
rJava is independent of the JVM implementation, it does not include a JVM and has nothing to do with Oracle, so, in general, no. rJava is licensed under LGPL open source license.

However, if the user chooses to install Oracle software, they will be bound by the licensing of that software, whatever the terms are.
