### ISSUE TITLE
rJava Corruption

### ISSUE THREAD

**Issue by max49326** [s-u/rJava#264]
I am attempting to install and run the 'OpenStreetMaps' pack in RStudio which require the installation of rJava. Install the 'rJava' package was successful, though when loading the package using library(), this error message occurs:

Error: package or namespace load failed for ‘rJava’ in get(Info[i, 1], envir = env):
 lazy-load database 'C:/Users/HP/Documents/R/win-library/4.0/rJava/R/rJava.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

Please could this be resolved so that I am able to use the OpenStreetMap function.

**Comment by s-u** [comment]
As the error says, your library is corrupted. Remove it from the library and re-install, if in doubt from another mirror.

**Comment by s-u** [comment]
Actually, a quick googling suggests that this may be an issue in RStudio and you need to restart it. So, as usual, try it with R, if it works then ask RStudio support.
