### ISSUE TITLE
missing flags on WSL ubuntu

### ISSUE THREAD

**Issue by mdrishti** [s-u/rJava#268]
Hi,

I am working with R on WSL Ubuntu 20.04. I am using R version 3.6.0 and tried installing rJava-1.0.4. Didn't work! Tried rJava-0.9.14. For both, I have followed the recommended commands for setting up the java configuration for R. On one hand, while running. On one hand, on running javareconf, the following happened:

JAVA_HOME        : /usr/lib/jvm/default-java
Java library path: $(JAVA_HOME)/lib/server
JNI cpp flags    : -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux
JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
Updating Java configuration in /usr/lib/R
Done.

And, then on the other hand, when installing rJAVA, the following happens:

checking Java support in R... present:
interpreter : '/usr/bin/java'
archiver    : '/usr/bin/jar'
compiler    : '/usr/bin/javac'
header prep.: '/usr/bin/javah'
cpp flags   : ''
java libs   : ''
configure: error: One or more Java configuration variables are not set.
Make sure R is configured with full Java support (including JDK). Run
R CMD javareconf
as root to add Java support to R.

Not really sure, how to solve the issue. I would appreciate some help. Thanks!

**Comment by s-u** [comment]
It looks like you didn't update the configuration in R. Make sure you have sufficient permissions to write the new configuration file in `/usr/lib/R` when using `javareconf`.
