### ISSUE TITLE
Library not found for -lpcre2-8

### ISSUE THREAD

**Issue by loukesio** [s-u/rJava#282]
Dear rJava developers, 

I would really like to thank you for your effort with rJava.
I have a MAC with M1 chip and I have just updated my R to R/4.1.1 patched. 

I have downloaded Xcode 
I have installed gcc 
and gfortran 
I have installed RccP 
but when I am trying to install rJava I see this error

I have also update JAVA_HOME =.....
and run ```sudo R CMD javareconf```

```
ld: library not found for -lpcre2-8
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libjri.jnilib] Error 1
make[1]: *** [src/JRI.jar] Error 2
make: *** [jri] Error 2
ERROR: compilation failed for package ‘rJava’
```

If you have an idea what I could do, I would be very happy

thank your for your time

**Comment by s-u** [comment]
You are missing libraries needed to compile R - please see the documentation. I would strongly suggest using the CRAN binary instead of trying to compile your own.

**Comment by loukesio** [comment]
Thank you for your time!
I am sorry but this is not helpful! Its not your fault maybe I am posting issues in the wrong place. 
I have reinstalled everything and an error still persists when I install rJava.

**Comment by s-u** [comment]
Ok, if you really don't want to read the documentation then please paste the following in your R:

```r
install.packages("rJava", repos="https://mac.R-project.org")
```

However, make sure you have installed Java that corresponds to your R architecture. I.e., if you installed arm64 R then you need arm64 Java. If you installed Intel (x86_64) R then you have to install Intel Java.

If in doubt, really do need to read the documentation: https://github.com/s-u/rJava
