### ISSUE TITLE
rJava not compatible with R 4.2.0 apple ARM64 version

### ISSUE THREAD

**Issue by epi-gde** [s-u/rJava#294]
After installing R version 4.2.0 ARM64 version, when trying to load rJava package I got this error message :
error: unable to load shared object '/library/internet plug-ins/javaappletplugin.plugin/contents/home/lib/jli/libjli.dylib': dlopen(/library/internet plug-ins/javaappletplugin.plugin/contents/home/lib/jli/libjli.dylib, 0x000a): tried: '/library/internet plug-ins/javaappletplugin.plugin/contents/home/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
I have installed the latest Java version for MacOs 
/usr/libexec/java_home -V
1.8.331.09 (x86_64) "Oracle Corporation" - "Java" /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

It may due to a Java incompatibility but I don't found any solution to make it running. 
Everything run well if I reinstall the R version 4.2.0 x86_64

**Comment by s-u** [comment]
rJava is compatible, but you have to install arm64 (aka aarch64) version of Java (see e.g. [Adoptium](https://adoptium.net/)). Officially, you'll need Java 17 as older versions don't have arm64 support ([Azul](https://www.azul.com/downloads/?os=macos&architecture=arm-64-bit&package=jdk#download-openjdk) provides Java 8, but it's their back-ported version - still, it works fine with rJava).

**Comment by epi-gde** [comment]
Perfect it run fine with Adoptium JDK 
Thanks a lot
