### ISSUE TITLE
should rJava use the same version of Java that R was configured with by default?

### ISSUE THREAD

**Issue by kevinushey** [s-u/rJava#298]
(This is really more of a question since I'm not sure if this is the intended behavior -- please let me know if there's a more appropriate forum for this.)

It looks like `rJava` searches for a version of Java to bind to on load, using the first of the following that is set:

1. The `JAVA_HOME` environment variable,
2. The output from `/usr/libexec/java_home`.

After finding where Java lives, a number of shared libraries are loaded.

However, shouldn't the `rJava` package also be consulting R to figure out what version of Java it has been configured to use as well? From what I can see, by default, R doesn't set `JAVA_HOME` on startup:

```
$ R --vanilla -s -e 'Sys.getenv("JAVA_HOME")'
[1] ""
```

However, my copy of R has indeed been configured to use a different JDK; e.g.:

```
$ cat /Library/Frameworks/R.framework/Resources/etc/ldpaths | grep JAVA_HOME=
: ${JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.0.1+12/Contents/Home}
```

And this ultimately means that `rJava` might end up loading libraries from a different JDK installation; e.g. I see on my machine:

```
> library(rJava)
> system(paste("lsof -p", Sys.getpid(), "| grep libjvm"))
R       4988 kevin  txt    REG   1,16 16983360            48120481 /Library/Java/JavaVirtualMachines/temurin-18.jdk/Contents/Home/lib/server/libjvm.dylib
```

And that is indeed what `/usr/libexec/java_home` reports:

```
$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/temurin-18.jdk/Contents/Home
```

Is this behavior intentional, or would this be considered a case of a user misconfiguring their system / R installation? (Is the intention that any user who wants to change the default Java installation also needs to run `sudo R CMD javareconf`?)

---

```
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] rJava_1.0-6

loaded via a namespace (and not attached):
[1] compiler_4.2.0
```

**Comment by s-u** [comment]
rJava works as expected - it will honor the `JAVA_HOME` env var, but what you describe seems like a bug in R, because `JAVA_HOME` is not exported, so it is not actually set for the R process.

```
echo 'export JAVA_HOME' >> /Library/Frameworks/R.framework/Resources/etc/ldpaths
```
fixes the issue.

**Comment by kevinushey** [comment]
Thanks; I wasn't sure if the behavior here in R was intentional or not. It seemed like the intention here was for R to export `JAVA_HOME`, but that is indeed not happening.

I'll file this on the R bug tracker.
