### ISSUE TITLE
Typo in file -- configure.win-- INGORE -- you probably meant IGNORE 

### ISSUE THREAD

**Issue by RohitDhankar** [s-u/rJava#304]
There seems to be a TYPO Here 

https://github.com/s-u/rJava/blob/e6b495d1ee85a869d29986f0777d8126f7931927/configure.win#L53

INGORE -- whats INGORE -- you probably meant IGNORE -- right ? 

`	echo "**** WARNING: JRI could NOT be built" >&2
	if [ -z "$INGORE" ]; then
	    echo "Set IGNORE=1 if you want to build rJava anyway."`

**Comment by s-u** [comment]
Thanks!
