### ISSUE TITLE
R freezes when executing rJava::.jinit()

### ISSUE THREAD

**Issue by carlosvblessa** [s-u/rJava#307]
R 4.3.0, Ubuntu 22.04, Java version 1.8.0_291.
Tested rJava versions:
0.9-13.
1.0-4
1.0-5
1.0-6

In all R freezes when calling the .jinit() function.
![image](https://user-images.githubusercontent.com/77589169/234841380-a1fc719c-da61-433a-8ae2-e0ca42efe954.png)

**Comment by carlosvblessa** [comment]
It worked with java version 11.0.9
java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)
![image](https://user-images.githubusercontent.com/77589169/235238968-4792c687-d8fa-4f72-974b-755464f90c50.png)

**Comment by yudalang3** [comment]
@carlosvblessa  So What is the solution? Use the openJDK？
