### ISSUE TITLE
Termination Error with rJava When Executing Complex R Code from Java Application

### ISSUE THREAD

**Issue by kishoreelli** [s-u/rJava#310]
Hello, I recently migrated my Java application to JDK-17, Ubuntu 20.04, and R version 4.3.0. Previously, my application was working fine in JDK 1.8 and Ubuntu 18. However, I am now facing an issue with rJava, as my application is terminating with the following errors:

Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C [libR.so+0x1934b3]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j org.rosuda.JRI.Rengine.rniParse(Ljava/lang/String;I)J+0
j org.rosuda.JRI.Rengine.eval(Ljava/lang/String;Z)Lorg/rosuda/JRI/REXP;+53
j org.rosuda.JRI.Rengine.eval(Ljava/lang/String;)Lorg/rosuda/JRI/REXP;+3
j com.demo.RCheck.oneway()V+19
j com.demo.RCheck.main([Ljava/lang/String;)V+0
v ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000018

I am trying to execute 'source(script.r)' from Java, and it works fine for normal scripts. However, whenever the R code contains more 'else if' statements grater than 5 and more nested if statements, or uses certain normal R functions, I encounter this error.

**Comment by s-u** [comment]
Thanks. Can you, please, post an example here that triggers the problem? (I.e. the actual code that triggers the parser crash). The above is not sufficient information to look into it.

**Comment by kishoreelli** [comment]
i am facing crash of jvm i this code. if i commented it. the process is working fine.

# Check if any plots should be generated
if (any(dict$plots)) {
  outcome[nrow(outcome) + 1, ] <- c("Diagnostics Plots", "Subtitle", "")
  for (m in 1:length(dict$plots)) {
    plotcode <- paste("plot(onewayanova, which=", m, ", col='", dict$plotcolor, "')", collapse="", sep="")
    if (isTRUE((dict$plots)[m])) {
      if (names(dict$plots)[m] == "Residuals vs Fitted") {
        outcome[nrow(outcome) + 1, ] <- c("Residuals vs Fitted Plot", "Rcode", plotcode)
        if (is.null(myTryCatch(eval(parse(text = plotcode)))$error)) {
          pngfile <- tempfile()
          eval(parse(text = paste("png(pngfile, width=", dict$plotsize[1], ",height=", dict$plotsize[2], ")", collapse="", sep="")))
          eval(parse(text = plotcode))
          dev.off()
          outcome[nrow(outcome) + 1, ] <- c("Residuals vs Fitted Plot", "Plot", toString(base64::img(pngfile)))
        } else {
          outcome[nrow(outcome) + 1, ] <- c("Residuals vs Fitted Plot", "Error", toString(myTryCatch(eval(parse(text = plotcode)))$error))
        }
      } else if (names(dict$plots)[m] == "Normal Q-Q") {
        outcome[nrow(outcome) + 1, ] <- c("Normal Q-Q Plot", "Rcode", plotcode)
        if (is.null(myTryCatch(eval(parse(text = plotcode)))$error)) {
          pngfile <- tempfile()
          eval(parse(text = paste("png(pngfile, width=", dict$plotsize[1], ",height=", dict$plotsize[2], ")", collapse="", sep="")))
          eval(parse(text = plotcode))
          dev.off()
          outcome[nrow(outcome) + 1, ] <- c("Normal Q-Q Plot", "Plot", toString(base64::img(pngfile)))
        } else {
          outcome[nrow(outcome) + 1, ] <- c("Normal Q-Q Plot", "Error", toString(myTryCatch(eval(parse(text = plotcode)))$error))
        }
      } else if (names(dict$plots)[m] == "Scale-Location") {
        outcome[nrow(outcome) + 1, ] <- c("Scale-Location Plot", "Rcode", plotcode)
        if (is.null(myTryCatch(eval(parse(text = plotcode)))$error)) {
          pngfile <- tempfile()
          eval(parse(text = paste("png(pngfile, width=", dict$plotsize[1], ",height=", dict$plotsize[2], ")", collapse="", sep="")))
          eval(parse(text = plotcode))
          dev.off()
          outcome[nrow(outcome) + 1, ] <- c("Scale-Location Plot", "Plot", toString(base64::img(pngfile)))
        } else {
          outcome[nrow(outcome) + 1, ] <- c("Scale-Location Plot", "Error", toString(myTryCatch(eval(parse(text = plotcode)))$error))
        }
      } else if (names(dict$plots)[m] == "Cook's Distance") {
        outcome[nrow(outcome) + 1, ] <- c("Cook's Distance Plot", "Rcode", plotcode)
        if (is.null(myTryCatch(eval(parse(text = plotcode)))$error)) {
          pngfile <- tempfile()
          eval(parse(text = paste("png(pngfile, width=", dict$plotsize[1], ",height=", dict$plotsize[2], ")", collapse="", sep="")))
          eval(parse(text = plotcode))
          dev.off()
          outcome[nrow(outcome) + 1, ] <- c("Cook's Distance Plot", "Plot", toString(base64::img(pngfile)))
        } else {
          outcome[nrow(outcome) + 1, ] <- c("Cook's Distance Plot", "Error", toString(myTryCatch(eval(parse(text = plotcode)))$error))
        }
      } else if (names(dict$plots)[m] == "Residuals vs Leverage") {
        outcome[nrow(outcome) + 1, ] <- c("Residuals vs Leverage Plot", "Rcode", plotcode)
        if (is.null(myTryCatch(eval(parse(text = plotcode)))$error)) {
          pngfile <- tempfile()
          eval(parse(text = paste("png(pngfile, width=", dict$plotsize[1], ",height=", dict$plotsize[2], ")", collapse="", sep="")))
          eval(parse(text = plotcode))
          dev.off()
          outcome[nrow(outcome) + 1, ] <- c("Residuals vs Leverage Plot", "Plot", toString(base64::img(pngfile)))
        } else {
          outcome[nrow(outcome) + 1, ] <- c("Residuals vs Leverage Plot", "Error", toString(myTryCatch(eval(parse(text = plotcode)))$error))
        }
      } else if (names(dict$plots)[m] == "Cook's Distance vs Leverage") {
        outcome[nrow(outcome) + 1, ] <- c("Cook's Distance vs Leverage Plot", "Rcode", plotcode)
        if (is.null(myTryCatch(eval(parse(text = plotcode)))$error)) {
          pngfile <- tempfile()
          eval(parse(text = paste("png(pngfile, width=", dict$plotsize[1], ",height=", dict$plotsize[2], ")", collapse="", sep="")))
          eval(parse(text = plotcode))
          dev.off()
          outcome[nrow(outcome) + 1, ] <- c("Cook's Distance vs Leverage Plot", "Plot", toString(base64::img(pngfile)))
        } else {
          outcome[nrow(outcome) + 1, ] <- c("Cook's Distance vs Leverage Plot", "Error", toString(myTryCatch(eval(parse(text = plotcode)))$error))
        }
      } else {
        plotcode <- paste("plot(TukeyHSD(onewayanova), col='", dict$plotcolor, "')", collapse="", sep="")
        outcome[nrow(outcome) + 1, ] <- c("Tukey's HSD Plot", "Rcode", plotcode)
        if (any(is.nan(TukeyHSD(onewayanova)[[1]][, 1])) | any(is.nan(TukeyHSD(onewayanova)[[1]][, 2])) | any(is.nan(TukeyHSD(onewayanova)[[1]][, 3])) | any(is.nan(TukeyHSD(onewayanova)[[1]][, 4]))) {
          outcome[nrow(outcome) + 1, ] <- c("Tukey's HSD Plot", "Error", "Error")
        } else {
          pngfile <- tempfile()
          eval(parse(text = paste("png(pngfile, width=", dict$plotsize[1], ",height=", dict$plotsize[2], ")", collapse="", sep="")))
          eval(parse(text = plotcode))
          dev.off()
          outcome[nrow(outcome) + 1, ] <- c("Tukey's HSD Plot", "Plot", toString(base64::img(pngfile)))
        }
      }
    }
  }
}
write(jsonlite::serializeJSON(outcome), file="/home/kishore/Documents/RProjectCheck/GeneratedFiles/outcome.json")

**Comment by s-u** [comment]
Sorry, I cannot replicate, I tried (adding in `rtest.java`):

```java
 String code = java.nio.file.Files.readString(java.nio.file.Paths.get("code.R"));
 re.eval(code, false);
```

where `code.R` is what you posted above, but it parses just fine.

---
FWIW: as and aside, using `eval()` inside R code is quite dangerous (due to arbitrary code injection), inefficient and unnecessary - e.g.
```
eval(parse(text = paste("png(pngfile, width=", dict$plotsize[1], ",height=", dict$plotsize[2], ")", collapse="", sep="")))
```
can be simply written as
```
png(pngfile, width=dict$plotsize[1], height=dict$plotsize[2])
```
