### ISSUE TITLE
Struggling with rJava and dependent packages in Rstudio Mac M1. Error: package or namespace load failed for ‘rJava’: 

### ISSUE THREAD

**Issue by GabriellaS-K** [s-u/rJava#312]
Hi, 

I'm really struggling with rJava. I have a new machine (Mac M1) and am running r code from an older project on an old intel Mac, and it isn't working at all. I am not especially familiar or confident with this, or using the terminal so please bare this in mind when answering :) 

The error message I am getting is: 

```
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(jli, FALSE)
  error: unable to load shared object '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib':
  dlopen(/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib, 0x000A): tried: '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib' (no such file), '/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

I think one issue is that if I run 
`$/usr/libexec/java_home
/usr/libexec/java_home
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
`
It thinks java is not in the right place?

I tried to rectify this by doing: 
`JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-1.8.jdk/Contents/Home
`
but it doesn't seem to make a difference. 

               _                           
```
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          3.1                         
year           2023                        
month          06                          
day            16                          
svn rev        84548                       
language       R                           
version.string R version 4.3.1 (2023-06-16)
nickname       Beagle Scouts               
```

Please let me know if there is other info needed! Thank you for any help

**Comment by GabriellaS-K** [comment]
This was rectified by  downloading Azul https://www.azul.com/core-post-download/?endpoint=zulu&uuid=cf6e06ec-c897-4b5a-9859-e1c547ff5864, now I have three versions of java which I'm sure will be a problem down the line...

**Comment by s-u** [comment]
@GabriellaS-K it means that you don't have Java. What's listed is just an Internet plugin, not actual Java installation. So as you found out, you have to download a proper Java SDK (nowadays https://adoptium.net/ is the most common source for macOS).

**Comment by GabriellaS-K** [comment]
thank you, you're quite right :)
