### ISSUE TITLE
long vectors not supported yet: memory.c:3888

### ISSUE THREAD

**Issue by yunmika** [s-u/rJava#315]
Hi guys,
The following error occurs when I read the matrix using rJava：
Error in .jarray(j.matrix, dispatch = TRUE) : 
  long vectors not supported yet: memory.c:3888
Calls: genotypes -> .jarray
Execution halted
I don't know what went wrong. Is there anything I can do to fix the problem?

**Comment by s-u** [comment]
This is a limitation in Java - Java does not support arrays with more than 2^31-1 elements, so you will have to split the matrix to handle it in Java (by row/column or into blocks).
