### ISSUE TITLE
Please submit rJava 1.0-8 to CRAN

### ISSUE THREAD

**Issue by HenrikBengtsson** [s-u/rJava#316]
Because `rJava::.jinit()` stalls with certain, not uncommon Java and GCC set-ups, could you please submit rJava 1.0-8 to CRAN?  This would be particular helpful to a lot of users and sysadmins, because rJava has many reverse package dependencies, and many of those packages fail to install because of this problem.

The background can be found in https://github.com/s-u/rJava/issues/300, where the problem was [identified and solved](https://github.com/s-u/rJava/issues/300#issuecomment-1367721064);

> I assume this is in some old JDK < 10 since that code should only be used for legacy JVMs. I can replicate it on Debian testing with gcc 12 and JDK 8. Apparently the compiler does tail call optimization (TCO) and thus completely destroys our stack detection attempts. Please test rJava 1.0-8, by making dummy volatile I attempted to convince gcc to avoid TCO - seems to work at least for now.

Please note that Java 8 (=Java 1.8) is still a common default on many systems. One example is CentOS 7, which is still widely used out there. The problem appears to kick in with GCC (>= 11). Putting rJava 1.0-8 to CRAN would allow sysadmins to safely provide GCC (>= 11) to R users without having to write special instructions and answer support emails around issues with rJava and dependent packages stalling during installation.

Please.

**Comment by s-u** [comment]
rJava has been already submitted, but apparently some rev-deps fail, so I need more time to figure out if those are bugs in the packages or some changes related to rJava ..
