### ISSUE TITLE
Licensing uncertainty

### ISSUE THREAD

**Issue by Gewerd-Strauss** [s-u/rJava#323]
Hello there,

can you please add a viable (preferably MIT or viable open-source) license to this package, so that it may be used by other people?

Thank you.
Sincerely,
~Gw

**Comment by s-u** [comment]
The package is licensed under LGPL-2.1 which is a very open license.

**Comment by Gewerd-Strauss** [comment]
Well, I am completely blind; and sorry for opening this issue. Nonetheless, thank you for the clarification.
