### ISSUE TITLE
Can objects generated by rJava be saved locally?

### ISSUE THREAD

**Issue by yunmika** [s-u/rJava#324]
Hi, I attempted to save objects generated by rJava using saveRDS to my local machine. However, upon attempting to re-read them using readRDS, I found that the objects were corrupted. Are there alternative methods to avoid this issue?

**Comment by s-u** [comment]
Yes, they can as long as the Java objects you save support serialization.

If you have issues, you'll have to elaborate on the exact Java and R code you are using to create, save and restore the state.

**Comment by yunmika** [comment]
Thanks for your reply, the issue has been successfully resolved.
