### ISSUE TITLE
R session Aborted Rjava

### ISSUE THREAD

**Issue by yenicapachac** [s-u/rJava#325]
I have a problem running RSTUDIO, I am using the "xlsx" and "rjava" package to read and save a large amount of hydrological data on a daily level (approximately 60000 rows and 70 columns) and I get "A fatal error has been detected by the Java Runtime Environment: # EXCEPTION_ACCESS_VIOLATION" restrictions.
Among some solutions I preferred to work with less columns, however now every time I run the code, the program quits even with executing a line to load a package. To date I can't run Rstudio because I get "Rsesion aborted", I have tried from uninstalling R, changing java versions, increasing the working capacity of the Java memory options( java.parameters = "-Xmx10g" ) , clearing cache; but none of them work. 
Also, I have the program report and I have compiled some screenshots in a power point of the errors:

[hs_err_pid22932.log](https://github.com/s-u/rJava/files/14804772/hs_err_pid22932.log)
[https://1drv.ms/p/s!Atkj5l6S-8GVgs1rc4cmZXNiFJxSQw?e=yfaAmy](url)

I would be grateful if you could provide me with a solution.

**Comment by s-u** [comment]
First, please try it in R since there have been issues reported in some versions of RStudio (if it is an issue in RStudio please check their support). If the problem persist in R, please share the exact code you use, full output of `sessionInfo()`, and your Java version.
