### ISSUE TITLE
Confused documentation about JRI  and rJava

### ISSUE THREAD

**Issue by softboy99** [s-u/rJava#330]
On JRI page, It saids that "JRI is now part of [rJava](http://www.rforge.net/rJava/), so if you simply want to use JRI, install rJava binary and your'e all set! There will be no further stand-alone JRI releases, JRI is now released only as a part of rJava". 

Howerver, On rJava Page, it saids that "If you want to run R within a Java application, please see the [JRI](http://www.rforge.net/JRI/) pages for details. rJava allows you to use R code to create Java objects, call Java methods and pass data between R and Java."

I want to run simple R script within a Java application, what i should do. Use old JRI or new RJava?

**Comment by s-u** [comment]
You can do either. However, if you are not familiar with R or Java then I recommend using rJava CRAN binary as that already has everything compiled and ready to use.
