### ISSUE TITLE
Failure to Load rJava

### ISSUE THREAD

**Issue by EdwinDrake** [s-u/rJava#333]
I am failing to load rJava in RStudio despite it showing that it is already installed as shown below:

library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: JAVA_HOME cannot be determined from the Registry
In addition: Warning message:
package ‘rJava’ was built under R version 4.3.2

**Comment by e-kotov** [comment]
do you have Java installed in the system?

please print output from the following R commands:

```r
Sys.getenv("JAVA_HOME")
Sys.which("java")
system("java -version")
```

**Comment by EdwinDrake** [comment]
This is the Output I have
> Sys.getenv("JAVA_HOME")
[1] ""
> Sys.which("java")
java 
  "" 
> system("java -version")
[1] 127

**Comment by e-kotov** [comment]
@EdwinDrake it seems like you do not have Java installed, or at least setup properly.
You might want to try installing Java. You may do that manually by downloading Java from some provider, overview is here https://whichjdk.com/

You can also just install java with `{rJavaEnv}` https://github.com/e-kotov/rJavaEnv
alternatively there are also some non-R Java environment managers:

- https://www.jenv.be/
- https://github.com/shyiko/jabba
and many others


With `{rJavaEnv}` the process would be as follows:

```r
# cran does not have latest binary for rJavaEnv, so please install from R universe, CRAN will have the same version in a few days
install.packages('rJavaEnv',
 repos = c('https://community.r-multiverse.org', 'https://cloud.r-project.org')
)


# this will install Amazon Corretto Java version 21 automatically and set up the paths for your current working directory/project directory. So every time you work in that directory, this version of Java should be picked up by `{rJava}`. Please read the consent warning that will pop-up in the R console the first time you run this function. You may have to restart R, but generally this is not needed.
library(rJavaEnv)
java_quick_install(21)

# if you only want to use Java in the current running R session just use the lines below. You will need to keep them in all your scripts before you do library(rJava)
library(rJavaEnv)
use_java(21)
```

Please do not do `library(rJava)` before running the commands above, or they will not help, as `{rJava}` "locks" where it looks for Java as soon as you load it with `library()` command. It will even "lock" these folders if you so much as have accessed the autocomplete, say by typing `rJava::` in your code or in console. So if so "touched" `{rJava}` in any way at all, even without trying to initialise Java, you will have to restart the R session to be able to set Java paths.

Let me know if this works.

If that does not help and you are on Linux or Mac (but it seems to me you are on Windows, as you had "JAVA_HOME cannot be determined from the Registry"), you may have to do this procedure: https://solutions.posit.co/envs-pkgs/using-rjava/#reconfigure-r

Here is how you could do it:

```
library(rJavaEnv)
java_home <- java_unpack(java_download(21, quiet = TRUE), quiet = TRUE)
cat(java_home)
```

Copy this java home and use it in the following command in system shell/terminal:

```sh
sudo R CMD javareconf JAVA_HOME='<paste_here_what_you_got_from_java_home_variable_in_r_above>'
```

**Comment by EdwinDrake** [comment]
Thank youso much
I downloaded and installed Java from Oracle and it worked out

**Comment by s-u** [comment]
Ideally, please read the "Troubleshooting" section - in 90% of case it simply means you didn't install the correct Java matching your R architecture.
