### ISSUE TITLE
The work dir. problem: the JVM user.dir always bind with the Rstudio work dir.

### ISSUE THREAD

**Issue by yudalang3** [s-u/rJava#337]
# The problem
I run a GUI desktop app on the Rstudio. It is previous run by the cmd line or the exe file. 
So, the launch path is already fiexed, add the resources the program used is always relative to the fixed path.

Then, everything change when I used in the Rstudio.
Because, the JVM user dir is always bind with the Rstudio work dir, so, the program can not get the resource.

The R running path is not same with the program launching path. In a real-life scenario, it is very common.

Any solutions ?

# What I tried

```R
options(java.parameters = c("-Duser.dir=C:/Users/yudal/Documents/project/eGPS2/eGPS_v2_windows_openJDK8_64bit","-Xmx4g"))
```
This is not work!!

setwd()

then, change to the original wd.

This is not work, because the JVM user dir also will change.

**Comment by s-u** [comment]
Please contact Posit support for any questions about RStudio or their apps.

**Comment by yudalang3** [comment]
Do you have any problem about when running the R from the CLI?  will you have problem in the User.dir? @s-u
