### ISSUE TITLE
Cannot install on Yosemite: homebrew-cask java 1.8.0_25, homebrew R 3.1.2

### ISSUE THREAD

**Issue by mpodell** [s-u/rJava#36]
Not sure this is a rJava problem but looking for help.

Installing R via homebrew gives me this message:

```
To enable rJava support, run the following command:
  R CMD javareconf JAVA_CPPFLAGS=-I/System/Library/Frameworks/JavaVM.framework/Headers
If you've installed a version of Java other than the default, you might need to instead use:
  R CMD javareconf JAVA_CPPFLAGS='-I/System/Library/Frameworks/JavaVM.framework/Headers -I/Library/Java/JavaVirtualMachines/jdk<version>.jdk/'
  (where <version> can be found by running `java -version` or `locate jni.h`)

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
```
running either (subbing `jdk1.8.0_25.jdk` for `<version>`) fails not finding `jni.h`

java installs `jni.h` into
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/include
```
Since there was nothing at `/System/Library/Frameworks/JavaVM.framework/Headers/` where `javareconf` seems to want to look for it, I created symlinks:
```
cd /System/Library/Frameworks/JavaVM.framework/Versions
sudo ln -nsf /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents ./CurrentJDK
cd /System/Library/Frameworks/JavaVM.framework
sudo ln -nsf Versions/CurrentJDK/Home/include/ ./Headers
```
and added
```
export JAVA_HOME = "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home"
```
to ```~/.bash_profile``` since without it `javareconf` says the JAVA_HOME is not a valid path. This allows `javareconf` to find `jni.h` using:

```
R CMD javareconf JAVA_CPPFLAGS=-I/System/Library/Frameworks/JavaVM.framework/Headers -I/System/Library/Frameworks/JavaVM.framework/Headers/
```
but then `javareconf` fails because it can't find `jni_md.h` which is in `/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/include/dawrin`

looking at `javareconf` there is this code:

        ## only if we get jni.h we can try to find jni_md.h
        if test -n "${jinc}"; then
           JAVA_CPPFLAGS="-I${jinc}"
           jmdinc=''
           jmdirs=''
       ## we are not in configure, so we need to find the OS from R
       host_os=`echo 'cat(R.version$os)'|${R_HOME}/bin/R --vanilla --slave 2>/dev/null`
           ## put the most probable locations for each system in the first place
           case "${host_os}" in
             darwin*)  jmdirs=darwin;;
             linux*)   jmdirs=linux;;
             bsdi*)    jmdirs=bsdos;;
             osf*)     jmdirs=alpha;;
             solaris*) jmdirs=solaris;;
             freebsd*) jmdirs=freebsd; add_java_libs='-lpthread';;
           esac
I would think that this would allow `javareconf` to find the `jni_md.h` but that's not happening.

This may not be a rJava issue but since the R install said to run `javareconf` in order to enable `rJava` support, I thought I would post here, but then again, I know just enough to know that I know nothing about this stuff. I'm just bummed I can't get rJava installed in R.

Thanks for taking the time to read this.

**Comment by yasirs** [comment]
@gwinstanley
What is $JAVA_HOME in OSX?
I get $ which java
/usr/bin/java
 ls -alth /usr/bin/java
lrwxr-xr-x  1 root  wheel    74B Oct 23  2013 /usr/bin/java -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java

**Comment by gwinstanley** [comment]
Good point @yasirs, I forgot to mention that I usually set the JAVA_HOME variable in my ```.zshenv```/```.bashrc``` file. This is the line I usually include in mine:
```
export JAVA_HOME=`/usr/libexec/java_home`
```
or if you want a specific version of Java (e.g. Java 8):
```
export JAVA_HOME=`/usr/libexec/java_home -v1.8`
```

**Comment by s-u** [comment]
@gwinstanley check with RStudio - one way to make sure that you have correct vars set is to use `R CMD open -a RStudio` or similar. Normally, RStudio should be using R's vars, but I'm not sure if they actually do. Either way, always test with R first to make sure it's not a bug in RStudio (which is not R).
Also do *not* set `JAVA_HOME` 


As for configuration, with properly installed Oracle Java (do *not* set `JAVA_HOME` manually!) you should see something like

```
Java interpreter : /usr/bin/java
Java version     : 1.8.0_20
Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar
Non-system Java on OS X

trying to compile and link a JNI program 
detected JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
detected JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/../include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/../include/darwin -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c conftest.c -o conftest.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o conftest.so conftest.o -L/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/server -ljvm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation


JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre
Java library path: $(JAVA_HOME)/lib/server
JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
```

**Comment by gwinstanley** [comment]
I like the idea of launching from the ```R CMD ...```, which should pick up the Java config from the R installation. Regarding JAVA_HOME though, I have three Java installations on my machine, so I have it set to configure many other items from the specific Java version I'm using. I found the standard *javareconf* script failed without both disabling the OS auto-detect for Darwin, and custom configuring JAVA_HOME & JAVA_CPPFLAGS. It would make sense if *javareconf* correctly detected this (e.g. using jdk1.8.0_xx), but it didn't work for me, hence the workaround I posted. That said, perhaps it's updated since I last tried (27 Nov 2014).

**Comment by gwinstanley** [comment]
So I've just upgraded to the latest Hombrew version of R (3.2.1_1) and latest Java (1.8.0_51), and I get the following using the recommended
```R CMD javareconf JAVA_CPPFLAGS=-I/System/Library/Frameworks/JavaVM.framework/Headers```:
However, it works fine using my technique as shown above.
```
Java interpreter : /usr/bin/java
Java version     : 1.8.0_51
Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar
Non-system Java on OS X

trying to compile and link a JNI program
detected JNI cpp flags    : -I/System/Library/Frameworks/JavaVM.framework/Headers
detected JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
clang -I/usr/local/Cellar/r/3.2.1_1/R.framework/Resources/include -DNDEBUG -I/System/Library/Frameworks/JavaVM.framework/Headers -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include    -fPIC  -g -O2  -c conftest.c -o conftest.o
conftest.c:1:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^
1 error generated.
make: *** [conftest.o] Error 1
Unable to compile a JNI program


JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre
Java library path:
JNI cpp flags    :
JNI linker flags :
```

**Comment by gwinstanley** [comment]
BTW, if anyone's arrived at this thread still looking for a fix for the latest Java/rJava, I've created a [gist](https://gist.github.com/gwinstanley/884d6af25844bdaeb0c81f95bb285768) for it.
