### ISSUE TITLE
"No Java runtime" error in OS X 10.10 using Oracle's 1.8.0 JVM

### ISSUE THREAD

**Issue by serpico7456** [s-u/rJava#37]
I've tried 3 different Macs running OS X 10.10, R 3.1.2, Java 1.8.0_25, and rJava 0.9-7.  In all three cases rJava installs from source without error but after running .jinit(), fails to detect Java and prompts to install Java 6 from apple.  Another researcher at my institution reports the same issue.

I've spent hours researching online, but haven't yet found a solution and tried various things like manually setting JAVA_HOME and LD_LIBRARY_PATH to no avail.

>R CMD javareconf
Java interpreter : /usr/bin/java
Java version     : 1.8.0_25
Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar
...

~ % echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
~ % echo $LD_LIBRARY_PATH
/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/server

~ % R CMD INSTALL rJava_0.9-7.tar.gz

[full compile output](https://gist.github.com/serpico7456/224e05d657aa891c53b5)

~ % R

> library('rJava')
> .jinit()
No Java runtime present, requesting install.

**Comment by yufree** [comment]
Hi, I tried @conjugateprior 's method(re-config R and rJava) and it still show me 1.6.0_65-b14-466.1-11M4716. When I use JGR, the issue disappeared. I am still confused but right now I could use RNetLogo.

**Comment by conjugateprior** [comment]
@yufree I've put as much as I understand in a [blog post](http://conjugateprior.org/2014/12/r-java8-osx/). The comments also have some detail on setting paths.  I suppose it's possible that JGR is setting them correctly for you when loaded. (I've never used it, so I don't know.)

**Comment by yufree** [comment]
Thank you! I checked you posts and tried again in RStudio, still 1.6, not 1.8. It seemed something wired happened between RStudio and rJava.
> 在 2015年1月4日，下午10:44，Will Lowe <notifications@github.com> 写道：
> 
> @yufree I've put as much as I understand in a blog post. The comments also have some detail on setting paths. I suppose it's possible that JGR is setting them correctly for you when loaded. (I've never used it, so I don't know.)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

State Key Laboratory of Environmental Chemistry and Ecotoxicology
Research Center for Eco-Environmental Sciences
Chinese Academy of Sciences
P.O. Box 2871
Beijing, 100085
Tel: +86-10-6284-9119
Email: yumiao210@mails.ucas.ac.cn
Pages: http://yufree.github.io

**Comment by s-u** [comment]
Note that there is a very nasty bug in Yosemite concerning environment variables, so you may want to avoid RStudio for installing packages - use R in the shell which doesn't trigger the bug. First try if things are working in command line R, if they do then worry about RStudio (check for updates/betas since I know they have been working around that bug in some version).

To check what's happening, you can set `DYLD_PRINT_LIBRARIES` and it will show you which `libjvm` is loaded - you want the one from Java 1.8.

**Comment by yufree** [comment]
Thanks @s-u .In fact I know the bug and I always run RStudio from terminal and it could solve most of the problems because RStudio could inherit the environment variables from treminal. But this one it didn't work.

    /Applications/RStudio.app/Contents/MacOS/RStudio

For  `DYLD_PRINT_LIBRARIES`, I found the rJava still use 1.6.

    > library(rJava)
    dyld: loaded: /Library/Frameworks/R.framework/Versions/3.1/Resources/library/rJava/libs/rJava.so
    dyld: loaded: /System/Library/Frameworks/JavaVM.framework/Versions/A/JavaVM
    dyld: loaded: /System/Library/PrivateFrameworks/JavaLaunching.framework/Versions/A/JavaLaunching
    > .jinit()
    dyld: loaded: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bundle/Libraries/libclient64.dylib
    dyld: loaded:     /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/../Libraries/libjvmlinkage.dylib
    dyld: loaded: /usr/lib/libstdc++.6.dylib
    dyld: loaded: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libverify.dylib
    dyld: loaded: /System/Library/Frameworks/JavaVM.framework/Versions/A/Frameworks/JavaNativeFoundation.framework/Versions/A/JavaNativeFoundation
    dyld: loaded: /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    dyld: loaded: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjava.jnilib
    dyld: loaded: /System/Library/Frameworks/JavaVM.framework/Versions/A/Frameworks/JavaRuntimeSupport.framework/Versions/A/JavaRuntimeSupport
    dyld: loaded: /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    dyld: loaded: /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    dyld: loaded: /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    dyld: loaded: /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    dyld: loaded: /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    dyld: loaded: /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    dyld: loaded: /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    dyld: loaded: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libzip.jnilib

I tried to use `sudo R CMD javareconf -n`, it seemed R has known 1.8.

    Java interpreter : /usr/bin/java
    Java version     : 1.8.0_20
    Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre
    Java compiler    : /usr/bin/javac
    Java headers gen.: /usr/bin/javah
    Java archive tool: /usr/bin/jar
    Non-system Java on OS X
    
    trying to compile and link a JNI progam 
    detected JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
    detected JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
    clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/../include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/../include/darwin -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c conftest.c -o conftest.o
    clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o conftest.so conftest.o -L/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/server -ljvm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
    
    
    JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre
    Java library path: $(JAVA_HOME)/lib/server
    JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
    JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm

Then I try to install rJava from source `install.packages('rJava', type='source')`. Try the following code

    library(rJava)
    .jinit()
    .jcall("java/lang/System", "S", "getProperty", "java.runtime.version")

Still `1.6.0_65-b14-466.1-11M4716`. I think I have re-config R and rJava but rJava just ignore 1.8. I also confused by JGR, some code and the output is `1.8.0_20-b26`. This is the right one.

Thus, I think rJava and JGR are fine but connection between RStudio and rJava has something wrong. I hope this issue only happened in my mac.

**Comment by sherbrich** [comment]
@sdaza - could you provide a walk through (with terminal commands) of what you did to finally get this working on your laptop?

**Comment by sdaza** [comment]
@sherbrich This is what I did (remember that I use R in terminal): 

1. Install Java 8 (http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
2. Install Java 6 from Mac (http://support.apple.com/kb/DL1572)
3. It is necessary to define correctly the java home directory. I used `/Library/Java/Home`, but it could be another. You can use eclipse IDE (preferences, installed jREs) to define the directory.
3. Reconfigure R using `sudo R CMD javareconf -n` in terminal
4. Install rJava as source `install.packages("rJava", type="source"`)
4. You can check in the terminal to make sure you have linked rJava against 1.8 and not 1.6.

```DYLD_PRINT_LIBRARIES=1 R 
library(rJava)
.jinit()
.jcall("java/lang/System", "S", "getProperty", "java.runtime.version")
```

Then, install `RNetLogo`. That's it.

**Comment by hdbeukel** [comment]
I am experiencing this issue as well and tried all your suggestions, without success. Both Java 8 and 6 are installed, I defined the necessary environment variables, reconfigured R and reinstalled rJava from source. Still, R links rJava against 1.6 instead of 1.8.

Is there anything else I can try?

**Comment by s-u** [comment]
An update on the Oracle bug: it will be fatal eventually, because Apple will stop providing 1.6 runtime at which point you can't get 1.6 to appease the Oracle loader so you can't load 1.8.

But thanks to Mike Swingler at Apple we have a work-around (the stub checks for the existence of `libjli` to see if it should try 1.6). In fact we may end up using a way to detect JVM at run-time just like we do on Windows since that's probably the only way to support Oracle Java in the long run given its non-standard location that changes with each update.

**Comment by s-u** [comment]
For those that have trouble forcing 1.8, try the following:

    jvm=`ls /Library/Java/JavaVirtualMachines/*/Contents/Home/jre/lib/server/libjvm.dylib`
    sudo install_name_tool -id "$jvm" "$jvm"

and then re-compile rJava from sources. That above makes sure that jvm will link in the proper full path to the library so it's guaranteed to be found - even if no special environment variables are set.

**Comment by hdbeukel** [comment]
The trick with setting

```
jvm=`ls /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/server/libjvm.dylib`
sudo install_name_tool -id "$jvm" "$jvm"
```

before installing rJava from source worked for me. Thanks!

**Comment by s-u** [comment]
If you have any of these issues, please try rJava 0.9-8, it tries to address most issues involved - the stub bug as well as the fact that Oracle Java doesn't contain paths and OS X strips `DYLD_FALLBACK_LIBRARY_PATH` when passing from `R` to the build script.

**Comment by rodrigomurta** [comment]
I still have problem to make rJava recognise Java 8 in OSX 10.11. I tried to install version 0.9-8, but I get:
`checking JNI data types... configure: error: One or more JNI types differ from the corresponding native type. You may need to use non-standard compiler flags or a different compiler in order to fix this.`
I tried this SE post [rJava package install failing](http://stackoverflow.com/questions/3311940/r-rjava-package-install-failing), without success.

**Comment by kingo55** [comment]
@rodrigomurta - I've tried this too. Looks to be another Java issue with rebuilding.

Can we compile R packages outside of R? Have no troubles accessing 1.8.0 outside of R....

**Comment by jirutka** [comment]
I wrote an user friendly script for this hack with relinking rJava.so against specific Java VM: https://gist.github.com/jirutka/ab8ccaf40e10773cb17f

**Comment by s-u** [comment]
Please don't use any "hacks" like the above - they are pointless with Java 1.8, because the linked path is ignored. As mentioned above, please use rJava 0.9-8 which work around the issues both in Oracle Java and in most recent OS X versions.

**Comment by jirutka** [comment]
rJava version has been bumped to 0.9-8 ~2 months ago in this repo, so why the heck it's still not on CRAN?! Well, it's my fault that I didn't double check the installed version, but still...

**Comment by jirutka** [comment]
I disagree that it's pointless, it obviously isn't since it solved the problem for me and friend of mine. It's nasty hack, but the only way that actually worked.

**Comment by tatsujb** [comment]
is there any solution that does not involve installing Apple's java 6?

**Comment by mottelet** [comment]
> is there any solution that does not involve installing Apple's java 6?

Yeah, you just have to modify the Info.plist of Oracle jdk  : https://derflounder.wordpress.com/2015/08/08/modifying-oracles-java-sdk-to-run-java-applications-on-os-x/
