### ISSUE TITLE
Unable to load ZIP library

### ISSUE THREAD

**Issue by xieguigang** [s-u/rJava#38]
Hi, i need some help about using rJava to initialize the Java:

I have a problem about using rJava on 64bit Win8, when i using the rJava try to initialize the Java, the R engine throw me an exception: 
This exception comes from the jinit function, 

.jinit()

"Unable to load ZIP library: C:\Program Files\Java\jre7\bin\zip.dll"

i'm not sure about this problem, because the rJava program works fine on 32bit win7 but not works on 64bit win7 and win8. i dont know why. I have just reinstall my windows operating system today, and try run the r program again, it still running into this error.........

 

$  call genome_reprogramming_analysis
\<Imports Namespace> 'pfsnet.footprint_pathway'
\<Imports Namespace> 'io_device.csv'
\<Imports Namespace> 'gcmodeller.compiler.csv_tabular'
\<Imports Namespace> 'pfsnet'
    = [0] C:\meme_data\12.21_FOOTPRINT_PATHWAYS\xcb_model\trunk\WT.MonteCarlo\s_ExpressionMatrix.csv
[DEBUG] CSV data "C:\meme_data\12.21_FOOTPRINT_PATHWAYS\xcb_model\trunk\WT.MonteCarlo\s_ExpressionMatrix.csv" load done!   867ms.
Try to start the Java VMs...
Error occurred during initialization of VM
Unable to load ZIP library: C:\Program Files\Java\jre7\bin\zip.dll

![image](https://cloud.githubusercontent.com/assets/9410171/5558046/6f624f36-8ccc-11e4-8ae8-6fa4d801260d.png)

**Comment by s-u** [comment]
Make sure you use 64-bit R with 64-bit Java. If in doubt, re-install Java and make sure you do NOT set `JAVA_HOME`.
