### ISSUE TITLE
.jsimplify fails to convert minimal Integer value

### ISSUE THREAD

**Issue by vlevkevich** [s-u/rJava#39]
Hi,

Converting Java integer with minimal possible value (-2147483648) to R returns NA instead of the correct value:
> value
[1] "Java-Object{-2147483648}"
> .jsimplify(value)
[1] NA

Environment:
Ubuntu 14.04 64 bit
R version 3.0.2 (2013-09-25)
rJava version 0.9-6
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

**Comment by s-u** [comment]
-2147483648 is the representation of `NA` in R, so there is no way to represent that number as integer in R, it has to be passed as `double`. Similarly, `NA_integer_` when passed to Java as an integer has that value. Therefore it's impossible to distinguish `NA`s from -2147483648 and it's not well defined what the result would be --- a choice has to be made either way.

Given the ambiguity I have added `promote=TRUE` option to `.jsimplify()` which allows type promotion in that case:

    > i <- .jnew("java/lang/Integer", NA_integer_)
    > .jsimplify(i)
    [1] NA
    > .jsimplify(i, promote=TRUE)
    [1] -2147483648

**Comment by vlevkevich** [comment]
Thanks for the quick problem resolution!
Does also it work with -2147483648 in arrays?

**Comment by s-u** [comment]
No, `.jsimplify()` is only for scalars. I guess something similar could be added to `.jevalArray()` - it's slightly more complicated, because it would have to check if any of the values is -2147483648 first, but doable - I guess a good idea for symmetry.
