### ISSUE TITLE
.jarray does not create an array of shorts

### ISSUE THREAD

**Issue by vlevkevich** [s-u/rJava#40]
How to create a java array of shorts? The .jarray method returns array of integers, even if the type is specified:
> data = c(1,2,3,4)
> .jarray(.jshort(data))
[1] "Java-Array-Object[I:[I@4cd4aaf6"
> .jarray(.jshort(data), "[S")
[1] "Java-Array-Object[I:[I@1e2423e2"

The same code for long values works perfectly:
> .jarray(.jlong(data))
[1] "Java-Array-Object[J:[J@3309f28b"

What am I doing wrong?

**Comment by s-u** [comment]
Thanks, nothing, that branch was simply not implemented, now fixed.

```r
> data = c(1,2,3,4)
> .jarray(.jshort(data))
[1] "Java-Array-Object[S:[S@4b67cf4d"
```
