### ISSUE TITLE
R Studio crashes when installing rJava Package

### ISSUE THREAD

**Issue by JLBescos** [s-u/rJava#41]
Java 1.70_76-b13
Mac OS Yosemite 10.10.2
R Studio 0.98.10.91
When loading the rJava library it produces a fatal error saying that  RStudio needs an older version of Java execution runtime: SE 6. As I have other applications requiring SE 7, I don't want to come back to the older Java Runtime . Any idea about how to overcome this? Thanks in advance
JB

**Comment by s-u** [comment]
This is a bug in Oracle's Java - see #37 for full discussion - installing 1.6 is required although it is not actually used.
