### ISSUE TITLE
Running rJava from JRI in JBoss application server

### ISSUE THREAD

**Issue by pgschr** [s-u/rJava#44]
I'm running an R script in Jboss (a java application server) using JRI. Within the R script I have a call to a Java class.

Therefore, this is what I have:

Java program in JBoss --> invokes JRI and runs R script --> invokes Java program.

When I attempt to run the following script in JRI (or instantiate any class from rJava):

```
s <- .jnew("java/lang/String", "Hello World")
```

The object is created, however Java throws the following exception:

22:18:29,973 ERROR [stderr](http-localhost-127.0.0.1-8080-1) java.lang.NoClassDefFoundError: RJavaClassLoader

22:18:29,973 ERROR [stderr](http-localhost-127.0.0.1-8080-1)   at org.rosuda.JRI.Rengine.rniEval(Native Method)

22:18:29,973 ERROR [stderr](http-localhost-127.0.0.1-8080-1)   at org.rosuda.REngine.JRI.JRIEngine.eval(JRIEngine.java:281)

22:18:29,973 ERROR [stderr](http-localhost-127.0.0.1-8080-1)   at org.rosuda.REngine.REngine.parseAndEval(REngine.java:102)

22:18:29,973 ERROR [stderr](http-localhost-127.0.0.1-8080-1)   at org.rosuda.REngine.REngine.parseAndEval(REngine.java:108)

Even though the exception is thrown, I can continue executing other statements, for example:

```
print(s) 
```

will execute correctly.

The first time I run **any** rJava statement, I get the exception. 

I know that is possible to run rJava from within JRI, but is it possible in an application server like Jboss instead of a plain Java object? rJava would need to have access to Jboss' JVM.

**Comment by philipp94831** [comment]
@pgschr Same problem here, any solution yet?

**Comment by s-u** [comment]
How did you instantiate the JNI binding? Do you have example code? It seems like your embedded Java doesn't have the correct class paths set.

**Comment by s-u** [comment]
To elaborate in case it is not obvious: since you're loading rJava into an existing JVM, rJava cannot set the class path and java library path accordingly because it's too late, hence whoever instantiates the JVM is responsible for doing that - I presume JBoss here.

**Comment by philipp94831** [comment]
@s-u Okay, so how to set class path manually in jboss?

**Comment by s-u** [comment]
Well, I don't support JBoss (neither do I use it) so I'm the wrong person to ask. Please refer to the JBoss docs. Since you are already somehow registering the JRI JARs in your app anyway, you should simply include the rJava piece as well - at the very least you need to add the contents of `rJava/java/boot` but it b necessary to add `rJava/java` too, since your classes may be loaded by JBoss instead of the rJava class loader.

**Comment by philipp94831** [comment]
Okay, thanks, I just wanted to know which folders to include :) this already seems very helpful and I will try it asap

**Comment by philipp94831** [comment]
@pgschr I managed to solve the problem by packing either

1. placing the contents of `rJava/java/boot` in my `WEB-INF/classes` folder in `jboss/standalone/deployments`
2. or placing a jar with the contents of `rJava/java/boot` in one of my deployed modules
