### ISSUE TITLE
Rengine or JRIEngine

### ISSUE THREAD

**Issue by colomb001** [s-u/rJava#46]
When interacting with R through java, should I be using org.rosuda.JRI.Rengine or org.rosuda.REngine? The examples in the rJava folder use Rengine, but closed issue #12 references REngine.engineForClass(...) for best practices when creating REngines.

Thanks

**Comment by s-u** [comment]
`JRI.Rengine` is the low-level API. It is recommended to use the high-level API in `org.rosuda.REngine` which supports multiple engines, unless you have a some very specific reason why you need low-level access (which should be very rare).
