### ISSUE TITLE
Can't find local class since R 3.2.0

### ISSUE THREAD

**Issue by piccolbo** [s-u/rJava#47]
Hi
I installed rJava on Yosemite following these instructions
http://andrewgoldstone.com/blog/2015/02/03/rjava/

which means I have both Oracle java 1.8 and the apple version, 1.6. Everything worked until I installed R 3.2. Now jfindClass doesn't find a class that I know is there (because it did work and because I checked with jar) It appears rJava is picking up 1.6

```
J("java.lang.System")$getProperty("java.version")
[1] "1.6.0_65"
```

This is unexpected. Installing 1.6 was supposed to be a workaround for a 1.8 bug, but it should be using the more recent version.
I did a javareconf, but it doesn't solve the issue. I tried to build rJava from source, but it can't find javac. It seems like there is an additional "jre" in the path it is using to access javac. java and javac are on the search path (1.8 version). If I change java home, I can get the build past the javac problem, but then it fails with "One or more JNI types differ from the corresponding native type. You may need to use non-standard compiler flags or a different compiler in order to fix this."

The rub is that to reproduce the process that worked, I need to uninstall the second java I installed. Opinions on how to achieve that are many.  Any suggestions?

**Comment by s-u** [comment]
Check `config.log` - it will show the error, but it seems that your environment is configured badly and/or your Java runtime is broken. First, don't even try installing within RStudio - it messes things up, so use R instead. There is no need to set any extra `DYLD_*` variables, if your Java environment is correct. It worked for me out of the box, no need to set any environment variables at all.

FWIW: this is what I see:

```
$ R CMD javareconf 
Java interpreter : /usr/bin/java
Java version     : 1.8.0_20
Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar
Non-system Java on OS X

trying to compile and link a JNI program 
detected JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
detected JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/../include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/../include/darwin -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c conftest.c -o conftest.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o conftest.so conftest.o -L/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/server -ljvm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation


JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre
Java library path: $(JAVA_HOME)/lib/server
JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
Updating Java configuration in /Library/Frameworks/R.framework/Resources
Done.
```

Then

```r
> install.packages("rJava",type='source')
> library(rJava)
> .jinit()
> J("java.lang.System")$getProperty("java.version")
[1] "1.8.0_20"
```

Make sure you have properly installed Oracle Java framework:

```
$ otool -L /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/server/libjvm.dylib
/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/server/libjvm.dylib:
	/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/server/libjvm.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 52.0.0)
```

**Comment by piccolbo** [comment]
Thanks. What seemed to make a difference was (not that I know why) was to use R CMD javareconf -e and work in the shell from there (start R, install from source, per  your instructions). I still need the DYLIB trick, so I have some problem in my java (independent of RStudio). Unfortunately, I can only download and click, so not a lot of leverage there. But in the end I am up and running, thanks.

**Comment by s-u** [comment]
If you have to use `-e` then you simply don't have permissions to update the config file in `R_HOME`. If you need to use `DYLD_*` then check the ID of the `libjvm` library - it may be missing the path.
