### ISSUE TITLE
R call Java Error (which new REngine in Java)

### ISSUE THREAD

**Issue by webperf** [s-u/rJava#54]
I could call R from Java and call Java function from R successfully both. 
However, when I'm trying to use rJava JRI to call Java from R, and Java code instance new REngine. It failed reports 
R is already initialized
and then quit R directly. 

My class:
public class testRJava {
    public void testOK(){
        System.out.println("test this funciton could be called OK");
    }
    public void callSample(){
        Rengine re = Rengine.getMainEngine();
        if(re == null){
            re=new Rengine (new String [] {"--vanilla"}, false, null);
            if (!re.waitForR())
            {
                System.out.println ("Cannot load R");
                return;
            }
        }
        // print a random number from uniform distribution
        System.out.println (re.eval ("runif(100)").asDouble());
        re.end();
    }
}

then, I call the Jar from R 

> b <- .jnew("testRJava")
> b$testOK()
test this funciton could be called OK
> b$
b$callSample()  b$main(         b$wait()        b$toString()    b$getClass()    b$notifyAll()
b$testOK()      b$wait(         b$equals(       b$hashCode()    b$notify()
> b$callSample()
R is already initialized
[root@ home]#

Do you know why? Any solution about this error ?

**Comment by s-u** [comment]
You have to setup the engine on the R end vis `.jengine(TRUE)` if you want to use it:

```r
> library(rJava)
> .jinit(".")
> .jengine(TRUE)
[1] "Java-Object{Thread[Thread-0,5,main]}"
> b <- .jnew("testRJava")
> b$callSample()
0.7860610249917954
```

**Comment by webperf** [comment]
Hi, s-u, Could you please explain why .jengine is needed in R call Java call R case, while doesnot need to set TRUE in either java call R or R call Java case

**Comment by webperf** [comment]
One more question, I'm recently reading rJava source codes, and a little confused about below questions, could you tell me are they right?
1. Each REngine is called by a Java thread in JRI, and Each REngine will initilize one R process in backend, which means if we new multiple REngine from Java in JVM, multiple R process will be started from JVM. 
2. Luckily, we can reuse existing REngine by setting up the callback for Java into R, which means only one R process is needed instead of multiple R process. One R engine is started to execute many steps as my code above. 
3. If my understand of step 2 is right, could you explain how the below code is executed. 
  def callRDD(sc:SparkContext,input:String,output:String): Unit ={
    System.out.println("Start call RDD function")
    var re: Rengine = Rengine.getMainEngine()
    if(re == null){
      re = new Rengine(Array[String]("--vanilla"), false, null)
      if (!re.waitForR) {
        System.out.println("Cannot load R")
        return
      }
    }

    println("Start read text file")
    val dataRDD=sc.textFile(input,2).map(_.split(",").map(_.toDouble)).map{xr=>
      re.assign("x",xr)
      val result:REXP = re.eval("(sum(x))")
      println("lines " + result.asDouble())
      result.asDouble()
    }
    dataRDD.repartition(1).saveAsTextFile(output)
    re.end
  }
As we know, only one R process is started at first, and the call eval in map procedure by Spark.  Is each map start a R process? or it just reuse existing R process. But there is no thread in R, are them executed in sequential or parallelization? what kind of parallelization? Thread level or process level ? 
many thanks.
