### ISSUE TITLE
runjdwp parameter not affecting JVM

### ISSUE THREAD

**Issue by AidanDelaney** [s-u/rJava#58]
Hi,
If you  set the options as follows

```R
options(java.parameters = "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address='8000'")
```

then I would expect the debug and runjdwp options to be passed to the underlying JVM in the .jinit call.  However, the parameters do not seem to launch the underlying JVM in debug mode and suspended.

There's no obvious cause for this error in the rJava codebase.  Maybe it's just me setting the parameters incorrectly.  However, printing the contents of &vm_args in the call to JNI_CreateJavaVM on line 143 of init.c might shine some light on the issue.

**Comment by s-u** [comment]
I think what you actually wanted to pass is

```r
.jinit(parameters=c("-Xdebug","-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000"))
```
since `-Xdebug` and `-Xrunjdwp` are two separate parameters to the JVM (and BTW the port is an integer, not a string).
