### ISSUE TITLE
TwitteR and JRI

### ISSUE THREAD

**Issue by WeimusT** [s-u/rJava#61]
Hi I am having an issue to get JRI to work with TwitteR. I also posted this issue on TwitteR issues board but I also post it here to get some suggestions/ideas from the JRI side. Many thanks. 

I am doing a side Java project using JRI and twitteR to generate wordcloud using tweets. Since my R script is executed in a Java environment so JRI is used.

But JRI crashes with warning messages:

JRI Warning: jriReadConsole detected a possible deadlock [org.rosuda.JRI.Mutex@20ed2dc[locked, by current thread]][Thread[qtp584131341-43,5,main]]. Proceeding without lock, but this is inherently unsafe.

Previously when the old twitter oauth setup functions, OAuthFactor and registerTwitterOAuth, were used, my project worked and the wordcloud was generated. But recently I picked this project up again and used the new OAuth setup function: setup_twitter_oauth, but JRI fails w/ warning messages given above. Because only the authentication setup part of the R script was changed, I guess it appears to be that JRI is incompatible with the setup_twitter_oauth function in JRI. 

Anyone has any thoughts on this issue? Thanks a million.

**Comment by rafaleo** [comment]
I have also the issue with `wordcloud` in `JRI`. Using Eclipse and evaluating the simple code all results are just blank pages while in R it works properly. 

Example:
```

 /** R library for this task */ 
	        engine.eval("library(wordcloud)");
	        
	        /** Plot to a file */
	        engine.eval("enf_df <- data.frame(word = names(enf), freq = unname(enf), stringsAsFactors = F)");
	        engine.eval("png(filename = 'plots/en_wordcloud.png')");
	        engine.eval("wordcloud(enf_df$word, enf_df$freq.Freq, random.order = F, colors = brewer.pal(7, 'Dark'), scale = c(3, 0.5), min.freq = 30)");
	        engine.eval("dev.off()");
```
	       
I also tried `wordcloud2` but it's the same result. Can't find the source of this error. Any plots, clustplots, etc. in my program work well.
