### ISSUE TITLE
JInit NoClassDefoundError

### ISSUE THREAD

**Issue by mitchum20** [s-u/rJava#62]
Hallo guys,
I am using R 3.2.0 and rJava 0.97

When I am starting .jinit() the following error appears:
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

Any idea ?

best regards, Mike

**Comment by s-u** [comment]
That is indeed interesting - it appears that Java can't even load the most basic classes. Can you post your exact setup, i.e. OS, how you configured R (`R CMD javareconf`) and Java version? Do you have multiple Java versions on your system? Do you set `JAVA_HOME` (not recommended!)?

**Comment by s-u** [comment]
No feedback
