### ISSUE TITLE
Update DESCRIPTION

### ISSUE THREAD

**Issue by jakob-r** [s-u/rJava#64]
Sorry for bothering again, but the DESCRIPTION File should be updated for real. I have seen the PR #34  - but it's a bit outdated. Especially the version number is important since I now get the latest version from github but to compile it with `--disable-Xrs` but in the later process it updates again to the "newer" cran version so that it will crash again.

**Comment by s-u** [comment]
It means you're installing it incorrectly - you are apparently not installing from the correct tar ball. The recommended way is to use

    install.packages("rJava",,"http://rforge.net")

and if you want to install it from the checkout you must use `mkdist` to create the distribution tar ball. The GH checkout is *not* a valid package - you *must* run the distribution script to create the package.

**Comment by s-u** [comment]
I have added `README.md` to make sure those instructions are clear.
