### ISSUE TITLE
JRI: Get byte array from R raw vector

### ISSUE THREAD

**Issue by kenahoo** [s-u/rJava#66]
I have an R method that produces an object that I'd like to use Java to store somewhere (maybe filesystem, HBase, S3, etc.).  For that, I'd like to get a Java byte array from the R return value, using something like R's `serialize(x, NULL)`.

It looks like `org.rosuda.REngine.REXP` has an `asBytes()` method that would work well.  However, `Rengine.eval(String)` returns a `org.rosuda.JRI.REXP` object, for which there's no `asBytes()` method.

Is there a way to coerce one REXP type to the other?  Or a different workaround?

**Comment by s-u** [comment]
You're mixing two different API - the recommended way is to use the  `org.rosuda.REngine` API (in your case using `JRIEngine` as the engine) and thus just call `parseAndEval()` which gives you the `org.rosuda.REngine.REXP` that you want.

Only legacy applications should be using the long deprecated `org.rosuda.JRI` API directly and, yes, that API has not supported raw vectors (other than using `rniGetRawArray()`).

**Comment by kenahoo** [comment]
Thanks.  I was unaware the `org.rosuda.JRI` API was deprecated.  I don't see any deprecation notices in those classes in the Javadoc at http://rforge.net/org/docs/ , is that documentation up to date?

**Comment by s-u** [comment]
Yes, the API is internal, so the classes are not deprecated individually, the entire API is in favor of REngine.
