### ISSUE TITLE
Installation of rJava package-reg.

### ISSUE THREAD

**Issue by bappa10085** [s-u/rJava#72]
I am trying to install rJava package using "install.packages("rJava",,'http://rforge.net/',type='source')" code. But I have failed to install it. Please help me to install rJava. I am using 32 bit Windows.
![image](https://cloud.githubusercontent.com/assets/17943205/14076067/1b3e2206-f4fc-11e5-91f7-0fc4ad49de91.png)

**Comment by s-u** [comment]
Ir seems that you don't even have basic tools installed. Unless you know what you're doing, please use released version from CRAN (see basic R documentation on installing packages).

**Comment by bappa10085** [comment]
I am using **rattle** package. When I am executing _distribution _, I am getting this error
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/govind/Documents/R/R-3.2.2/library/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  The specified module could not be found.
How to fix this problem.
![image](https://cloud.githubusercontent.com/assets/17943205/14100009/cd7e91ac-f5a7-11e5-808e-9c90277f4f01.png)

**Comment by s-u** [comment]
Make sure you have 32-bit Java installed in your system since you're using 32-bit R.

**Comment by bappa10085** [comment]
I have copied "jvm.dll" from the directory "C:\Program Files\Java\jre1.8.0_77\bin\client" and paste it to "C:\Users\govind\Documents\R\R-3.2.2\bin\i386" and "C:\Users\govind\Documents\R\R-3.2.2\library\rJava\libs\i386" directory. This has solved my problem.
