### ISSUE TITLE
Can rJava call Scala function with default parameter value?

### ISSUE THREAD

**Issue by xliuqq** [s-u/rJava#73]
a simple scala function with default parameter value :

class Test {
  def func(a:Int, b:Double = 2.0):Double  = {
    a + b
  }
}
In R terminal: 
   a <- .jnew("Test")
then a has two method : a$func and  a$func$default$2
How can I call the second method?

**Comment by s-u** [comment]
> .jcall(a, "D", "func$default$2")
    [1] 2

or

    > a$`func$default$2`()
    [1] 2
