### ISSUE TITLE
HeadlessException when trying to create a JFrame

### ISSUE THREAD

**Issue by blernermhc** [s-u/rJava#77]
When I execute the code shown on the help page for .jnew to create a JFrame, I get a HeadlessException.
```
> library(rJava)
> .jinit()
> f <- .jnew("java.awt.Frame", "Hello")
Error in .jnew("java.awt.Frame", "Hello") : java.awt.HeadlessException
```
I am using rJava 0.9-8, R 3.2.3 on a Mac running OSX 10.10.5.

rJava seems to be using 1.6 even though the current version of Java is  1.8:
```
> .jcall("java/lang/System", "S", "getProperty", "java.version")
[1] "1.6.0_65"
```
In the shell:
```
~ -> java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
```

I would really appreciate help with this.

**Comment by s-u** [comment]
Java on OSX doesn't support single-threaded operation for AWT, so you can only run it headless unless you run R on a separate thread (e.g., if you use [JGR](https://www.rforge.net/JGR/)).
