### ISSUE TITLE
.jarray creates wrong JNI signature for multidimensional string array

### ISSUE THREAD

**Issue by floidgilbert** [s-u/rJava#81]
I am building an R package that imports rJava and I ran across a bug in .jarray that affects .jcall. Specifically, .jcall fails when the target method expects a multidimensional string array and .jarray is used to build up the array.

The declaration for the Java method I call is:

`void put(String key, String[][] value)`

The following R code throws an error:

```
key <- "a"
m <- .jarray(matrix(letters, 13, 2), dispatch = TRUE)
.jcall(obj, "V", "put", key, m)
```

```
Error in .jcall(controller, "V", "put", "identifier",  : 
  method put with signature (Ljava/lang/String;[[Ljava.lang.String;)V not found
```

The JNI signature in the error is wrong (dots not slashes). When I change the last line in .jarray from

`new("jrectRef", jobj = r, dimension = dim, jclass = clazz, jsig = tojni(clazz))`

to

`new("jrectRef", jobj = r, dimension = dim, jclass = tojni(clazz), jsig = tojni(clazz))`

the error clears.

Let me know if you need any more information.

Thank you for writing the rJava the package. I am finding it very useful.

**Comment by s-u** [comment]
Thanks!
