### ISSUE TITLE
Java debugging -> abort

### ISSUE THREAD

**Issue by kapelner** [s-u/rJava#84]
Hi Simon,

Long time user here - bartMachine maintainer - now shooting for another machine learning package with rJava.

I would like to use debugging features as printing to console within Java within R is hit or miss.

However when I run

```
> options(java.parameters = c("-Xmx3000m", "-Xdebug", "-Xrunjdwp:server=y,transport=dt_socket,address=8000"))
> library(rJava)
> .jinit()
```

I'm getting the following:

```
JDWP exit error AGENT_ERROR_ILLEGAL_ARGUMENT(202): saveGlobalRef obj [util.c:60]
FATAL ERROR in native method: JDWP saveGlobalRef obj, jvmtiError=AGENT_ERROR_ILLEGAL_ARGUMENT(202)
Abort trap: 6
```

Is using debugging tools not allowed from rJava? Any other strategy?

I'm on Java 1.8.0_101-b13 and rJava 0.9-9 installed from source and Mac OS 10.11.4.

Adam

**Comment by s-u** [comment]
Sorry, you'll have to consult Java documentation - the above comes from your JVM, not rJava. rJava just instantiates the JVM with whatever arguments you give it, it's just a pass-through, so it's between you and the JVM - Oracle folks may help you with that that means.
