### ISSUE TITLE
Using the rJava package on Win7 64 bit with R

### ISSUE THREAD

**Issue by englianhu** [s-u/rJava#85]
I faced same issue with [Using the rJava package on Win7 64 bit with R](http://stackoverflow.com/questions/7019912/using-the-rjava-package-on-win7-64-bit-with-r), Java

```diff
> Sys.getenv("JAVA_HOME")
[1] "C:\\Program Files\\Java\\jre1.8.0_102;C:\\Program Files\\Java\\jre1.8.0_102\\bin;C:\\Program Files\\Java\\jre1.8.0_102\\bin\\server"
> library(shiny)
> library(AER)
> library(ReporteRs)
Loading required package: ReporteRsjars
- Error : .onLoad failed in loadNamespace() for 'rJava', details:
-   call: inDL(x, as.logical(local), as.logical(now), ...)
-   error: unable to load shared object 'C:/Users/scibr/Documents/R/win-library/3.3/rJava/libs/x64/rJava.dll':
-   LoadLibrary failure:  The specified module could not be found.

- Error: package `ReporteRsjars`could not be loaded
```
Below is the info of my system.
```
> devtools::session_info()$platform
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.1130)         
 language (EN)                        
 collate  English_United States.1252  
 tz       Asia/Tokyo                  
 date     2016-08-26
```

**Comment by englianhu** [comment]
rJava, the R<->Java bridge, will need jvm.dll, but R will have trouble finding that DLL. It resides in a folder like`C:\Program Files\Java\jdk1.6.0_25\jre\bin\server` or `C:\Program Files\Java\jre6\jre\bin\client`.

Above solution doesn't work for me, and I tried below codes, its work for me. the source of answer from [here](http://stackoverflow.com/a/15998358/3806250).
```
> Sys.getenv("JAVA_HOME")
[1] "C:\\Program Files\\Java\\jre1.8.0_102;C:\\Program Files\\Java\\jre1.8.0_102\\bin;C:\\Program Files\\Java\\jre1.8.0_102\\bin\\server"
> if (Sys.getenv("JAVA_HOME")!="")
+     Sys.setenv(JAVA_HOME="")
> library(rJava)
> library(shiny)
> library(AER)
> library(ReporteRs)
Loading required package: ReporteRsjars
```

**Comment by raedkm** [comment]
I hade a simliar error regarding java with "rJava" and "xlsx
`> library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/Raed/Documents/R/win-library/3.6/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  The specified module could not be found.`

`> library(xlsx)
Error: package or namespace load failed for ‘xlsx’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/Raed/Documents/R/win-library/3.6/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  The specified module could not be found.`

The solution you provided worked.

Thanks!
