### ISSUE TITLE
rJava on OSX 10.11.6

### ISSUE THREAD

**Issue by cezden** [s-u/rJava#86]
I guess the problem is well-known, yet I couldn't find the clear solution.

After the:
- OS X update, 
- reinstallation of R 3.3.1, 
- reinstallation of Oracle JDK 1.8 (build 1.8.0_102-b14), 
- R reconfiguration (sudo R CMD javareconf) 

I'm trying to install the newest rJava_0.9-9 (2016-06-27 18:29).

My system-specific configuration is following:
- R usage on non-sudo account
- no legacy Java 1.6 installed (only Oracle JDK 8)

On the "sudo" account: 
- the installation of rJava works only on sudoed R
- the library(rJava) works only on sudoed R
- the non-sudoed R fails to load rJava (Library not loaded: @rpath/libjvm.dylib)

On non-sudoed R both installation and loading fail.

Since it "almost" works, I've performed a './configure' and 'sudo ./configure' and found some configuration differences in config.log, which I hope will help the Darwinians ;) get the smooth rJava installation:
- DEFS='-DHAVE_CONFIG_H'    vs     DEFS=''
- JAVA_HOME: 
  JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre'
  JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home'
- WANT_JRI_FALSE='#'    vs    WANT_JRI_FALSE=''
- exec_prefix='${prefix}'    vs   exec_prefix='NONE'
- prefix='/usr/local'   vs    prefix='NONE'
- subdirs=' jri'    vs   subdirs=''
- only in 'working':   #define USE_HEADLESS_INIT 1

The exact diff below:

diff <blah>/sudo/rJava/config.log <blah>/nosudo/rJava/config.log:

276,315c276,316
< configure:3820: $? = 0
< configure:3821: result: ok
< configure:3832: checking whether JRI should be compiled (autodetect)
< configure:3834: result: yes
< configure:3847: checking whether debugging output should be enabled
< configure:3854: result: no
< configure:3858: checking whether memory profiling is desired
< configure:3870: result: no
< configure:3882: checking whether threads support is requested
< configure:3900: result: no
< configure:3905: checking whether callbacks support is requested
< configure:3917: result: no
< configure:3921: checking whether JNI cache support is requested
< configure:3933: result: no
< configure:3937: checking whether headless init is enabled
< configure:3946: result: yes
< configure:3954: checking whether JRI is requested
< configure:3957: result: yes
< configure:4123: creating ./config.status
< 
< ## ---------------------- ##
< ## Running config.status. ##
< ## ---------------------- ##
< 
< This file was extended by rJava config.status 0.8, which was
< generated by GNU Autoconf 2.69.  Invocation command line was
< 
<   CONFIG_FILES    = 
<   CONFIG_HEADERS  = 
<   CONFIG_LINKS    = 
<   CONFIG_COMMANDS = 
<   $ ./config.status 
< 
< on -MacBook-Pro.local
< 
< config.status:820: creating src/Makevars
< config.status:820: creating R/zzz.R
< config.status:820: creating src/config.h
< configure:5348: === configuring in jri (/Users/_/tmp/sudo/rJava/jri)
## < configure:5411: running /bin/sh ./configure --disable-option-checking '--prefix=/usr/local'  --cache-file=/dev/null --srcdir=.

> dyld: Library not loaded: @rpath/libjvm.dylib
>   Referenced from: /Users/_/tmp/nosudo/rJava/./conftest
>   Reason: image not found
> ./configure: line 1529: 50865 Trace/BPT trap: 5       ./conftest$ac_exeext
> configure:3820: $? = 133
> configure: program exited with status 133
> configure: failed program was:
> | /\* confdefs.h _/
> | #define PACKAGE_NAME "rJava"
> | #define PACKAGE_TARNAME "rjava"
> | #define PACKAGE_VERSION "0.8"
> | #define PACKAGE_STRING "rJava 0.8"
> | #define PACKAGE_BUGREPORT "Simon.Urbanek@r-project.org"
> | #define PACKAGE_URL ""
> | #define STDC_HEADERS 1
> | #define HAVE_SYS_WAIT_H 1
> | #define HAVE_SYS_TYPES_H 1
> | #define HAVE_SYS_STAT_H 1
> | #define HAVE_STDLIB_H 1
> | #define HAVE_STRING_H 1
> | #define HAVE_MEMORY_H 1
> | #define HAVE_STRINGS_H 1
> | #define HAVE_INTTYPES_H 1
> | #define HAVE_STDINT_H 1
> | #define HAVE_UNISTD_H 1
> | #define HAVE_STRING_H 1
> | #define HAVE_SYS_TIME_H 1
> | #define HAVE_UNISTD_H 1
> | #define TIME_WITH_SYS_TIME 1
> | #define HAVE_STATIC_INLINE 1
> | #define HAVE_DECL_SIGSETJMP 1
> | #define HAVE_DECL_SIGLONGJMP 1
> | #define HAVE_POSIX_SETJMP 1
> | /_ end confdefs.h.  */
> | 
> | #include <jni.h>
> | int main(void) {
> |   return (sizeof(int)==sizeof(jint) && sizeof(long)==sizeof(long) && sizeof(jbyte)==sizeof(char) && sizeof(jshort)==sizeof(short) && sizeof(jfloat)==sizeof(float) && sizeof(jdouble)==sizeof(double))?0:1;
> | }
> | 
> configure:3824: error: One or more JNI types differ from the corresponding native type. You may need to use non-standard compiler flags or a different compiler in order to fix this.
> 373c374
> ## < DEFS='-DHAVE_CONFIG_H'
> 
> DEFS=''
> 384c385
> ## < JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre'
> 
> JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home'
> 400c401
> ## < WANT_JRI_FALSE='#'
> 
> WANT_JRI_FALSE=''
> 409c410
> ## < exec_prefix='${prefix}'
> 
> exec_prefix='NONE'
> 421c422
> ## < prefix='/usr/local'
> 
> prefix='NONE'
> 426c427
> ## < subdirs=' jri'
> 
> subdirs=''
> 460d460
> < #define USE_HEADLESS_INIT 1
> 462c462
> ## < configure: exit 0
> 
> configure: exit 133

**Comment by cezden** [comment]
And the winning configuration (in my case) is:

export JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre'
(JAVA_HOME='/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home', although reported by /usr/libexec/java_home is BAD for rJava 0_9-9)

It allows for the successful load of the rJava package.

I'd like to thank The Development Team (@s-u) for the very useful package.

**Comment by gwarnes-mdsol** [comment]
This path is version-specific.  To ensure that the correct value is set, use `java_home` to obtain the current path:

# Set JAVA_HOME so rJava package can find it
export JAVA_HOME=$(/usr/libexec/java_home)/jre

**Comment by gwarnes-mdsol** [comment]
**This is how I configured it working properly on both my MacBookPro and my MacPro under Mac OS X El Capitan (10.11.6):**

1.  Download and install the Java software from Oracle:  https://www.java.com/en/download/mac_download.jsp 
2. Add the following lines to `/Users/<userid>/.bashrc`:

    ```
# Set JAVA_HOME so rJava package can find it
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)/jre
   ```
3. Close and restart any terminal, R, and RStudio windows (to pick up the changes to `.bashrc`).
4. Run the following command in a Terminal window:

    ```
sudo ln -sf $(/usr/libexec/java_home)/jre/lib/server/libjvm.dylib /usr/local/lib
    ```
5. Run the following command in a new R session: 

    ```
install.packages("rJava", repos="http://rforge.net", type="source")
    ```

**Comment by bjxiaowanzi** [comment]
@gwarnes-mdsol Thanks for your tutorial, the problem made me eating nothing in two days!

**Comment by TonyMcode** [comment]
The above did not work for me on MacBook Pro running 10.13.4 using Rstudio Version 1.1.442
There were several warnings generated and then following this error listing:

clang: error: unsupported option '-fopenmp'
make[2]: *** [libjri.jnilib] Error 1
make[1]: *** [src/JRI.jar] Error 2
make: *** [jri] Error 2
ERROR: compilation failed for package ‘rJava’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava’
Warning in install.packages :
  installation of package ‘rJava’ had non-zero exit status

**Comment by s-u** [comment]
@TonyMcode Please read R FAQ - you don't have the right compilers - this has nothing to do with rJava.
