### ISSUE TITLE
Cannot install rJava on Ubuntu 14.04

### ISSUE THREAD

**Issue by woodbomb50** [s-u/rJava#87]
On stackoverflow, Dirk  Eddelbuettel r-sig-debian recommends sudo apt-get install r-cran-rjava. This fails giving the message:
====
warning: [options] bootstrap class path not set in conjunction with -source 1.4
warning: [options] source value 1.4 is obsolete and will be removed in a future release
warning: [options] target value 1.4 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
====
This output has been observed various times as related to the probable cause of failure to compile but I have seen no solution. 
When I try to install from R inside a terminal window using install.packages("rJava") I get the same result.
Finally, per the advice at https://www.rforge.net/rJava/files/, I used install.packages('rJava',,'http://www.rforge.net/') to install try to install from source. Same message. I'd give up except that a number of other packages  depend on rJava and I have no way to bypass them.

**Comment by s-u** [comment]
Those are benign warnings, so your statement is certainly false.

**Comment by enkidu0** [comment]
Actually, I'm fighting against exactly the same four warnings. The package installs, but when I try to load the library I get the following error:

Error: package or namespace load failed for 'rJava':
.onLoad failed in loadNamespace() for 'rJava', details:
call: dyn.load(file, DLLpath = DLLpath, ...)
error: unable to load shared object '...3.4/rJava/libs/rJava.so':
libjvm.so: cannot open shared object file: No such file or directory

Any ideas what could be happening here?

**Comment by s-u** [comment]
The warnings are benign. Your error means that your R is not correctly configured for the Java you're using. Run

    sudo R CMD javareconf

to fix that.

**Comment by enkidu0** [comment]
Thanks for the quick reply. I ran what you said, but still no go. What else can I try?

Thanks for the help!
