### ISSUE TITLE
.jinit() gives me "R session aborted, R encountered a fatal error. The session was terminated"

### ISSUE THREAD

**Issue by danielmedbar** [s-u/rJava#88]
I just do as follows:
`library(rJava)
.jinit()`

And I get the typical "R session aborted" message.
Any ideas on why this could be happening?

Previously I have compiled some java files in the windows CMD console just for testing, and i have a 64 bits pc.

**Comment by PeterNSteinmetz** [comment]
I was receiving a similar error when there was a version mismatch between the DYLD_FALLBACK_LIBRARY_PATH version of the jvm being used and the version used to compile rJava.
