### ISSUE TITLE
Unable to load local Class

### ISSUE THREAD

**Issue by harakiro** [s-u/rJava#9]
When attempting to use cloudera CDH 5.0, hive 0.12 with rJDBC we see the following error:

Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hive.conf.HiveConf$ConfVars

I have validated multiple times that the listed class is indeed in my class path as it is a part of hive-common.jar. You can see the source here:
https://github.com/cloudera/hive/blob/trunk/common/src/java/org/apache/hadoop/hive/conf/HiveConf.java

I'm trying to debug what may be causing this any help would greatly be appreciated.

R environment:
R version 3.0.3 (2014-03-06)
Platform: x86_64-pc-linux-gnu (64-bit) (ubuntu 12.04)
RJDBC_0.2-4 
rJava_0.9-7 
DBI_0.2-7 

R code used:
library(DBI)
library(rJava)
library(RJDBC)

cp <- c(
  "/opt/cloudera/parcels/CDH/lib/hive/lib/libthrift-0.9.0.cloudera.2.jar",
  "/opt/cloudera/parcels/CDH/lib/hive/lib/libfb303-0.9.0.jar",
  "/opt/cloudera/parcels/CDH/lib/hive/lib/hive-service.jar",
  "/opt/cloudera/parcels/CDH/lib/hive/lib/hive-common.jar",
  "/opt/cloudera/parcels/CDH/lib/hive/lib/hive-metastore.jar",
  "/opt/cloudera/parcels/CDH/lib/hive/lib/hive-shims-common.jar",
  "/opt/cloudera/parcels/CDH/lib/hive/lib/hive-shims.jar",
  "/opt/cloudera/parcels/CDH/lib/hive/lib/httpclient-4.2.5.jar",
  "/opt/cloudera/parcels/CDH/lib/hive/lib/httpcore-4.2.5.jar",
  "/opt/cloudera//parcels/CDH/lib/hive/lib/hive-cli.jar",
  "/opt/cloudera//parcels/CDH/lib/hive/lib/hive-contrib.jar",
  "/opt/cloudera//parcels/CDH/lib/hive/lib/hive-beeline.jar",
  "/opt/cloudera//parcels/CDH/lib/hive/lib/hive-jdbc.jar"
  
)

.jinit(classpath=cp)
drv <-JDBC("org.apache.hive.jdbc.HiveDriver", "hive-jdbc.jar", "`")
conn <-dbConnect(drv, "jdbc:hive2://<hiveserver2_host>:10000/default", "hdfs", "hdfs")

**Comment by souravrajiitbbs** [comment]
I am facing the similar issue when try to use RJDBC 0.2-5 to connect to Hiveserver 1 in Rstudio. I got the following error:

Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1], : 
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hive.conf.HiveConf$ConfVars

I verified the above missing class is present in hive-common.jar. I also checked the JVM version and mine is latest one so there should not be any problem.

Now I am wondering why it is throwing exception. Can anyone help me?

I already tried above things but that doesn't solve my problem.

My server has hadoop-2.4.1 and hive-0.14. I follow the below mention steps to connect to Hive.

library(DBI)
library(rJava)
library(RJDBC)
.jinit(parameters="-DrJava.debug=true")
drv <- JDBC("org.apache.hadoop.hive.jdbc.HiveDriver", 
c("/home/packages/hive/New folder3/commons-logging-1.1.3.jar",
"/home/packages/hive/New folder3/hive-jdbc-0.14.0.jar",
"/home/packages/hive/New folder3/hive-metastore-0.14.0.jar",
"/home/packages/hive/New folder3/hive-service-0.14.0.jar",
"/home/packages/hive/New folder3/libfb303-0.9.0.jar",
"/home/packages/hive/New folder3/libthrift-0.9.0.jar",
"/home/packages/hive/New folder3/log4j-1.2.16.jar",
"/home/packages/hive/New folder3/slf4j-api-1.7.5.jar",
"/home/packages/hive/New folder3/slf4j-log4j12-1.7.5.jar",
"/home/packages/hive/New folder3/hive-common-0.14.0.jar",
"/home/packages/hive/New folder3/hadoop-core-0.20.2.jar",
"/home/packages/hive/New folder3/hive-serde-0.14.0.jar",
"/home/packages/hive/New folder3/hadoop-common-2.4.1.jar"),
identifier.quote="`")

conHive <- dbConnect(drv, "jdbc:hive://myserver:10000/default",
"usr",
"pwd")

**Comment by s-u** [comment]
Nothing to do wit rJava - you can ask on the mailing list if you provide details (including the debugging output).
