### ISSUE TITLE
Does it work for OSX 10.12?

### ISSUE THREAD

**Issue by sloth2012** [s-u/rJava#94]
I have tried it in JDK1.8 and R that installed by anaconda. my system is OS X 10.12. I face error like this:
![image](https://cloud.githubusercontent.com/assets/4048815/21923386/cbb2f610-d9ae-11e6-96c5-1eb134beb4fa.png)

since this project hasn't been updated so long time, I wonder if it supports osx 10.12 now?

**Comment by s-u** [comment]
Yes.

Since you're not using official R, please contact your supplier (anaconda) since that error comes from the R distribution, nor rJava.
