### ISSUE TITLE
rJava 0.9-9 uses 1.6 instead of the current Java version

### ISSUE THREAD

**Issue by PedroReyes** [s-u/rJava#95]
How can I set rJava to use Java 1.8? 

The result from this R code:
```
library(rJava)
options(java.home="/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk")
Sys.setenv(DYLD_FALLBACK_LIBRARY_PATH="/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/server/")
.jinit()
print(.jcall("java/lang/System", "S", "getProperty", "java.runtime.version"))
```

returns ```"1.6.0_65-b14-468-11M4833"```.

I have being through all the web pages related to this topic but nothing has worked up to now for me. I have Apple JDK 1.6 installed too and I do not have problems with the installation of rJava 0.9-9 if I use Java 1.6 when wrapping my Java code in a .jar file. The problem is when I use Java code written in JDK 1.8. For example, the code below calls to UmaShock2.jar, that is written in JDK1.8 :
```
library(rJava)
umashockJarPath <- paste(getwd(),"/umashock/java/UmaShock2.jar", sep = "")
init = .jinit(classpath = umashockJarPath, parameters = "-Xmx512m", force.init = FALSE)
class <- .jnew("Test") 
```
The error that I've got is ```"Error: java.lang.UnsupportedClassVersionError: Test : Unsupported major.minor version 52.0"```

I have already tried this command on my terminal and it didn't work:

```sudo R CMD javareconf JAVA_CPPFLAGS="-I/System/Library/Frameworks/JavaVM.framework/Headers -I/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/"```

I have also set the java version to 1.8 as you can see here:

```
MacBook-Pro-de-Pedro-2:~ pedro$ java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)
```

I got no problems with JNI, JAVA_HOME is correctly set, and everything looks fine when re-configurating java:
```
pedro$ sudo R CMD javareconf
Password:
Java interpreter : /usr/bin/java
Java version     : 1.8.0_112
Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar
Non-system Java on macOS

trying to compile and link a JNI program 
detected JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
detected JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/../include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/../include/darwin -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c conftest.c -o conftest.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o conftest.so conftest.o -L/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/server -ljvm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation


JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre
Java library path: $(JAVA_HOME)/lib/server
JNI cpp flags    : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/darwin
JNI linker flags : -L$(JAVA_HOME)/lib/server -ljvm
Updating Java configuration in /Library/Frameworks/R.framework/Resources
Done.

```
PS: Please I desperately need help from you. I really like this package and would like to keep using it because it allows me to interconnect my Java applications and R Shiny code perfectly (https://shiny.rstudio.com/).

**Comment by s-u** [comment]
Have you re-compiled rJava after re-configuring R?

**Comment by PedroReyes** [comment]
Not, I didn't. After your comment I typed this in my R console for checking where my packages are: ``` .libPaths() ``` and I've got ```"/Library/Frameworks/R.framework/Versions/3.3/Resources/library"```. I went with the terminal window to this directory and typed ```R CMD build rJava``` and ```R CMD INSTALL rJava``` for recompiling (first time I recompile a R package, no idea if I did it right) and I got this succession of errors that finally ended up in automatically removing the rJava package:
### R CMD build rJava
```
* checking for file ‘rJava/DESCRIPTION’ ... OK
* preparing ‘rJava’:
* checking DESCRIPTION meta-information ... OK
Warning in file(con, "r") :
  was not possible to open file 'man': No such file or directory
Error in file(con, "r") : can't open connection
 ERROR
computing Rd index failed
```
### R CMD INSTALL rJava
```
* installing to library ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library’
ERROR: cannot install to srcdir for package ‘rJava’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava’


```


Since my rJava was uninstalled automatically. I installed it again from Rstudio typing on the terminal ```install.packages("rJava",,"http://rforge.net/",type="source")```. Now when I try to load the rJava library using ```library(rJava)``` I've got the next succession of errors:
```
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava/libs/rJava.so
  Reason: image not found
Error: package or namespace load failed for ‘rJava’
```

It is very probable that I did something wrong when I recompiled. Should have I used other commands maybe?

PS: Thanks for helping me out s-u

**Comment by s-u** [comment]
`install.packages('rJava',type='source')` is correct, but don't do it in RStudio since I recall they had a bug where it doesn't propagate Java settings correctly and I don't know if they fixed it.

**Comment by PedroReyes** [comment]
I went to the terminal and type ```sudo R``` and from there I typed ```install.packages('rJava',,'http://rforge.net',type='source')```as you advised me. Now, it seems that the library is installed at least.

Now, the problem is that rJava works perfectly from the terminal as soon as I enter in the command line of R using before ```sudo R```. The same code that works perfectly in this "sudo" console of R does not work in RStudio, any idea s-u? The error is the next one:

```
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/rJava/libs/rJava.so
  Reason: image not found
Error: package or namespace load failed for ‘rJava’
```

The code that I am talking about is 
```
library(rJava)
.jinit()
print(.jcall("java/lang/System", "S", "getProperty", "java.runtime.version"))
```

which returns in the "sudo R" terminal Java 1.8 finally. The point is that in RStudio (which is the place that must work) the very first line (```library(rJava)```) returns the error that I have written above. I think we are nearly there! xd. In the next picture you can see how in an "sudo R" terminal everything goes like a dream whereas in the "normal R" terminal fails at the first line.

<img width="1136" alt="rjavaterminal" src="https://cloud.githubusercontent.com/assets/4096108/21964411/b1d61e40-db4b-11e6-95b9-6c361f8c3518.png">

I have gone through webpages looking for an answer to this problem and the possible solutions up to now to this problem that didn't work for me are:

- Install Java 1.6, which I already did (the one from Apple, https://support.apple.com/kb/DL1572?viewlocale=en_US&locale=en_US).
- Set the JAVA_HOME to empty. It does not work neither if I set the JAVA_HOME to this location ```Sys.setenv(JAVA_HOME = "/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/")```
- Set the JAVA_HOME using the next command in R ```options(java.home="/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/")```

Finally (sorry for the big text but I am writting as I try to resolve the problem so if anybody goes through the same, then she/he will not have to loose a weekend for resolve a job issue xdd) I came across the solution typing this ```dyn.load('/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/server/libjvm.dylib')
```before this ```library(rJava)```.

Reference web page: http://charlotte-ngs.github.io/2016/01/MacOsXrJavaProblem.html

I have a last problem or it seems to me the last problem ... When I try to upload my ShinyApp I got this from the deploy console ```Uploading bundle for application: 139705...Error: Unable to retrieve package records for the following packages: 'rJava'```. It seems that this problem is because I installed the package from "forge.net", that is, the package is only installed locally, instead of installing the package from "CRAN". Could you upload the last version 0.9-9 to "CRAN" s-u? The issue is this one ```The package was installed locally from source. Only packages
installed from CRAN, BioConductor and GitHub are supported. Execution halted``` This is why I asked you put the version 0.9-9 into CRAN.

**Comment by s-u** [comment]
Sorry, this has nothing to do with rJava, please contact RStudio support. As you noticed yourself the issues are with RStudio as it doesn't set Java settings properly (or at least the way you use it).

Also this has nothing to do with RForge.net nor the version of rJava - it is the combination of RStudio and non-system Java. Hence there is nothing I can do about it - we only support system Java on CRAN, because only Apple Java has a valid system location that binaries can link agains, Oracle unfortunately doesn't provide it so the user has to configure R and link the binary against the installed location.
